project:
  type: website
  output-dir: docs

website:
  title: "Math326 Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Basics of Design"
      menu:
        - text: "Key Principles"
#This will include randomization, replication, local control, blocking (maybe) and crossing (maybe)
          href: key_principles.qmd
        - text: "Research Objectives"
          href: research_objectives.qmd
        - text: "Response Variable"
          href: response_variable.qmd
        - text: "Experimental Units"
          href: experimental_units.qmd
        - text: "Sources of Variation - Factors and Conditions"
          href: sources_of_variances.qmd
        - text: "Randomization"
          href: randomization.qmd
    - text: "Specific Designs"
      menu:
         - text: "Basic Factorial Introduction"
           href: BasicFactorial_intro.qmd
         - text: "BF[1]"
           href: BasicFactorial_quarto_boat.qmd
         - text: "BF[2]"
           href: bf2.qmd
         - text: "BF[3+]"
           href: bf3.qmd
         - text: "Blocking Introduction"
           href: block_intro.qmd
         - text: "CB[1]"
           href: cb1.qmd
         - text: "ANCOVA"
           href: ancova.qmd
         - text: "Latin Square"
           href: latin_square.qmd
         - text: "Nested Factor Designs Intro"
           href: nested_intro.qmd
         - text: "SP/RM[1,1]"
           href: split_plot.qmd

    - text: "Broad Topics"
      menu:
        - text: "Factor Structure"
          file: factor_structure.qmd
        - text: "Effects Model"
          file: effects_model.qmd
        - text: "ANOVA and the F-test"
          href: ANOVA_F-test.qmd
        - text: "Assumptions"
          href: assumptions.qmd
        - text: "Contrasts"
          href: contrast.qmd
        - text: "Multiple Comparisons"
          href: multiple_comparisons.qmd
        - text: "Unbalanced Datasets"
          href: unbalanced.qmd
        - text: "Random Factors and EMS"
          href: random_v_fixed.qmd

    - text: "R Instructions"
      menu:
        - text: "Descriptive Summaries"
          href: DescribeData.html
        - text: "Model diagnostics"
          href: diagnostics.html
    right:
    - text: "Datasets"
      menu:
        - text: "Download Zip Data"
          href: data/data_for_class.zip
        - text: "Data Page"
          href: data_for_class.qmd


format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

