project:
  type: website
  output-dir: docs

website:
  title: "Math326 Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Basics of Design"
      menu:
        - text: "Key Principles"
#This will include randomization, replication, local control, blocking (maybe) and crossing (maybe)
          href: key_principles.qmd
        - text: "Research Objectives"
          href: research_objectives.qmd
        - text: "Response Variable"
          href: response_variable.qmd
        - text: "Experimental Units"
          href: experimental_units.qmd
        - text: "Sources of Variation - Factors and Conditions"
          href: sources_of_variances.qmd
        - text: "Randomization"
          href: randomization.qmd
    - text: "Specific Designs"
      menu:
         - text: "Basic Factorial Introduction"
           href: BasicFactorial_intro.qmd
         - text: "BF[1]"
           href: BasicFactorial_quarto_boat.qmd
         - text: "BF[2]"
           href: bf2.qmd
         - text: "BF[3+]"
           href: BasicFactorial_quarto.qmd
         - text: "Block Designs"
           href: Block.html
         - text: "Covariate Designs"
           href: Covariate.html
         - text: "Nested Factor (aka Split Plot/Repeated Measure) Designs"
           href: NestedFactor.html
        # - text: "1 Factor, Completely Randomized, Basic Factorial"
        #   href: GraphicalSummaries.html
        # - text: "2 Factor, Completely Randomized, Basic Factorial"
        #   href: NumericalSummaries.html
        # - text: "3 Factor, Completely Randomized, Basic Factorial"
        #   href: NumericalSummaries.html
        # - text: "1 Factor, Complete Block"
        #   href: NumericalSummaries.html
        # - text: "Latin Square"
        #   href: NumericalSummaries.html
        # - text: "ANCOVA"
        #   href: NumericalSummaries.html
        # - text: "Split Plot/Repeated Measures"
        #   href: NumericalSummaries.html
    - text: "Broad Topics"
      menu:
        - text: "Factor Structure"
          file: factor_structure.qmd
        - text: "Effects Model"
          file: effects_model.qmd
        - text: "ANOVA and the F-test"
          href: Anova_F-test.qmd
        - text: "Assumptions"
          href: assumptions.qmd
        - text: "Contrasts"
          href: contrast.qmd
        - text: "Multiple Comparisons"
          href: multiple_comparisons.qmd
        - text: "Unbalanced Datasets"
          href: unbalanced.qmd
        - text: "ZPower??"
          href: Kruskal.html
        - text: "ZRandom Factors??"
          href: LogisticRegression.html

    - text: "R Instructions"
      menu:
        - text: "Descriptive Summaries"
          href: DescribeData.html
        - text: "Model diagnostics"
          href: diagnostics.html
  right:
    - text: "Datasets"
      menu:
        - text: "XYZ"
          href: ./Data/AnalysisRubric.html
        - text: "yadda yadda"
          href: ./Data/StudentHousing.html


format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

