---
title: "Experimental Units"
---

The **experimental unit** is the subject of the experiment. It is the entity to which the treatment factor levels are assigned. The **observational unit** is the entity on which the response measurements are taken. It is important to differentiate between the two, in cases in which they are different. It is important to consider the research objectives when determining the experimental unit and observational unit. Research objectives need to be revised when the experimental and observational units are not clearly defined. We will illustrate this importance by using two different examples.

The first example will study to see if a specific SAT prep class improves individual's SAT math scores. Twenty randomly selected students are randomly divided into two groups. One group will take the prep class and the other group will not take the class. In this case the experimental unit is the student because factor level assignments were made for each student. The observational unit is also the student because the math scores are measured for each student.

The next example will be slightly, but distinctly different. In this case, we will be applying a new teaching method to a math classroom to see if it improves math scores. Six randomly selected classrooms are randomly divided into 2 groups. One group will be randomly assigned the new teaching method and the other group will be randomly assigned the standard method. Within each classroom there are 25 students and math scores will be taken from each student. In this case, the classrooms are the experimental unit because the factor levels are assigned to each classroom. The students are the observational unit because the scores are measured for each student. The new teaching method will have 75 observations (3 classrooms with 25 students in each). However, the research objectives are concerning the *classroom,* and assignments of the teaching method are made at the classroom level, so the number of experimental units for each teaching method is just 3 for this analyses. Even though there were many observations, the limited number of experimental units limits the ability to make convincing inference to the broader population. We would like more classrooms involved be be more sure the succes/failure of the new teaching method was not due to a few particularly good/bad teachers. The researcher needs to be aware when this type of sampling is occurring so that a more complex analysis technique can be used to tease out the effect of teachers vs. method - and enhance our ability to make inference. This technique is discussed in further detail with the Nested Factor Designs.

Now let's apply this to the toothbrush study. Each person will be assigned to use one type of toothbrush, so person is the experimental unit. The measurements will be taken from teeth, so the observational unit will be tooth. If measurements are taken from multiple teeth, then a more complex design, like the Nested Factor designs should be considered.

------------------------------------------------------------------------
