<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Math326 Notebook - BF[1]</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Math326 Notebook</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-basics-of-design" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Basics of Design</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-basics-of-design">    
        <li>
    <a class="dropdown-item" href="./key_principles.html">
 <span class="dropdown-text">Key Principles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./research_objectives.html">
 <span class="dropdown-text">Research Objectives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./response_variable.html">
 <span class="dropdown-text">Response Variable</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./experimental_units.html">
 <span class="dropdown-text">Experimental Units</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sources_of_variances.html">
 <span class="dropdown-text">Sources of Variation - Factors and Conditions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./randomization.html">
 <span class="dropdown-text">Randomization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-specific-designs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Specific Designs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-specific-designs">    
        <li>
    <a class="dropdown-item" href="./BasicFactorial_intro.html">
 <span class="dropdown-text">Basic Factorial Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./BasicFactorial_quarto_boat.html">
 <span class="dropdown-text">BF[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bf2.html">
 <span class="dropdown-text">BF[2]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./BasicFactorial_quarto.html">
 <span class="dropdown-text">BF[3+]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./block_intro.html">
 <span class="dropdown-text">Blocking Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cb1.html">
 <span class="dropdown-text">CB[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ancova.html">
 <span class="dropdown-text">ANCOVA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NestedFactor.html">
 <span class="dropdown-text">Nested Factor (aka Split Plot/Repeated Measure) Designs</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-broad-topics" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Broad Topics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-broad-topics">    
        <li>
    <a class="dropdown-item" href="./factor_structure.html">
 <span class="dropdown-text">Factor Structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./effects_model.html">
 <span class="dropdown-text">Effects Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Anova_F-test.html">
 <span class="dropdown-text">ANOVA and the F-test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html">
 <span class="dropdown-text">Assumptions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./contrast.html">
 <span class="dropdown-text">Contrasts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./multiple_comparisons.html">
 <span class="dropdown-text">Multiple Comparisons</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unbalanced.html">
 <span class="dropdown-text">Unbalanced Datasets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Kruskal.html">
 <span class="dropdown-text">ZPower??</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./LogisticRegression.html">
 <span class="dropdown-text">ZRandom Factors??</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-instructions" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Instructions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-instructions">    
        <li>
    <a class="dropdown-item" href="./DescribeData.html">
 <span class="dropdown-text">Descriptive Summaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./diagnostics.html">
 <span class="dropdown-text">Model diagnostics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-datasets" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Datasets</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-datasets">    
        <li>
    <a class="dropdown-item" href="././Data/AnalysisRubric.html">
 <span class="dropdown-text">XYZ</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="././Data/StudentHousing.html">
 <span class="dropdown-text">yadda yadda</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul>
  <li><a href="#factor-structure" id="toc-factor-structure" class="nav-link" data-scroll-target="#factor-structure">Factor Structure</a></li>
  <li><a href="#hypothesis-and-model" id="toc-hypothesis-and-model" class="nav-link" data-scroll-target="#hypothesis-and-model">Hypothesis and Model</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  </ul></li>
  <li><a href="#design" id="toc-design" class="nav-link" data-scroll-target="#design">Design</a>
  <ul>
  <li><a href="#lifeboat-training-example" id="toc-lifeboat-training-example" class="nav-link" data-scroll-target="#lifeboat-training-example">Lifeboat Training Example</a></li>
  </ul></li>
  <li><a href="#decomposition" id="toc-decomposition" class="nav-link" data-scroll-target="#decomposition">Decomposition</a>
  <ul>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of Freedom</a></li>
  <li><a href="#factor-effects" id="toc-factor-effects" class="nav-link" data-scroll-target="#factor-effects">Factor Effects</a>
  <ul class="collapse">
  <li><a href="#calculate-means" id="toc-calculate-means" class="nav-link" data-scroll-target="#calculate-means">Calculate means</a></li>
  <li><a href="#calculate-effects" id="toc-calculate-effects" class="nav-link" data-scroll-target="#calculate-effects">Calculate effects</a></li>
  </ul></li>
  <li><a href="#completing-the-anova-table" id="toc-completing-the-anova-table" class="nav-link" data-scroll-target="#completing-the-anova-table">Completing the ANOVA table</a></li>
  </ul></li>
  <li><a href="#analysis-in-r" id="toc-analysis-in-r" class="nav-link" data-scroll-target="#analysis-in-r">Analysis in R</a>
  <ul>
  <li><a href="#describe-the-data" id="toc-describe-the-data" class="nav-link" data-scroll-target="#describe-the-data">Describe the Data</a>
  <ul class="collapse">
  <li><a href="#numerical-summaries" id="toc-numerical-summaries" class="nav-link" data-scroll-target="#numerical-summaries">Numerical Summaries</a></li>
  <li><a href="#graphical-summaries" id="toc-graphical-summaries" class="nav-link" data-scroll-target="#graphical-summaries">Graphical Summaries</a></li>
  </ul></li>
  <li><a href="#create-the-model" id="toc-create-the-model" class="nav-link" data-scroll-target="#create-the-model">Create the Model</a></li>
  <li><a href="#check-assumptions" id="toc-check-assumptions" class="nav-link" data-scroll-target="#check-assumptions">Check assumptions</a>
  <ul class="collapse">
  <li><a href="#constant-error-variance" id="toc-constant-error-variance" class="nav-link" data-scroll-target="#constant-error-variance">Constant Error Variance</a></li>
  <li><a href="#normally-distributed-error-term" id="toc-normally-distributed-error-term" class="nav-link" data-scroll-target="#normally-distributed-error-term">Normally Distributed Error Term</a></li>
  <li><a href="#independent-residuals" id="toc-independent-residuals" class="nav-link" data-scroll-target="#independent-residuals">Independent Residuals</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a>
  <ul>
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples">Examples</a></li>
  <li><a href="#links-to-outside-resources" id="toc-links-to-outside-resources" class="nav-link" data-scroll-target="#links-to-outside-resources">Links to outside resources</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BF[1]</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>
<section id="overview" class="level1 page-columns page-full">
<h1>Overview</h1>
<p>In a basic one-way factorial design (BF[1]), only one factor is purposefully varied.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Each experimental unit is assigned to exactly one factor level. (In the case of an observational study, only one independent factor is under consideration.)</p>
<section id="factor-structure" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-structure">Factor Structure</h2>
<p>The factor structure for the model resulting from a completely randomized, one factor design is:</p>
<div class="column-page">
<div id="fig-bf1-structure-with-equation" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF1_factor_structure_with_equation.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Example of BF1 Factor Structure</figcaption><p></p>
</figure>
</div>
</div>
<p><a href="#fig-bf1-structure-with-equation">Figure&nbsp;1</a> illustrates a factor with 4 levels, 6 replications at each level.</p>
</section>
<section id="hypothesis-and-model" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-and-model">Hypothesis and Model</h2>
<p>A more detailed description of the model for an ANOVA with just one factor:</p>
<p><span class="math display">\[
y_{ij} = \mu + \alpha_i + \epsilon_{ij}
\]</span></p>
<p><span class="math inline">\(y_{ij}\)</span>: the <span class="math inline">\(j^{th}\)</span> observation from factor level <span class="math inline">\(i\)</span></p>
<p><span class="math inline">\(\mu\)</span>: the grand mean of the data set.</p>
<p><span class="math inline">\(\alpha_i\)</span>: effect of factor level <span class="math inline">\(i\)</span></p>
<p><span class="math inline">\(\epsilon_{ij}\)</span>: the error term, or residual term of the model. There are <em>j</em> replicates for each treatment. It represents the distance from an observation to its factor level mean (or predicted value).</p>
<p>The null and alternative hypotheses can be expressed as:</p>
<p><span class="math display">\[
H_o: \alpha_1 = \alpha_2 = ... = 0
\]</span></p>
<p><span class="math display">\[
H_a: \alpha_i \neq 0 \quad \text{for at least one }\ \alpha_i
\]</span></p>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>A one-way ANOVA model may be used to analyze data from a BF[1] design if the following requirements are satisfied:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 36%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Requirements</th>
<th>Method for Checking</th>
<th>What You Hope to See</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Constant variance across factor levels</td>
<td>Rule of thumb comparing standard deviations</td>
<td><span class="math inline">\(max(s) &lt; 2*min(s)\)</span></td>
</tr>
<tr class="even">
<td></td>
<td>Residual vs.&nbsp;Fitted Plot</td>
<td>No major disparity in vertical spread of point groupings</td>
</tr>
<tr class="odd">
<td></td>
<td>Levene’s Test</td>
<td>Fail to reject <span class="math inline">\(H_0\)</span></td>
</tr>
<tr class="even">
<td>Normally Distributed Residuals</td>
<td>Normal Q-Q plot</td>
<td>Straight line, majority of points in boundaries</td>
</tr>
<tr class="odd">
<td>Independent residuals</td>
<td>Order plot</td>
<td>No pattern/trend</td>
</tr>
<tr class="even">
<td></td>
<td>Familiarity with/critical thinking about the experiment</td>
<td>No potential source for bias</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="design" class="level1">
<h1>Design</h1>
<p>In a one factor design, one factor is purposely varied and all other factors are controlled in order to isolate the effect of just the factor under study. Each level of the factor is considered a treatment.</p>
<p>In a completely randomized design, each experimental unit is randomly assigned to exactly 1 factor level. In this example we expect a balanced design (i.e.&nbsp;each factor level has the same number of observations) because the number of observations is a perfect multiple of the number of factor levels. To make random assignments, start by listing all the subjects, then listing the treatments, as seen below:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">6</td>
</tr>
</tbody>
</table>
<p>Then you randomly shuffle the treatment column. (You should also be paying attention to the order in which subjects and treatments are being experimented on as this could be a potential source of bias. In a BF[1], if it makes sense to do, you randomize the order also.) The result might look something like this.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>You may notice in the above example that, even with randomization, treatment C occurs in the last 2 observations. If we were truly concerned about the order we could be more strategic and implement a <strong><em>blocked design</em></strong> to prevent “unlucky” ordering and pairing.</p>
</div>
</div>
<p>The design above is laid out in “longer format”. In “longer format”, each row represents an observation. There is a column to indicate what treatment experimental unit received, a column to contain the value of the response variable, and (if necessary) a column to keep track of the order in which the observations are made. “Longer format” is what many softwares need, R included.</p>
<p>“Wider format” is how the design is laid out in the factor structure diagram. Each factor level has it’s own column. Each cell contains a response value for a particular subject. The order of the experimental runs becomes difficult to track/document in this format. This data format is often used for data collection and is often easier for humans (as opposed to machines) to digest. In “wider format” the above table would look like the following:</p>
<table class="table">
<caption>Wider Format Example</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Treatment A</th>
<th>Treatment B</th>
<th>Treatment C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Response for subject 5</td>
<td>Response for subject 6</td>
<td>Response for subject 3</td>
</tr>
<tr class="even">
<td>Response for subject 1</td>
<td>Response for subject 2</td>
<td>Response for subject 3</td>
</tr>
</tbody>
</table>
<section id="lifeboat-training-example" class="level2">
<h2 class="anchored" data-anchor-id="lifeboat-training-example">Lifeboat Training Example</h2>
<p>Consider the following example. An experiment was done to assess different modes of virtual training in how to launch a lifeboat. Sixteen students in the maritime safety training institute were a part of the study, and each of the students were assigned one of four possible virtual training experiences. The four experiences included:</p>
<ol type="1">
<li>Lecture/Materials (Control)</li>
<li>Monitor/Keyboard</li>
<li>Head Monitor Display/Joypad, and</li>
<li>Head Monitor Display/Wearables.</li>
</ol>
<p>The <a href="./response_variable.html">response variable</a> was the student’s performance on a procedural knowledge assessment (performance is defined as their level of improvement from pre to post test). There is just one <a href="./sources_of_variances.html">controlled factor</a>, training method, which has 4 levels: the four training methods. An <a href="./experimental_units.html">experimental unit</a> in this study is each of the individuals being trained, 16 in all.</p>
<p>We want to assign each treatment to four students. We could get 16 pieces of paper and write “Treatment 1” on 4 pieces, “Treatment 2” on another 4 pieces, and so on until each treatment has 4 pieces of paper. We could then put them in a hat, mix them up and then randomly draw out a piece of paper to assign it to a subject. Intuitively this makes sense, but writing and cutting paper is slow and inefficient. We could implement a similar process in R to assign treatments.</p>
<p>First, we list all the possible treatments, and repeat that listing until it is the same size as our count of subjects. (Note, if your number of subjects is not an exact multiple of the number of treatments, you may need to decide which treatments deserve fewer observations)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Repeat the sequence of 1 to 4, four times</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Treatment <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">4</span>) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a sequence from 1 to 16</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Paste the word "Subject " in front of each id #</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Subject <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Subject"</span>, <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>), <span class="at">sep =</span> <span class="st">" "</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Combine the vector of treatment numbers and Subject ID's into 1 tibble/data frame</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>assignment_table <span class="ot">&lt;-</span> <span class="fu">tibble</span>(Subject, Treatment)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#print the table, pander() makes it look nice</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(assignment_table) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 7</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 8</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 9</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 10</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 11</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 12</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 13</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 14</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 15</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 16</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Then we randomly shuffle the brush and paste column to get the following assignments. Check out the R-code to see how this is done.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#set.seed() allows us to get the same random sample each time</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>) </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#sample() will randomly select from the Treatment vector 16 times without replacement</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># %&gt;% is called a pipe. It simply takes the output from the command on the left</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># and sends it to the command on the right</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(Subject, <span class="fu">sample</span>(Treatment, <span class="dv">16</span>)) <span class="sc">%&gt;%</span> <span class="fu">pander</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 18%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">sample(Treatment, 16)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 7</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 8</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 9</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 10</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 11</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 12</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 13</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 14</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 15</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 16</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can see here that subject 1 should get treatment 2. Subject 2 gets treatment 4, Subject 3 gets treatment 1, and so on.</p>
</section>
</section>
<section id="decomposition" class="level1 page-columns page-full">
<h1>Decomposition</h1>
<p>This section serves as a bridge between the design and the analysis of an experiment. It is equivalent to doing the analysis by hand. The primary goal is to see how the design decisions impact the analysis; including a deeper understanding of what the numbers in an ANOVA table mean and how they are calculated.</p>
<p>The factor structure diagram of an experimental design is an effective way to organize and plan for the type of data needed for an experiment. Recall that in our lifeboat example there were four levels of training method with six replicates for each (the actual study used 16 observations per treatment). The diagram below gives the factor structure of the design, and the accompanying mathematical model.</p>
<div class="column-page">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/BF1_factor_structure_with_equation.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Example of BF1 Factor Structure</figcaption><p></p>
</figure>
</div>
</div>
<p>A basic one-way factorial design has three analysis factors: the grand mean, treatment, and residual. The effects of these factors can be summed together to find each observed value.</p>
<ul>
<li>The <strong>observed values</strong> on the left show that there are 24 distinct observations of performance score, represented by the 24 cells - one for each of the observed values.</li>
<li>The <strong>grand mean factor</strong> represents the grand mean. The single large cell indicates that there is only one grand mean and it is part of every observation.</li>
<li>The <strong>treatment factor</strong> involves the four methods of training, represented by the four vertically long cells. Each factor level may have a distinct mean and effect.</li>
<li>The <strong>residual error</strong> represents the difference between the observed value and the predicted value. The predicted value, also called the fitted value, is the sum of the grand mean and factor level effect. Each of the cells represent a distinct value for the residual error.</li>
</ul>
<section id="degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h2>
<p>We can use our understanding of <a href="./factor_structure.html">inside vs.&nbsp;outside factors</a> to determine the degrees of freedom (df) for the <strong>grand mean</strong>, <strong>treatment</strong>, and <strong>residual errors</strong> factors. We start with 24 observations - or pieces of information. In other words, we have 24 degrees of freedom that need to be allocated to the 3 factors.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
General Rule for Degrees of Freedom
</div>
</div>
<div class="callout-body-container callout-body">
<p>df<span class="math inline">\(_\text{factor}\)</span> = Total levels of a factor minus the sum of the df of all outside factors</p>
<p>An alternative way to find degrees of freedom is to count the number of unique pieces of information in a factor.</p>
</div>
</div>
<p>In the lifeboat example, <strong>grand mean</strong> has one level (shown by the one cell in <a href="#fig-bf1-structure-with-equation">Figure&nbsp;1</a>) and there are no factors outside of grand mean. Therefore, its degrees of freedom equals one.</p>
<p>Remember, the degrees of freedom represent the number of unique pieces of information contributing to the estimation of the effects for that factor. In this case, as soon as you estimate the grand mean for just one of the observations, you know it for all the observations. In other words, only 1 value was <em>free</em> to vary. As soon as it was known all the other values for the grand mean effect were also known. Therefore, there is just one unique piece of information in the grand mean factor. Grand mean has just 1 degree of freedom.</p>
<p>For <strong>treatment factor</strong>, there are four levels of the factor (shown by the four vertically long cells for treatment factor in <a href="#fig-bf1-structure-with-equation">Figure&nbsp;1</a>). Grand mean is the only factor outside of training method. Take the number of levels for training method (4) and subtract the degrees of freedom for grand mean (1), which yields 4-1 = <strong>3 degrees of freedom</strong> for training method.</p>
<p>We could just as easily have used the other approach to finding the degrees of freedom: counting the unique pieces of information the training method effects really contain. Since all observations from the same training method will have the same effect, we only need to know 4 pieces of information: the effect of each training method. But the answer is actually less than that! Because we know that the effects must all sum to zero, only 3 of the effects are free to vary and the 4th one is constrained to be whatever value will satisfy this mathematical condition. Thus, the degrees of freedom are 3. As soon as we know 3 of the effects for training method, we can fill in the training method effects for all the observations.</p>
<p>For <strong>residual errors</strong>, there are 24 levels of the factor (as shown by the 24 cells for residual error on the far right of <a href="#fig-bf1-structure-with-equation">Figure&nbsp;1</a>). Both grand mean and training method are outside of the residual errors factor. Take the number of levels for the residual error (24) and subtract the sum of the degrees of freedom for grand mean and training method (3+1=4). The residual error has 24 - (3+1) = <strong>20 degrees of freedom</strong>.</p>
<p>The approach of counting unique pieces of information can be applied here as well. In this case, we use the fact that the residual factor effects must sum to zero within each treatment. So within each treatment, 5 of the observations are free to vary, but the 6th will be determined by the fact that their sum must be zero. Five observations multiplied by 4 levels of training method is 20 observations, or in other words, 20 degrees of freedom.</p>
</section>
<section id="factor-effects" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-effects">Factor Effects</h2>
<p>We can use our understanding of <a href="./factor_structure.html">inside vs.&nbsp;outside factors</a> to estimate the effect size of the grand mean, training methods, and residual errors factors in the lifeboat training study. In other words, we can estimate the terms in the one-way ANOVA model.</p>
<div id="effect-rule" class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
General Rule for Effect Size
</div>
</div>
<div id="effect-rule" class="callout-body-container callout-body">
<p>Effect size = factor level mean - the sum of the effects of all outside factors</p>
</div>
</div>
<section id="calculate-means" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="calculate-means">Calculate means</h3>
<p>To estimate all the factor effects we must first calculate the mean for the grand mean factor and the means for each level of training method.</p>
<p>To get the grand mean, average all 24 observations. The mean for all the observations is 6.5846. There is only one level for grand mean so this number is placed into each of the cells for the grand mean factor in <a href="#fig-training-means">Figure&nbsp;2</a>.</p>
<p>For the treatment factor, calculate the mean of each of the four levels. To calculate the mean for Control:</p>
<p><span class="math display">\[
\frac{4.5614 + 6.6593 + 5.6427 + 6.4394 + 4.8635 + 0.3268}{6} = 4.7489
\]</span></p>
<p>You can similarly find the mean for monitor keyboard is 7.8492, the mean for head monitor display/joypad is 6.5789, and the mean for head monitor display/wearables is 7.1616. In <a href="#fig-training-means">Figure&nbsp;2</a> these means are placed in the respective training method column.</p>
<p>We do not need to calculate means for residual error factor because for two reasons. First, there is only one observation per level of residual error, so the mean is the observation itself. Second, nothing is inside of residual error. It is the last step in the process and its mean is not needed to calculate factor effects.</p>
<div class="column-page">
<div id="fig-training-means" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF1_means_decomp.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Raw data and means for grand mean and training factors</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="calculate-effects" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="calculate-effects">Calculate effects</h3>
<p>Now that we have calculated means for each level of each factor, we can move on to calculate the effects of the factor levels. We will use the general formula for calculating effect size.</p>
<p>For the grand mean, there is only one level and there are no outside factors. Therefore, the effect due to grand mean is 6.5846 (equivalent to its mean) and this affect is applied to all 24 observations.</p>
<p>The training method factor has four levels: one for each method. To calculate the effect of a training method, take the training method mean and subtract it from the effect due to the grand mean factor. For the “Control” method, this looks like:</p>
<p><span class="math display">\[
4.789 - 6.5846 = -1.8358
\]</span></p>
<p>Being in the control group has the effect of <em>reducing</em> the student’s performance by 1.8358 on average compared to the grand mean. In a similar way you can find the effect for Monitor/Keyboard <span class="math inline">\(7.8492 - 6.5846 = 1.2645\)</span>. This means the student performance scores increased by 1.2645 on average in this training method compared to the grand mean. For Head Monitor Display/Joypad, the effect is <span class="math inline">\(6.5789 - 6.5846 = -0.0058\)</span>. For Head Monitor Display/Wearables the effect is <span class="math inline">\(7.1616 - 6.5846 = 0.5770\)</span> (see below).</p>
<div class="column-page">
<div id="fig-training-effects" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF1_trt_effect_boat_decomp.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Training Method Effects</figcaption><p></p>
</figure>
</div>
</div>
<p>To calculate the residual error effects remember that there are 24 levels of the residual error factor. Therefore, the factor level mean for a residual is simply the observed value itself. This means the residual effect can be calculated by taking an observed value and subtracting the effects for grand mean and the effect for whichever training method that particular observation received. For instance, for the observation located in the top left of our data set the value is 4.5614. Subtract the sum of the effects of outside factors (grand mean and training). This observation was from the control group so we get:</p>
<p><span class="math display">\[
4.5614 - (6.5846 + -1.8358) = -0.1875
\]</span></p>
<p>The value for the top left cell in residual error effects is -0.1875. This means the observed value of 4.5614 was lower than we would have expected it to be. In other words, the performance score of 4.5614 was 0.1875 <em>less</em> than the mean of the control group. This individual’s performance was lower than the mean of his/her peers who received the same type of training.</p>
<p>We can repeat the residual calculation for the first observation in the second column. Take the observed value (5.4532) and subtract the sum of the effect due to grand mean and its respective training (in this case monitor/keyboard). The residual is</p>
<p><span class="math display">\[
5.4523 - (6.5846 + 1.2645) = -2.3960
\]</span></p>
<p>Repeat this process for all the remaining 22 residual values. The result is shown in <a href="#fig-residual-effects">Figure&nbsp;4</a>.</p>
<div class="column-page">
<div id="fig-residual-effects" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF1_effect_boat_decomp.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Residual Effects</figcaption><p></p>
</figure>
</div>
</div>
</section>
</section>
<section id="completing-the-anova-table" class="level2">
<h2 class="anchored" data-anchor-id="completing-the-anova-table">Completing the ANOVA table</h2>
<p>Now that we have calculated degrees of freedom and effects for each factor in a basic one-way factorial design, we can calculate the remaining pieces of the ANOVA table: <strong>Sum of Squares (SS), Mean Squares (MS), F-statistic and p-value</strong>. An ANOVA table essentially steps through the variance calculation that is needed to calculate the F statistics of an ANOVA test. In other words, a completed ANOVA summary table contains the information we need for a hypothesis test of a treatment factor.</p>
<p>In an ANOVA table, each factor and their associated degrees of freedom are listed on the left. Note: the total degrees of freedom are the total number of observations.</p>
<div class="cell">
<div class="cell-output-display">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:left;"> SS </th>
   <th style="text-align:left;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Factor </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>To get the <strong>sum of squares (SS)</strong> for a factor, the factor’s effect needs to be squared. This is done for each observation. Then all the squared values are summed up to get the sum of squares.</p>
<p>For <strong>grand mean</strong>, the effect of 6.5845 is listed 24 times, once for each observation. The value of 6.5845 will be squared. This squaring will be done 24 times and the squared values will then be added together to get the sum of squares due to grand mean.</p>
<p><span class="math display">\[
SS_\text{Grand Mean} = (6.5845)^2 + (6.5845)^2 + ... + (6.5845)^2 = 24*(6.5845)^2 = 1040.57
\]</span></p>
<p><br></p>
<p>The <strong>treatment factor</strong>, training method, has four different effects: one for each level of the factor. For each effect, the value is squared and then multiplied by the number of observations within the level of the factor. Then, the results are added across all levels to get the sum of squares due to training method. For instance, for the control group, the effect is -1.8358. That value is squared, and then the squared values is multiplied by six due to the six observations within the control group. This is done for the other three levels as well and then the resulting values from the four levels are added.</p>
<p><span class="math display">\[
SS_\text{Factor} = 6*(-1.8358)^2 + 6*(1.2645)^2 + 6*(-0.0058)^2 + 6*(0.5770)^2 = 31.81
\]</span> <br></p>
<p>The effect for the <strong>residual error factor</strong> has 24 unique values. Each of those residuals are squared and then the squared values are summed together.</p>
<p><span class="math display">\[
SS_\text{Residuals} = (-0.1875)^2 + (1.9105)^2 + (0.8939)^2 + (1.6906)^2 + ... + (-2.0157)^2 = 100.49
\]</span> <br></p>
<p>To get the <strong>total sum of squares</strong>, we can either square all the observations and then add the squared values,</p>
<p><span class="math display">\[
SS_\text{Total} = (4.5614)^2 + (6.6593)^2 + (5.6427)^2 + (6.4394)^2 + ... + (5.1459)^2 = 1172.87
\]</span></p>
<p><strong>-OR-</strong> we can get the same result if we add together the sum of squares for the grand mean factor, treatment factor, and residual error factor.</p>
<p><span class="math display">\[
SS_\text{Total} = 1040.57 + 31.81 + 100.49 = 1172.87
\]</span></p>
<p><br> <br></p>
<div class="cell">
<div class="cell-output-display">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:left;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Factor </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 31.81 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 100.49 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 1172.87 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Recall that SS is a measure of total variability. Comparing factors on total variability isn’t exactly fair.</p>
<p>Consider for a moment 2 classes that were competing in a canned food drive. One class collected 150 cans. The other class collected 3,000 cans. The second class seems to have one. But is it a fair comparison? What if the first class had 10 students and the second class had 300 students. If we are interested in determining which class was more effective at getting canned food donations, we should somehow account for the difference in class size. If we divide the total cans by the number of students, we get the mean number of cans collected per student. We see the first class collected 15 cans per student, and the second class only collected 10 cans per student.</p>
<p>Like the canned food drive example, differences in SS for a factor may be due in part to differences in number of levels for each factor. (For example, the residual factor has 24 factor levels, while toothbrush only has 4). We will convert this total variability (sum of squares) into a mean variability (mean square) measure to properly account for differences in number of factor levels. This allows us to compare the factors’ variability on a standardized scale.</p>
<p>We calculate the mean squared error column, or <strong>mean square (MS)</strong>, by dividing the sum of squares by the number of unique pieces of information that make up the factor. In this way we convert a total (the sum of squares) into an average; or in other words we change a sum into a mean. The mean squared error is the same as a variance. (The Root Mean Squared Error is equivalent to a standard deviation). The MS is calculated in this manner for each of the effects.</p>
<p>The purpose of the ANOVA table is to partition or break apart the variability in the dataset to its component pieces. This works when looking at SS, since it is the total variance due to each factor. Mean squares is then the average variability for each effect and clearly shows which factor is a bigger source of variability.</p>
<p>The mean square calculations are:</p>
<p><span class="math display">\[
MS_\text{Grand Mean} = \frac{SS_\text{Grand Mean}}{df_\text{Grand Mean}} = \frac{1040.57}{1} = 1040.57
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Factor} = \frac{SS_\text{Factor}}{df_\text{Factor}} = \frac{31.81}{3} = 10.60
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Residual Error} = \frac{SS_\text{Residual Error}}{df_\text{Residual Error}} = \frac{100.49}{20} = 5.02
\]</span></p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:right;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Factor </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 31.81 </td>
   <td style="text-align:right;"> 10.60 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 100.49 </td>
   <td style="text-align:right;"> 5.02 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 1172.87 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The treatment factor, in this case training method, is the primary factor of interest so the <strong>F test statistic</strong> is only calculated for that factor. To get the F test statistic for the treatment factor take the mean square (MS) due to treatment factor and divide by the mean square (MS) due to the residual error. Since the mean square error is equivalent to a variance, you can think of the F statistics as the ratio of variance between treatment means over the variance of the distances for observed values to their respective treatment mean. Simply put, it is the between groups variance divided by the within group variance.</p>
<p><span class="math display">\[
F_\text{Factor} = \frac{MS_\text{Treatment Factor}}{MS_\text{Residual Error}} = \frac{10.6}{5.02} = 2.11
\]</span></p>
<p><br></p>
<p>To complete the ANOVA, table, the <strong>p-value for the treatment factor</strong> is calculated based on the F statistic and the degrees of freedom for both treatment factor and residual error. In practice, statistical software computes all the components of the ANOVA table, including the p-value. To complete the decomposition of variance in a manual way, the p-value is calculated in R using the <code>pf()</code> function: <code>1 - pf(test statistic, df of Treatment, df of Residual error)</code>.</p>
<p>In this example, we get</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(<span class="fl">2.11</span>, <span class="dv">3</span>, <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1310051</code></pre>
</div>
</div>
<p>This p-value, 0.1310, is greater than a typical level of significance (0.05), so we would fail to reject the null hypothesis that all the effects due to the treatment factor are equal to zero. Meaning, we have insufficient evidence to say that any of the training methods had an impact on procedural knowledge test scores regarding launching a life boat.</p>
<div class="cell">
<div class="cell-output-display">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:right;"> MS </th>
   <th style="text-align:right;"> Fvalue </th>
   <th style="text-align:right;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Factor </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 31.81 </td>
   <td style="text-align:right;"> 10.60 </td>
   <td style="text-align:right;"> 2.11 </td>
   <td style="text-align:right;"> 0.131 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 100.49 </td>
   <td style="text-align:right;"> 5.02 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 1172.87 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
</section>
<section id="analysis-in-r" class="level1">
<h1>Analysis in R</h1>
<p>We will illustrate the R code using the lifeboat launch training example with just 6 observations per training method.</p>
<section id="describe-the-data" class="level2">
<h2 class="anchored" data-anchor-id="describe-the-data">Describe the Data</h2>
<p>When working with a dataset the first thing to do is get to know your data through numerical and graphical summaries. Numerical summaries typically consist of means, standard deviations, and sample sizes for each factor level. Graphical summaries most usually are boxplots or scatterplots with the means displayed.</p>
<p>Interactive code and additional explanations of numerical summaries and plots in R are found at <a href="DescribeData.html">R Instructions-&gt;Descriptive Summaries</a> section of the book.</p>
<section id="numerical-summaries" class="level3">
<h3 class="anchored" data-anchor-id="numerical-summaries">Numerical Summaries</h3>
<div class="cell">

</div>
<p>After loading required packages, we will read in the data and do some wrangling.</p>
<div class="cell" data-cap="Read in / Wrangle Data">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Reduced data to match decomposition example</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>virtual <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/virtual_training_redux.csv"</span>) </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#A bit of data wrangling</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>virtual <span class="ot">&lt;-</span> virtual <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Treatment =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>           grp.trt <span class="sc">%in%</span> <span class="dv">1</span>  <span class="sc">~</span> <span class="st">"Control"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>           grp.trt <span class="sc">%in%</span> <span class="dv">2</span>  <span class="sc">~</span> <span class="st">"Monitor/Keyboard"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>           grp.trt <span class="sc">%in%</span> <span class="dv">3</span>  <span class="sc">~</span> <span class="st">"Joypad"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>           grp.trt <span class="sc">%in%</span> <span class="dv">4</span>  <span class="sc">~</span> <span class="st">"Wearables"</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We then calculate summary statistics for each level of training method, in <a href="#tbl-numerical">Table&nbsp;1</a>. Monitor/Keyboard has the highest mean (7.16) and median (8.33). It appears to be the best training method. Our ANOVA will seek to know if differences between training methods are statistically significant.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(procKnow<span class="sc">~</span>Treatment, <span class="at">data =</span> virtual) <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="tbl-numerical" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;"><caption>Table&nbsp;1:  Numerical Summary </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Treatment </th>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> Q1 </th>
   <th style="text-align:right;"> median </th>
   <th style="text-align:right;"> Q3 </th>
   <th style="text-align:right;"> max </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> missing </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Control </td>
   <td style="text-align:right;"> 0.33 </td>
   <td style="text-align:right;"> 4.64 </td>
   <td style="text-align:right;"> 5.25 </td>
   <td style="text-align:right;"> 6.24 </td>
   <td style="text-align:right;"> 6.66 </td>
   <td style="text-align:right;"> 4.75 </td>
   <td style="text-align:right;"> 2.32 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Joypad </td>
   <td style="text-align:right;"> 1.88 </td>
   <td style="text-align:right;"> 6.25 </td>
   <td style="text-align:right;"> 6.61 </td>
   <td style="text-align:right;"> 8.25 </td>
   <td style="text-align:right;"> 9.45 </td>
   <td style="text-align:right;"> 6.58 </td>
   <td style="text-align:right;"> 2.65 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Monitor/Keyboard </td>
   <td style="text-align:right;"> 5.45 </td>
   <td style="text-align:right;"> 6.78 </td>
   <td style="text-align:right;"> 8.33 </td>
   <td style="text-align:right;"> 8.78 </td>
   <td style="text-align:right;"> 9.78 </td>
   <td style="text-align:right;"> 7.85 </td>
   <td style="text-align:right;"> 1.65 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wearables </td>
   <td style="text-align:right;"> 4.94 </td>
   <td style="text-align:right;"> 5.21 </td>
   <td style="text-align:right;"> 7.03 </td>
   <td style="text-align:right;"> 8.91 </td>
   <td style="text-align:right;"> 9.83 </td>
   <td style="text-align:right;"> 7.16 </td>
   <td style="text-align:right;"> 2.22 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="graphical-summaries" class="level3">
<h3 class="anchored" data-anchor-id="graphical-summaries">Graphical Summaries</h3>
<p>You should also visualize the data. Since there are only six data point, a scatter plot may be preferred over a boxplot.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> virtual, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>Treatment, <span class="at">y =</span> procKnow, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">geom=</span> <span class="st">"line"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Training Method"</span>, <span class="at">y =</span> <span class="st">"Process Knowledge Test Score"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Process Knowledge Scores by Training Method"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Group Means Connected with a Line"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-summary" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="BasicFactorial_quarto_boat_files/figure-html/fig-summary-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Graphical Summary</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>This plot reinforces the conclusion that Monitor/Keyboard tends to have higher scores. The outliers in the Control and Joypad method also become very apparent.</p>
</section>
</section>
<section id="create-the-model" class="level2">
<h2 class="anchored" data-anchor-id="create-the-model">Create the Model</h2>
<p>You then create the model using the <code>aov()</code> function. To see results of the F-test you can feed your model into a <code>summary()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>myaov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Y <span class="sc">~</span> X, <span class="at">data=</span>YourDataSet)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>myaov</code> is the user defined name in which the results of the aov() model are stored</li>
<li><code>Y</code> is the name of a numeric variable in your dataset which represents the quantitative response variable.</li>
<li><code>X</code> is the name of a qualitative variable in your dataset. It should have class(X) equal to factor or character. If it does not, use <code>factor(X)</code> inside the <code>aov(Y ~ factor(X),...)</code> command.</li>
<li><code>YourDataSet</code> is the name of your data set.</li>
</ul>
<p><strong>Example Code</strong></p>
<a href="javascript:showhide('bff1')">
<div class="hoverchunk">
<p><span class="tooltipr"> method_aov<span class="tooltiprtext">A name you come up with for your model</span> </span><span class="tooltipr"> &lt;- <span class="tooltiprtext">The assignment operator. The result to the right of it gets stored in an object specified on the left</span> </span><span class="tooltipr"> aov( <span class="tooltiprtext">A function to define the model</span> </span><span class="tooltipr"> procKnow <span class="tooltiprtext">The response, or y, variable in the model. It is numeric.</span> </span><span class="tooltipr"> ~ <span class="tooltiprtext">The ~ is like an equal sign in the model. Items on the left of ~ represent y, on the right you define independent factors (i.e.&nbsp;x’s).</span> </span><span class="tooltipr"> Treatment, <span class="tooltiprtext">The independent variable containing the names for the 4 training methods</span> </span><span class="tooltipr"> data = virtual <span class="tooltiprtext">Tell the model to look in the dataset named “virtual” for procKnow and Treatment variables</span> </span><span class="tooltipr"> ) <span class="tooltiprtext">Functions always end with a closing parenthesis</span> </span><br><span class="tooltipr"> summary( <span class="tooltiprtext">Give important information about an object. When called on an aov object the default is to print the ANOVA summary table</span> </span><span class="tooltipr"> method_aov <span class="tooltiprtext"> Whatever you named your ANOVA model in the previous line </span></span> <span class="tooltipr"> ) <span class="tooltiprtext"> Functions always end with a closing parenthesis </span></span><br><span class="tooltipr" style="float:right;"> Click to toggle output <span class="tooltiprtext">Click to toggle output.</span> </span></p>
</div>
</a>
<div id="bff1" style="display:show;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Treatment    3  31.81  10.604   2.111  0.131
Residuals   20 100.49   5.024               </code></pre>
</div>
</div>
</div>
<p>We then interpret the results. Training method does not appear to be a significant factor since the p-value (0.131) is higher than our significance level of 0.05. Therefore, we cannot conclude that one training method results in a better mean test score than another.</p>
</section>
<section id="check-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-assumptions">Check assumptions</h2>
<p>Now that the model is created the assumptions need to be checked. Interactive code and additional explanation for assumption checking can be found in the <a href="docs/diagnostics.html">Model Diagnostics</a> and <a href="./assumptions.html">Assumptions</a> sections of the book respectively.</p>
<p>Below, we find that all assumptions of our lifeboat training method model are met and we can trust the hypothesis test that was just conducted.</p>
<section id="constant-error-variance" class="level3">
<h3 class="anchored" data-anchor-id="constant-error-variance">Constant Error Variance</h3>
<p>We first check to see if the levels of training method have constant variance. The points in <a href="#fig-summary">Figure&nbsp;5</a> have similar spread, with the exception of the particularly low outlier scores in the Control and Joypad groups. Furthermore, in <a href="#tbl-numerical">Table&nbsp;1</a> we see that the largest standard deviation (2.65 for Joypad) is not more than double the smallest standard deviation (1.65 for Monitor/Keyboard). Therefore, the assumption of constant variance appears to be met.</p>
</section>
<section id="normally-distributed-error-term" class="level3">
<h3 class="anchored" data-anchor-id="normally-distributed-error-term">Normally Distributed Error Term</h3>
<p>A QQ-plot of the residuals is shown in <a href="#fig-qq">Figure&nbsp;6</a>. Since none of the points are outside of the boundary it is safe to conclude that residuals are normally distributed.</p>
<div class="cell">

</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(method_aov<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13  6</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-qq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="BasicFactorial_quarto_boat_files/figure-html/fig-qq-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: QQplot of Model Residuals</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="independent-residuals" class="level3">
<h3 class="anchored" data-anchor-id="independent-residuals">Independent Residuals</h3>
<p>Nothing about the study suggests a lack of independence among the residuals. The data was obtained second hand. If possible, you should ask the principal researcher more about how the data was collected. For our purposes, we will assume the row number in the dataset does <em>not</em> represent the order in which the data was originally collected. Therefore, an order plot would not be helpful in detecting order bias. Thus, based on everything we know about the study, we have no reason to suspect the independent residuals assumption is violated.</p>
</section>
</section>
</section>
<section id="resources" class="level1">
<h1>Resources</h1>
<section id="examples" class="level3">
<h3 class="anchored" data-anchor-id="examples">Examples</h3>
<p><a href="examples/VirtualTrain.html">Lifeboat launch training with a full dataset</a></p>
<p><a href="examples/mosquito.html">Mosquito</a></p>
</section>
<section id="links-to-outside-resources" class="level3">
<h3 class="anchored" data-anchor-id="links-to-outside-resources">Links to outside resources</h3>
<p>Populate this section yourself with links to good examples, definitions, other sections within this textbook, or anything else you think will be interesting/helpful.</p>
<hr>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>It can be argued that this design is not technically a factorial design because only one experimental factor is involved. However, we categorize it with the other basic factorial designs because the assignment of subjects to factor levels is done completely at random, just as it is for the other basic factorial designs covered in this course.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>