<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.344">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Math326 Notebook - Randomized, Basic Factorial Experiments</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link id="quarto-text-highlighting-styles" href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Math326 Notebook</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-basics-of-design" role="button" data-bs-toggle="dropdown" aria-expanded="false">Basics of Design</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-basics-of-design">    
        <li>
    <a class="dropdown-item" href="./RCommands.html">
 <span class="dropdown-text">Key Principles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./RMarkdownHints.html">
 <span class="dropdown-text">Choosing a response variable</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./RCheatSheetsAndNotes.html">
 <span class="dropdown-text">Choosing conditions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./DataSources.html">
 <span class="dropdown-text">Choosing units/experimental material</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-specific-designs" role="button" data-bs-toggle="dropdown" aria-expanded="false">Specific Designs</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-specific-designs">    
        <li>
    <a class="dropdown-item" href="./BasicFactorial.html">
 <span class="dropdown-text">Completely Randomized, Basic Factorial Designs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Block.html">
 <span class="dropdown-text">Block Designs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Covariate.html">
 <span class="dropdown-text">Covariate Designs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NestedFactor.html">
 <span class="dropdown-text">Nested Factor (aka Split Plot/Repeated Measure) Designs</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-broad-topics" role="button" data-bs-toggle="dropdown" aria-expanded="false">Broad Topics</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-broad-topics">    
        <li>
    <a class="dropdown-item" href="./factor_structure.html">
 <span class="dropdown-text">Factor Structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./effects_model.html">
 <span class="dropdown-text">Effects Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Anova_F-test.html">
 <span class="dropdown-text">ANOVA and the F-test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ANOVA.html">
 <span class="dropdown-text">ZModel Assumptions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./MakingInference.html">
 <span class="dropdown-text">ZMultiple Pairwise Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./MakingInference.html">
 <span class="dropdown-text">ZMultiple Pairwise Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Kruskal.html">
 <span class="dropdown-text">ZPower</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./LogisticRegression.html">
 <span class="dropdown-text">ZRandom Factors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WilcoxonTests.html">
 <span class="dropdown-text">ZUnbalanced Datasets</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-instructions" role="button" data-bs-toggle="dropdown" aria-expanded="false">R Instructions</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-instructions">    
        <li>
    <a class="dropdown-item" href="./DescribeData.html">
 <span class="dropdown-text">Descriptive Summaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./model_diagnostics.html">
 <span class="dropdown-text">Model diagnostics</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#bf1" id="toc-bf1" class="nav-link active" data-scroll-target="#bf1">BF[1]</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#design" id="toc-design" class="nav-link" data-scroll-target="#design">Design</a></li>
  <li><a href="#decomposition-and-factor-structure" id="toc-decomposition-and-factor-structure" class="nav-link" data-scroll-target="#decomposition-and-factor-structure">Decomposition and Factor Structure</a></li>
  <li><a href="#r-instructions" id="toc-r-instructions" class="nav-link" data-scroll-target="#r-instructions">R Instructions</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a></li>
  </ul></li>
  <li><a href="#bf2" id="toc-bf2" class="nav-link" data-scroll-target="#bf2">BF[2]</a>
  <ul class="collapse">
  <li><a href="#overview-1" id="toc-overview-1" class="nav-link" data-scroll-target="#overview-1">Overview</a></li>
  <li><a href="#design-1" id="toc-design-1" class="nav-link" data-scroll-target="#design-1">Design</a></li>
  <li><a href="#decomposition" id="toc-decomposition" class="nav-link" data-scroll-target="#decomposition">Decomposition</a></li>
  <li><a href="#r-instruction" id="toc-r-instruction" class="nav-link" data-scroll-target="#r-instruction">R Instruction</a></li>
  <li><a href="#resources-1" id="toc-resources-1" class="nav-link" data-scroll-target="#resources-1">Resources</a></li>
  </ul></li>
  <li><a href="#bf3" id="toc-bf3" class="nav-link" data-scroll-target="#bf3">BF[3]</a>
  <ul class="collapse">
  <li><a href="#overview-2" id="toc-overview-2" class="nav-link" data-scroll-target="#overview-2">Overview</a></li>
  <li><a href="#design-2" id="toc-design-2" class="nav-link" data-scroll-target="#design-2">Design</a></li>
  <li><a href="#decomposition-1" id="toc-decomposition-1" class="nav-link" data-scroll-target="#decomposition-1">Decomposition</a></li>
  <li><a href="#r-instruction-1" id="toc-r-instruction-1" class="nav-link" data-scroll-target="#r-instruction-1">R Instruction</a></li>
  <li><a href="#resources-2" id="toc-resources-2" class="nav-link" data-scroll-target="#resources-2">Resources</a></li>
  </ul></li>
  <li><a href="#fractional-factorial-designs" id="toc-fractional-factorial-designs" class="nav-link" data-scroll-target="#fractional-factorial-designs">Fractional Factorial Designs</a>
  <ul class="collapse">
  <li><a href="#overview-3" id="toc-overview-3" class="nav-link" data-scroll-target="#overview-3">Overview??</a></li>
  <li><a href="#how-many-treatments-design-rank" id="toc-how-many-treatments-design-rank" class="nav-link" data-scroll-target="#how-many-treatments-design-rank">How many treatments, design rank</a></li>
  <li><a href="#confounding-and-a-generating-function" id="toc-confounding-and-a-generating-function" class="nav-link" data-scroll-target="#confounding-and-a-generating-function">Confounding and a Generating Function</a></li>
  <li><a href="#anything-else" id="toc-anything-else" class="nav-link" data-scroll-target="#anything-else">Anything else??</a></li>
  <li><a href="#additional-resources-and-links" id="toc-additional-resources-and-links" class="nav-link" data-scroll-target="#additional-resources-and-links">Additional resources and links</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Randomized, Basic Factorial Experiments</h1>
</div>





<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<hr>
<p>The experimental designs in this section have 2 key characteristics in common:</p>
<ul>
<li>Conditions are assigned to subjects (a.k.a. experimental units) completely at random</li>
<li>The way error is accounted for in all these designs and the way the requirements are checked can be approached the same way</li>
</ul>
<p>To assign something <strong>completely at random</strong> means that each experimental unit has a known and equal chance of being selected for a particular treatment and that no other considerations are taken into account when making treatment assignments. Usually, for balance, the same number of units are assigned to each treatment. For example, if I have 4 treatment and 16 units, I may use a computer to randomly shuffle the units into treatment groups.</p>
<p>Factorial experiments involve two or more factors that are crossed. <strong>Factorial crossing</strong> means that each combination of factor levels is considered as a treatment in the study. (A study with just one factor is not technically a factorial design, but we will lump it in with our discussion of factorial experiments her because of the completely random treatment assignment).</p>
<p>Contrast a factorial design with the one-at-a-time approach. In a one-at-a-time approach, if I had two factors I wanted to study I would run two separate experiments to evaluate the effect of each factor on the response one-at-time. Factorial designs have a couple of major advantages over one-factor-at-a-time studies.</p>
<ol type="1">
<li>They are a more efficient use of our time and material: I can get information about both of my factors from just one experimental unit</li>
<li>Perhaps most importantly, factorial designs allow the researcher to estimate interaction effects. Or in other words, we can observe how one factor’s effect on the response variable changes for different levels of the other factor.</li>
</ol>
<p>EXAMPLE of BF2???</p>
<p>In summary, “factorial” refers to how you determine which treatments will be included in the study, and “completely randomized” refers to how treatments are assigned to subjects.</p>
<hr>
<section id="bf1" class="level2 tabset tabset-fade tabset-pills">
<h2 class="tabset tabset-fade tabset-pills anchored" data-anchor-id="bf1">BF[1]</h2>
<p>A study with just one factor</p>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview">Overview</h3>
<p>In a basic one-way factorial design (BF[1]), only one factor is purposefully varied. Each level of the factor is considered a treatment. Each experimental unit is randomly assigned to exactly one treatment.</p>
<section id="factor-structure" class="level4">
<h4 class="anchored" data-anchor-id="factor-structure">Factor structure</h4>
<p>The factor structure for the model resulting from a completely randomized, one factor with design is:</p>
<p><img src="images/BF1_factor_structure_with_equation.PNG" class="img-fluid"></p>
<p>The above diagram illustrates a factor with 4 levels, 6 replications at each level.</p>
</section>
<section id="hypotheses-and-model" class="level4">
<h4 class="anchored" data-anchor-id="hypotheses-and-model">Hypotheses and model</h4>
<p>A more detailed description of the model for an ANOVA with just one factor:</p>
<p><span class="math display">\[
y_{ij} = \mu + \alpha_i + \epsilon_{ij}
\]</span></p>
<p><span class="math inline">\(y_{ij}\)</span>: the <span class="math inline">\(j^{th}\)</span> observation from treatment <span class="math inline">\(i\)</span></p>
<p><span class="math inline">\(\mu\)</span>: the grand mean of the dataset. Also referred to as an overall mean or benchmark.</p>
<p><span class="math inline">\(\alpha_i\)</span>: effect of treatment <span class="math inline">\(i\)</span></p>
<p><span class="math inline">\(\epsilon_{ik}\)</span>: the error term, or residual term of the model. There are <em>j</em> replicates for each treatment. It represents the distance from an observation to its treatment mean (or predicted value).</p>
<p>The null and alternative hypotheses can be expressed as:</p>
<p><span class="math display">\[
H_o: \alpha_1 = \alpha_2 = ... = 0
\]</span> <span class="math display">\[
H_a: \alpha_i \neq 0 \quad \text{for at least one }\ \alpha_i
\]</span></p>
</section>
<section id="assumptions" class="level4">
<h4 class="anchored" data-anchor-id="assumptions">Assumptions</h4>
<p>A one-way ANOVA model may be used to analyze data from a BF[1] design if the following requirements are satisfied:</p>
<ol type="1">
<li>Each experimental unit is randomly assigned to only 1 treatment (or factor level)</li>
<li>The error term of the model (<span class="math inline">\(\epsilon_{ik}\)</span>) is normally distributed. This assumption is met when the residuals are normally distributed (as seen in a qq-plot).</li>
<li>The population variance of each group is equal. This is often called the homogeneity of variance, or constant variance assumption. This is considered met when each group of residuals in the residual vs.&nbsp;fitted-values plot shows a similar vertical spread.</li>
</ol>
<hr>
</section>
</section>
<section id="design" class="level3">
<h3 class="anchored" data-anchor-id="design">Design</h3>
<p>In a one factor design, one factor is purposefully varied and all other factors are controlled in order to isolate the effect of just the factor under study. Each level of the factor is considered a treatment.</p>
<p>In a completely randomized design, each experimental unit is randomly assigned to exactly 1 treatment. It is common to keep the number of units assigned to each treatment the same to ensure balance. This can be done by listing all the subjects, then listing the treatments, as seen below:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">6</td>
</tr>
</tbody>
</table>
<p>Then you randomly shuffle the treatment column. (You should also be paying attention to the order in which subjects and treatments are being experimented on as this could be a potential source of bias. In a BF[1], you randomize the order also.) The result might look something like this.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
<p>You may notice in the above example that, even with randomization, treatment C occurs in the last 2 observations. If we were truly concerned about the order we could be more strategic and implement a <em>blocked design</em> to prevent “unlucky” ordering and pairing.</p>
<p>Consider the following example. An experiment was done to asses different modes of virtual training in how to launch a lifeboat. Sixteen students in the maritime safety training institute were a part of the study, and each of the students were assigned one of four possible virtual training experiences. The four experiences included: Lecture/Materials (Control) (1), Monitor/Keyboard (2), Head Monitor Display/Joypad (3), and Head Monitor Display/Wearables (4). The response variable was the student’s performance on a procedural knowledge assessment (performance is defined as their level of improvement from pre to post test).</p>
<p>To obtain a balanced design, we will want each treatment to be assigned to four students. We could get 16 pieces of paper and write “Treatment 1” on 4 pieces, “Treatment 2” on another 4 pieces, and so on until each treatment has 4 pieces of paper. We could then put them in a hat, mix them up and then randomly draw out a piece of paper to assign it to a subject. Intuitively this makes sense, but writing and cutting paper is slow and inefficient. We could implement a similar process in R to assign treatments.</p>
<p>First, we list all the possible treatments, and repeat that listing until it is the same size as our count of subjects. (Note, if your number of subjects is not an exact multiple of the number of treatments, you may need to decide which treatments deserve fewer observations)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>treatment_list <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">4</span>) <span class="co">#This repeats the sequence of 1 to 4, four times</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>treatment_list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4</code></pre>
</div>
</div>
<p>Here it is reformatted in a easy to read table.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 7</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 8</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 9</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 10</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 11</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 12</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 13</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 14</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 15</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 16</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
<p>Then we randomly shuffle treatments with subjects to get the following assignments. The R code could look like this</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">17</span>) <span class="co">#only use this if you want the exact same random selection as this example</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(treatment_list, <span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2 4 1 4 3 1 3 2 2 2 4 3 4 1 3 1</code></pre>
</div>
</div>
<p>We can see here that subject 1 should get treatment 2. Subject 2 gets treatment 4, Subject 3 gets treatment 1 and so on.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 7</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 8</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 9</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 10</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 11</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 12</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 13</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 14</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 15</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 16</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="decomposition-and-factor-structure" class="level3">
<h3 class="anchored" data-anchor-id="decomposition-and-factor-structure">Decomposition and Factor Structure</h3>
<p>This section serves as a bridge between the design and the analysis of an experiment. It is equivalent to doing the analysis by hand. The primary goal is to see how the design decisions impact the analysis; including a deeper understanding of what the numbers in an ANOVA table mean and how they are calculated.</p>
<p>A factor structure for an experimental design can help provide an effective way to organize and plan for the type of data needed for an experiment. For a basic one-way factorial design, three factors are involved for the experiment: the benchmark (or grand mean), the treatment, and the residual error. For example, an experiment was done to help train people in the procedure to launch a lifeboat. This was a Basic One-way Factorial Design, one where the treatments included: Lecture/Materials (Control) (1), Monitor/Keyboard (2), Head Monitor Display/Joypad (3), and Head Monitor Display/Wearables (4). The students were then given a pre-test before training and a post-test after training and the difference between the two scores was the measurement used from each student in the analysis. Therefore, we have four levels for the treatment with six replicates for each treatment (the actual study used 16 observations per treatment). The diagram below gives the factor structure of the design, and the accompanying mathematical model.</p>
<p><img src="images/BF1_factor_structure_with_equation.PNG" class="img-fluid"></p>
<p>A basic one-way factorial design has three factors: the benchmark, treatment, and residual. The effects of these factors can be summed together to find each observed value.</p>
<ul>
<li>The <strong>observed values</strong> on the left show that there are 24 distinct observations of performance score, represented by the 24 cells - one for each of the observed values.</li>
<li>The <strong>benchmark</strong> represents the grand mean (or overall mean). The single large cell indicates that there is only one grand mean and it is part of every observation.<br>
</li>
<li>The <strong>treatment factor</strong> involves the four levels of the treatment represented by the four vertically long cells. Each treatment may have a distinct mean (or effect).</li>
<li>The <strong>residual error</strong> represents the difference between the observed value and the predicted value. The predicted value, also called the fitted value, is the sum of the grand mean and treatment effect. Each of the cells represent a distinct value for the residual error.</li>
</ul>
<section id="inside-vs.-outside-factors" class="level4">
<h4 class="anchored" data-anchor-id="inside-vs.-outside-factors">Inside vs.&nbsp;Outside Factors</h4>
<p>Having a factor structure can help us determine the <strong>degrees of freedom</strong> and the <strong>effects</strong> of each factor. Before determining the degrees of freedom and the effects of each factor, understanding <strong>outside and inside factors</strong> is helpful.</p>
<p>A factor is inside of another factor if all the levels of one factor (<strong>the inside factor</strong>) completely fits within a second factor (<strong>the outside factor</strong>).</p>
<p>You may find this analogy helpful. Pretend that an outside factor is a box, and the inside factor levels are blocks that fit perfectly within the box.</p>
<center>
<p><img src="./images/wooden_blocks_in_box.jpg" width="200px;"> <!-- ![blocks in box](images/wooden_blocks_in_box.jpg) --> <!-- picture from: https://www.amazon.com/MOD-Complete-Extra-Large-Size/dp/B079J8PB73 --></p>
</center>
<p>In our basic one-way factorial design there are three factors: the benchmark, treatment, and residuals. In the picture below, benchmark is represented in red, treatment is drawn in blue, and the residual factor levels are depicted in black.</p>
<p><img src="images/inside_outside_1.JPG" class="img-fluid"></p>
<p>In order to understand the relationship between the benchmark and treatment factor, imagine picking up the levels of factor and placing them in the other factor one at a time. We will start with taking the levels of treatment and placing them inside of the benchmark.</p>
<p><img src="images/inside_outside_2.JPG" class="img-fluid"></p>
<p>In this picture you can see that one entire level of treatment can fit inside of a single level of benchmark. Even though they may share a boundary line, the level does not cross over and start sharing boundaries with any other level. You can repeat this for the other 3 levels of treatment with the same result. Therefore, we say that treatment is inside of benchmark, which is the same as saying that benchmark is outside of treatment.</p>
<p>Consider now the relationship between treatment and residual. If we take a level of treatment and overlay it on the residual factor, we can see it does not fit neatly inside one of the levels of residual error. In fact, one level of treatment crosses the boundaries of many of the levels of residual error. Therefore, we cannot say that treatment is inside of residual error.</p>
<p><img src="images/inside_outside_3.JPG" class="img-fluid"></p>
<p>Since treatment is not inside of residual error, does this necessarily mean that treatment is outside of residual error? We can determine this by taking one level of residual at a time and overlaying it on the treatment factor structure, as is pictured below. It can be seen that one level of residual error does NOT cross any of the treatment level boundaries. Therefore, we can safely say that treatment is indeed outside of residual error; or equivalently that treatment is outside of residual error.</p>
<p><img src="images/inside_outside_4.JPG" class="img-fluid"></p>
<p>To clarify a common misunderstanding, consider an experiment where we are looking at the inside vs.&nbsp;outside relationship of two factors: A, and B.</p>
<ul>
<li>When factor A is inside of factor B, we can also say factor B is outside of factor A.</li>
<li>But, when factor A is <em>not</em> inside of factor B, this does <em>not necessarily mean that factor A is outside of factor B</em>. Later you will come across designs where the two factors are neither outside nor inside of each other: they are crossed.</li>
</ul>
<p>In summary, inside and outside factors for every basic one-way factorial design:</p>
<ul>
<li>The <strong>benchmark factor</strong> is the outside factor for all the other factors (treatment and residual error)</li>
<li>The <strong>treatment factor</strong> is an inside factor to the benchmark factor but an outside factor to the residual error.</li>
<li>The <strong>residual error</strong> is an inside factor for all other factors (the benchmark and treatment factors).</li>
</ul>
</section>
<section id="degrees-of-freedom" class="level4">
<h4 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h4>
<p>We can use our understanding of inside and outside factors to determine the degrees of freedom (df) for the <strong>benchmark</strong>, <strong>treatment</strong>, and <strong>residual errors</strong> factors.</p>
<p>The general formula for degrees of freedom for any factor in a design is:</p>
<center>
<blockquote class="blockquote">
<p><strong>df = Total levels of a factor minus the sum of the df of all outside factors</strong></p>
</blockquote>
</center>
<p>An alternative method of finding degrees of freedom is to count the number of unique pieces of information in a factor.</p>
<p>Going back to the lifeboat training example (see example above), we have 24 observations total and four levels of the treatment.</p>
<p><img src="images/BF1_factor_structure_with_equation.PNG" class="img-fluid"></p>
<p>For <strong>benchmark</strong>, there is only one level of the factor (shown by the one cell) and there are no outside factors for benchmark. Therefore, the degrees of freedom for benchmark is one. Another way to think of this is that the degrees of freedom represents the number of unique pieces of information contributing to the estimation of the effects for that factor. In this case, as soon as I know the benchmark value (or better stated, as soon as I estimate the benchmark value) for just one of the observations, I know it for all the observations. Therefore, there is just one degree of freedom.</p>
<p>For <strong>treatment</strong>, there are four levels of the factor (shown by the four vertically long cells for treatment). Benchmark is the only factor outside of treatment. Take the number of levels for treatment (4) and subtract the degrees of freedom for benchmark (1), which yields 4-1 = <strong>3 degrees of freedom</strong> for treatment.</p>
<p>We could just as easily have used the other approach to finding the degrees of freedom: counting the unique pieces of information the treatment effects really contains. Since all observations from the same treatment will have the same treatment effect applied, we really only need to know 4 pieces of information: the effect of each treatment. But the answer is actually less than that. Because we know that the effects must all sum to zero, only 3 of the effects are free to vary and the 4th one is constrained to be whatever value will satisfy this mathematical condition. Thus, the degrees of freedom is 3. As soon as we know 3 of the treatment effects, we can fill in the treatment effects for all the observations.</p>
<p>For <strong>residual errors</strong>, there are 24 levels of the factor (as shown by the 24 cells for residual error on the far right of the factor structure diagram). Both benchmark and treatment are outside factors for the residual errors factor. Take the number of levels for the residual error (24) and subtract the sum of the degrees of freedom for benchmark and treatment (3+1=4). The residual error has 24 - (3+1) = <strong>20 degrees of freedom</strong>.</p>
<p>The approach of counting unique pieces of information can be applied here as well. In this case, we use the fact that the treatment effects must sum to zero within each treatment. So within each treatment, 5 of the observations are free to vary, but the 6th will be determined by the fact that their sum must be zero. Five observations multiplied by 4 treatments is 20 observations, or in other words, 20 degrees of freedom.</p>
</section>
<section id="factor-effects" class="level4">
<h4 class="anchored" data-anchor-id="factor-effects">Factor Effects</h4>
<p>We can use our understanding of inside vs.&nbsp;outside factors to estimate the effect size for the benchmark, treatment, and residual errors factors. In other words, we can estimate the terms in the one-way ANOVA model.</p>
<p>The general formula for effect size for any factor of a design is:</p>
<center>
<blockquote class="blockquote">
<p><strong>Effect size = factor level mean minus the sum of the effects of all outside factors</strong></p>
</blockquote>
</center>
<p>To demonstrate this, the lifeboat training study will be used; where each column of data comes from a different training method (a.k.a. treatment).</p>
<p><img src="images/BF1_mean_blank.png" class="img-fluid"></p>
<section id="calculate-means" class="level5">
<h5 class="anchored" data-anchor-id="calculate-means">Calculate means</h5>
<p>To estimate all the factor effects we must first calculate the mean for the benchmark factor and the means for each treatment level.</p>
<p>For benchmark, get the mean of all 24 observations. The mean for all the observations is 6.5846. There is only one level for benchmark since, all observations come from the same benchmark. Therefore, this number is placed into each of the cells for the benchmark factor.</p>
<p><img src="images/BF1_mean_benchmark.png" class="img-fluid"></p>
<p>For the treatment factor, calculate the mean of each of the four levels. To calculate the mean for Control:</p>
<p><span class="math display">\[
\frac{4.5614 + 6.6593 + 5.6427 + 6.4394 + 4.8635 + 0.3268}{6} = 4.7489
\]</span></p>
<p>You can similarly find the mean for monitor keyboard is 7.8492, the mean for head monitor display/joypad is 6.5789, and the mean for head monitor display/wearables is 7.1616. These numbers will be put in the columns associated with each level of the treatment (see below).</p>
<p><img src="images/BF1_means_decomp.png" class="img-fluid"></p>
</section>
<section id="calculate-effects" class="level5">
<h5 class="anchored" data-anchor-id="calculate-effects">Calculate effects</h5>
<p>From here we can calculate the effects for benchmark, treatment and residual errors. We will use the general formula for calculating effect size as stated above.</p>
<p>For the benchmark, there is only one level and there are no outside factors. Therefore, the effect due to benchmark is 6.5846 (equivalent to its mean) and this affect is applied to all 24 observations.</p>
<p>For the treatment factor there are four means, one for each level. To calculate this, take the factor level mean and subtract it from the effect due to benchmark to get the effect for each treatment level. For Control, this looks like:</p>
<p><span class="math display">\[
4.789 - 6.5846 = -1.8358
\]</span></p>
<p>Being in the control group has the effect of <em>reducing</em> the student’s performance by 1.8358 on average compared to the overall, or grand, mean. In a similar way you can find the effect for Monitor/Keyboard 7.8492 - 6.5846 = 1.2645. This means the student performance scores increased by 1.2645 on average in this condition compared to the overall mean. For Head Monitor Display/Joypad, the effect is -0.0058 (6.5789 - 6.5846). For Head Monitor Display/Wearables, the effect is 0.5770 (7.1616 - 6.5846) (see below).</p>
<p><img src="images/BF1_trt_effect_boat_decomp.png" class="img-fluid"></p>
<p>To calculate the residual error effects we must remember that there are 24 levels of residuals. Therefore, the factor level mean for a residual is simply the observed value itself. This means the residual effect can be calculated by taking an observed value and subtracting the effects for benchmark and the effect for the treatment that particular observation received. For instance, for the observation located in the top left of our dataset the observed value is 4.5614. Subtract the sum of the effects of outside factors (benchmark and treatment). This observation was from the control group so we get:</p>
<p><span class="math display">\[
4.5614 - (6.5846 + -1.8358) = -0.1875
\]</span></p>
<p>The value for the top left cell in residual errors effects is -0.1875. This means the observed value of 4.5614 was lower than we would have expected it to be. In other words, the performance score of 4.5614 was -0.1875 less than the average for all observations in the control group. In context of the this study, this individual’s performance was lower than his/her peers who received the same type of training.</p>
<p>We can repeat the calculation for the first residual in the second column. Take the observed value (5.4532) and subtract the sum of the effect due to benchmark and its respective treatment (in this case monitor/keyboard). The residual is</p>
<p><span class="math display">\[
5.4523 - (6.5846 + 1.2645) = -2.3960
\]</span></p>
<p>Repeat this process for all the remaining 22 residual values. The result is shown in the table below on the right.</p>
<p><img src="images/BF1_effect_boat_decomp.png" class="img-fluid"></p>
</section>
</section>
<section id="completing-the-anova-table" class="level4">
<h4 class="anchored" data-anchor-id="completing-the-anova-table">Completing the ANOVA table</h4>
<p>Now that we have calculated degrees of freedom and effects for each factor in a basic one-way factorial design, we can calculate the remaining pieces of the ANOVA table: <strong>Sum of Squares (SS), Mean Squares (MS), F-statistic and p-value</strong>. An ANOVA table essentially steps through the variance calculation that is needed to calculate the F statistics of an ANOVA test. In other words, a completed ANOVA table enables us to conduct a hypothesis test of the significance of the treatment.</p>
<p>In an ANOVA table, each factor and their associated degrees of freedom are listed on the left. Note: the total degrees of freedom are the total number of observations.</p>
<div class="cell">
<div class="cell-output-display">
<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:left;"> SS </th>
   <th style="text-align:left;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Benchmark </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Treatment </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>To get the <strong>sum of squares (SS)</strong> for a factor, for each observation the effect for that factor needs to be squared. Then all the squared values are summed up to get the sum of squares.</p>
<p>For <strong>benchmark</strong>, the effect of 6.5845 is listed 24 times, once for each observation. The value of 6.5845 will be squared. This squaring will be done 24 times and the squared values will then be added together to get the sum of squares due to benchmark.</p>
<p><span class="math display">\[
SS_\text{Benchmark} = (6.5845)^2 + (6.5845)^2 + ... + (6.5845)^2 = 24*(6.5845)^2 = 1040.57
\]</span></p>
<p><br></p>
<p>The <strong>treatment factor</strong> has four different effects, one for each level of the factor. For each effect, the value is squared and then multiplied by the number of observations within the level of the factor. Then, the results are added across all levels to get the sum of squares due to treatment. For instance, for the control group, the effect is -1.8358. The value is then squared, and then multiplied by six due to the six observations within the control group. This is done for the other three levels as well and then the resulting values from the four levels are added.</p>
<p><span class="math display">\[
SS_\text{Treatment} = 6*(-1.8358)^2 + 6*(1.2645)^2 + 6*(-0.0058)^2 + 6*(0.5770)^2 = 31.81
\]</span> <br></p>
<p>The effect for the <strong>residual error factor</strong> has 24 unique values. Each of those residuals are squared and then the squared values are summed together.</p>
<p><span class="math display">\[
SS_\text{Residuals} = (-0.1875)^2 + (1.9105)^2 + (0.8939)^2 + (1.6906)^2 + ... + (-2.0157)^2 = 100.49
\]</span> <br></p>
<p>To get the <strong>total sum of squares</strong>, we can either square all the observations and then add the squared values,</p>
<p><span class="math display">\[
SS_\text{Total} = (4.5614)^2 + (6.6593)^2 + (5.6427)^2 + (6.4394)^2 + ... + (5.1459)^2 = 1172.87
\]</span></p>
<p><strong>-OR-</strong> we can get the same result if we add together the sum of squares for the benchmark, treatment, and residual error factors.</p>
<p><span class="math display">\[
SS_\text{Total} = 1040.57 + 31.81 + 100.49 = 1172.87
\]</span></p>
<p><br> <br></p>
<div class="cell">
<div class="cell-output-display">
<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:left;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Benchmark </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Treatment </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 31.81 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 100.49 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 1172.87 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>We can now calculate the mean squared error column, or <strong>mean square (MS)</strong>. This mean is calculated by dividing sum of squares by the number of unique pieces of information that make up the factor. In this way we convert a total into an average; or in other words we change a sum into a mean. The mean squared error is the same as a variance. (The Root Mean Squared Error is equivalent to a standard deviation).</p>
<p>The purpose of the ANOVA table is to partition or break apart the variability in the dataset to its component pieces. We can then see more clearly which factor is the a bigger source of variability.</p>
<p>The mean square calculations are:</p>
<p><span class="math display">\[
MS_\text{Benchmark} = \frac{SS_\text{Benchmark}}{df_\text{Benchmark}} = \frac{1040.57}{1} = 1040.57
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Treatment} = \frac{SS_\text{Treatment}}{df_\text{Treatment}} = \frac{31.81}{3} = 10.60
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Residual Error} = \frac{SS_\text{Residual Error}}{df_\text{Residual Error}} = \frac{100.49}{20} = 5.02
\]</span></p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:right;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Benchmark </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Treatment </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 31.81 </td>
   <td style="text-align:right;"> 10.60 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 100.49 </td>
   <td style="text-align:right;"> 5.02 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 1172.87 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>When getting an <strong>F test statistic</strong>, testing for the treatment factor is the primary factor of interest so only the F test statistic for treatment is calculated for the analysis. To get the F test statistic for treatment, take the mean square (MS) due to treatment and divide by the mean square (MS) due to the residual error. Since the mean square error is equivalent to a variance, you can think of this as calculating the variance in treatment effect sizes in the numerator and the variance of the distances for an observed value to its respective treatment mean in the denominator. Simply put, it is the between groups variance divided by the within group variance.</p>
<p><span class="math display">\[
F_\text{Treatment} = \frac{MS_\text{Treatment}}{MS_\text{Residual Error}} = \frac{10.6}{5.02} = 2.11
\]</span></p>
<p><br></p>
<p>To complete the ANOVA, table, the <strong>p-value for treatment</strong> is calculated based on the F statistic for treatment and the degrees of freedom for both Treatment and Residual Error. In practice, you would not compute this by hand, but in order to complete the decomposition of variance in a manual way, we will calculate the p-value in R using the <code>pf()</code> function: <code>1 - pf(test statistic, df of Treatment, df of Residual error)</code>.</p>
<p>In this example, we get</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(<span class="fl">2.11</span>, <span class="dv">3</span>, <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1310051</code></pre>
</div>
</div>
<p>This p-value, 0.1310, is greater than a typical level of significance (0.05), so we would fail to reject the null hypothesis that all the effects due to treatment are equal to zero. Meaning, we have insufficient evidence to say that any of the training methods had an impact on procedural knowledge test scores regarding launching a life boat.</p>
<div class="cell">
<div class="cell-output-display">
<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:right;"> MS </th>
   <th style="text-align:right;"> Fvalue </th>
   <th style="text-align:right;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Benchmark </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:right;"> 1040.57 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Treatment </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 31.81 </td>
   <td style="text-align:right;"> 10.60 </td>
   <td style="text-align:right;"> 2.11 </td>
   <td style="text-align:right;"> 0.131 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 100.49 </td>
   <td style="text-align:right;"> 5.02 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 1172.87 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<hr>
</section>
</section>
<section id="r-instructions" class="level3">
<h3 class="anchored" data-anchor-id="r-instructions">R Instructions</h3>
<p><strong>The following stuff would belong in the R code pages instead of here</strong></p>
<section id="numerical-summaries" class="level4">
<h4 class="anchored" data-anchor-id="numerical-summaries">Numerical Summaries</h4>
<p>In the following explanations</p>
<ul>
<li>Y must be a “numeric” vector of the quantitative response variable.</li>
<li>X is a qualitative variable (should have class(X) equal to factor or character. If it does not, use as.factor(X) inside the aov(Y ~ as.factor(X),…) command.</li>
<li>YourDataSet is the name of your data set.</li>
</ul>
<p>You can take a tidyverse approach or a mosaic package approach to calculating numerical summaries.</p>
<p>mosaic package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pander)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Y<span class="sc">~</span>X, <span class="at">data=</span>YourDataSet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>tidyverse approach:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>YourDataSet <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Group_by</span>(X) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Summarise</span>(<span class="at">MeanY =</span> <span class="fu">mean</span>(Y), <span class="at">sdY =</span> <span class="fu">sd</span>(Y), <span class="at">sampleSize =</span> <span class="fu">n</span>()) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="graphical-summaries" class="level4">
<h4 class="anchored" data-anchor-id="graphical-summaries">Graphical Summaries</h4>
<p>To obtain a boxplot:</p>
<p><code>boxplot(Y~X, data = YourDataSet)</code></p>
<p><strong>Example Code:</strong></p>
<!-- <a href="javascript:showhide('boxplot')"> -->
<!-- <div class="hoverchunk"> -->
<!-- <span class="tooltipr"> -->
<!-- boxplot() -->
<!-- To obtain a dot plot with a line connecting the treatment means: -->
<!-- `xyplot(Y~X, data=YourDataSet, type=c("p","a"), main=”Whatever title you want”, col=”whatever color you want”, xlab=”whatever x-axis label you want”, ylab=”whatever y-axis label you want”)` -->
<hr>
</section>
</section>
<section id="resources" class="level3">
<h3 class="anchored" data-anchor-id="resources">Resources</h3>
<section id="examples" class="level4">
<h4 class="anchored" data-anchor-id="examples">Examples</h4>
<p><a href="examples/VirtualTrain.html">Lifeboat launch training</a></p>
<p><a href="examples/mosquito.html">Mosquito</a></p>
</section>
<section id="links-to-outside-resources" class="level4">
<h4 class="anchored" data-anchor-id="links-to-outside-resources">Links to outside resources</h4>
<p>Populate this section yourself with links to good examples, definitions, other sections within this textbook, or anything else you think will be interesting/helpful.</p>
<hr>
</section>
</section>
</section>
<section id="bf2" class="level2 tabset tabset-fade tabset-pills">
<h2 class="tabset tabset-fade tabset-pills anchored" data-anchor-id="bf2">BF[2]</h2>
<p>A study with exactly two factors used to predict a continuous response variable.</p>
<section id="overview-1" class="level3">
<h3 class="anchored" data-anchor-id="overview-1">Overview</h3>
<p>Lorem Ipsum Overview</p>
<section id="hypotheses-and-model-1" class="level4">
<h4 class="anchored" data-anchor-id="hypotheses-and-model-1">Hypotheses and model</h4>
<p>Here we would list the model in equation form along with the hypotheses we would want to test</p>
</section>
<section id="assumptions-1" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-1">Assumptions</h4>
<p>A quick recount of the assumptions associated with the model. If this gets too repetitive maybe we could take it out and put it under broad topics</p>
</section>
<section id="factor-structure-image" class="level4">
<h4 class="anchored" data-anchor-id="factor-structure-image">Factor structure image</h4>
<p>This image would actually probably go at the top somewhere, maybe even by or above the title, as a sort of visual anchor/synopsis as to what this design is all about in terms of its structural factors.</p>
<hr>
</section>
</section>
<section id="design-1" class="level3">
<h3 class="anchored" data-anchor-id="design-1">Design</h3>
<p>This will explain how random assignment is conducted. It may generally be a short section, especially since I already explained about completely random assignment above. However, it could get more in-depth. For example, in blocking you can talk about the different methods for creating blocks, or for Latin Squares there’s a lot to describe. For partial fractional factorials it could get interesting, etc.</p>
<hr>
</section>
<section id="decomposition" class="level3">
<h3 class="anchored" data-anchor-id="decomposition">Decomposition</h3>
<p>It is what it sounds like: discussion of effect calculation, degree of freedom calculation, and factor structure diagrams. Where do things like <strong>notation</strong> get defined, and concepts like <strong>inside vs.&nbsp;outside factors?</strong> Should those go in the broad topics menu?</p>
<hr>
</section>
<section id="r-instruction" class="level3">
<h3 class="anchored" data-anchor-id="r-instruction">R Instruction</h3>
<p>It is what it sounds like: discussion of effect calculation, degree of freedom calculation, and factor structure diagrams. Where do things like <strong>notation</strong> get defined, and concepts like <strong>inside vs.&nbsp;outside factors?</strong> Should those go in the broad topics menu?</p>
</section>
<section id="resources-1" class="level3">
<h3 class="anchored" data-anchor-id="resources-1">Resources</h3>
<section id="examples-1" class="level4">
<h4 class="anchored" data-anchor-id="examples-1">Examples</h4>
<p>Here we could link to a full walk through example of the anlaysis (similar to the Math325 notebook)</p>
</section>
<section id="links-to-outside-resources-1" class="level4">
<h4 class="anchored" data-anchor-id="links-to-outside-resources-1">Links to outside resources</h4>
<p>This section the student would populate with links to good examples, definitions, other sections within this textbook, or anything else</p>
<hr>
</section>
</section>
</section>
<section id="bf3" class="level2 tabset tabset-fade tabset-pills">
<h2 class="tabset tabset-fade tabset-pills anchored" data-anchor-id="bf3">BF[3]</h2>
<p>A study with exactly three factors used to predict a continuous response variable.</p>
<section id="overview-2" class="level3">
<h3 class="anchored" data-anchor-id="overview-2">Overview</h3>
<p>Lorem Ipsum Overview</p>
<section id="hypotheses-and-model-2" class="level4">
<h4 class="anchored" data-anchor-id="hypotheses-and-model-2">Hypotheses and model</h4>
<p>Here we would list the model in equation form along with the hypotheses we would want to test</p>
</section>
<section id="assumptions-2" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-2">Assumptions</h4>
<p>A quick recount of the assumptions associated with the model. If this gets too repetitive maybe we could take it out and put it under broad topics</p>
</section>
<section id="factor-structure-image-1" class="level4">
<h4 class="anchored" data-anchor-id="factor-structure-image-1">Factor structure image</h4>
<p>This image would actually probably go at the top somewhere, maybe even by or above the title, as a sort of visual anchor/synopsis as to what this design is all about in terms of its structural factors.</p>
<hr>
</section>
</section>
<section id="design-2" class="level3">
<h3 class="anchored" data-anchor-id="design-2">Design</h3>
<p>This will explain how random assignment is conducted. It may generally be a short section, especially since I already explained about completely random assignment above. However, it could get more in-depth. For example, in blocking you can talk about the different methods for creating blocks, or for Latin Squares there’s a lot to describe. For partial fractional factorials it could get interesting, etc.</p>
<hr>
</section>
<section id="decomposition-1" class="level3">
<h3 class="anchored" data-anchor-id="decomposition-1">Decomposition</h3>
<p>It is what it sounds like: discussion of effect calculation, degree of freedom calculation, and factor structure diagrams. Where do things like <strong>notation</strong> get defined, and concepts like <strong>inside vs.&nbsp;outside factors?</strong> Should those go in the broad topics menu?</p>
<hr>
</section>
<section id="r-instruction-1" class="level3">
<h3 class="anchored" data-anchor-id="r-instruction-1">R Instruction</h3>
<p>It is what it sounds like: discussion of effect calculation, degree of freedom calculation, and factor structure diagrams. Where do things like <strong>notation</strong> get defined, and concepts like <strong>inside vs.&nbsp;outside factors?</strong> Should those go in the broad topics menu?</p>
</section>
<section id="resources-2" class="level3">
<h3 class="anchored" data-anchor-id="resources-2">Resources</h3>
<section id="examples-2" class="level4">
<h4 class="anchored" data-anchor-id="examples-2">Examples</h4>
<p>Here we could link to a full walk through example of the anlaysis (similar to the Math325 notebook)</p>
</section>
<section id="links-to-outside-resources-2" class="level4">
<h4 class="anchored" data-anchor-id="links-to-outside-resources-2">Links to outside resources</h4>
<p>This section the student would populate with links to good examples, definitions, other sections within this textbook, or anything else</p>
<hr>
</section>
</section>
</section>
<section id="fractional-factorial-designs" class="level2 tabset tabset-fade tabset-pills">
<h2 class="tabset tabset-fade tabset-pills anchored" data-anchor-id="fractional-factorial-designs">Fractional Factorial Designs</h2>
<p>This would probably not follow a similar structure as other sections</p>
<section id="overview-3" class="level3">
<h3 class="anchored" data-anchor-id="overview-3">Overview??</h3>
<p>Lorem Ipsum Overview</p>
<hr>
</section>
<section id="how-many-treatments-design-rank" class="level3">
<h3 class="anchored" data-anchor-id="how-many-treatments-design-rank">How many treatments, design rank</h3>
<p>Here we would list the model in equation form along with the hypotheses we would want to test</p>
<hr>
</section>
<section id="confounding-and-a-generating-function" class="level3">
<h3 class="anchored" data-anchor-id="confounding-and-a-generating-function">Confounding and a Generating Function</h3>
<p>A quick recount of the assumptions associated with the model. If this gets too repetitive maybe we could take it out and put it under broad topics</p>
<hr>
</section>
<section id="anything-else" class="level3">
<h3 class="anchored" data-anchor-id="anything-else">Anything else??</h3>
<hr>
</section>
<section id="additional-resources-and-links" class="level3">
<h3 class="anchored" data-anchor-id="additional-resources-and-links">Additional resources and links</h3>
<section id="examples-3" class="level4">
<h4 class="anchored" data-anchor-id="examples-3">Examples</h4>
<p>Here we could link to a full walk through example of the anlaysis (similar to the Math325 notebook)</p>
</section>
<section id="links-to-outside-resources-3" class="level4">
<h4 class="anchored" data-anchor-id="links-to-outside-resources-3">Links to outside resources</h4>
<p>This section the student would populate with links to good examples, definitions, other sections within this textbook, or anything else</p>
<hr>
<p>The decompositions presented in this book are all for balanced designs. Unbalanced designs (where not all treatments have an equal number of observations) use more complicated formulas, but a similar approach/process of decomposition is used.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>