<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Math326 Notebook - BF[2]</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Math326 Notebook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-basics-of-design" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Basics of Design</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-basics-of-design">    
        <li>
    <a class="dropdown-item" href="./key_principles.html" rel="" target="">
 <span class="dropdown-text">Key Principles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./research_objectives.html" rel="" target="">
 <span class="dropdown-text">Research Objectives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./response_variable.html" rel="" target="">
 <span class="dropdown-text">Response Variable</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./experimental_units.html" rel="" target="">
 <span class="dropdown-text">Experimental Units</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sources_of_variances.html" rel="" target="">
 <span class="dropdown-text">Sources of Variation - Factors and Conditions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./randomization.html" rel="" target="">
 <span class="dropdown-text">Randomization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-specific-designs" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Specific Designs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-specific-designs">    
        <li>
    <a class="dropdown-item" href="./BasicFactorial_intro.html" rel="" target="">
 <span class="dropdown-text">Basic Factorial Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./BasicFactorial_quarto_boat.html" rel="" target="">
 <span class="dropdown-text">BF[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bf2.html" rel="" target="">
 <span class="dropdown-text">BF[2]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bf3.html" rel="" target="">
 <span class="dropdown-text">BF[3+]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./block_intro.html" rel="" target="">
 <span class="dropdown-text">Blocking Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cb1.html" rel="" target="">
 <span class="dropdown-text">CB[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ancova.html" rel="" target="">
 <span class="dropdown-text">ANCOVA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./latin_square.html" rel="" target="">
 <span class="dropdown-text">Latin Square</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NestedFactor.html" rel="" target="">
 <span class="dropdown-text">Nested Factor (aka Split Plot/Repeated Measure) Designs</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-broad-topics" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Broad Topics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-broad-topics">    
        <li>
    <a class="dropdown-item" href="./factor_structure.html" rel="" target="">
 <span class="dropdown-text">Factor Structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./effects_model.html" rel="" target="">
 <span class="dropdown-text">Effects Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Anova_F-test.html" rel="" target="">
 <span class="dropdown-text">ANOVA and the F-test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html" rel="" target="">
 <span class="dropdown-text">Assumptions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./contrast.html" rel="" target="">
 <span class="dropdown-text">Contrasts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./multiple_comparisons.html" rel="" target="">
 <span class="dropdown-text">Multiple Comparisons</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unbalanced.html" rel="" target="">
 <span class="dropdown-text">Unbalanced Datasets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Kruskal.html" rel="" target="">
 <span class="dropdown-text">ZPower??</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./LogisticRegression.html" rel="" target="">
 <span class="dropdown-text">ZRandom Factors??</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Nested_Samples.html" rel="" target="">
 <span class="dropdown-text">ZNested Subsamples</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-instructions" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">R Instructions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-instructions">    
        <li>
    <a class="dropdown-item" href="./DescribeData.html" rel="" target="">
 <span class="dropdown-text">Descriptive Summaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./diagnostics.html" rel="" target="">
 <span class="dropdown-text">Model diagnostics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-datasets" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Datasets</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-datasets">    
        <li>
    <a class="dropdown-item" href="././Data/AnalysisRubric.html" rel="" target="">
 <span class="dropdown-text">XYZ</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="././Data/StudentHousing.html" rel="" target="">
 <span class="dropdown-text">yadda yadda</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul>
  <li><a href="#factor-structure" id="toc-factor-structure" class="nav-link" data-scroll-target="#factor-structure">Factor Structure</a></li>
  <li><a href="#hypothesis-and-model" id="toc-hypothesis-and-model" class="nav-link" data-scroll-target="#hypothesis-and-model">Hypothesis and Model</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  </ul></li>
  <li><a href="#design" id="toc-design" class="nav-link" data-scroll-target="#design">Design</a></li>
  <li><a href="#interaction-effect" id="toc-interaction-effect" class="nav-link" data-scroll-target="#interaction-effect">Interaction Effect</a>
  <ul>
  <li><a href="#conceptual-understanding" id="toc-conceptual-understanding" class="nav-link" data-scroll-target="#conceptual-understanding">Conceptual Understanding</a></li>
  </ul></li>
  <li><a href="#decomposition" id="toc-decomposition" class="nav-link" data-scroll-target="#decomposition">Decomposition</a>
  <ul>
  <li><a href="#factor-effects" id="toc-factor-effects" class="nav-link" data-scroll-target="#factor-effects">Factor Effects</a>
  <ul class="collapse">
  <li><a href="#factor-level-means" id="toc-factor-level-means" class="nav-link" data-scroll-target="#factor-level-means">Factor Level Means</a></li>
  <li><a href="#factor-level-effects" id="toc-factor-level-effects" class="nav-link" data-scroll-target="#factor-level-effects">Factor Level Effects</a>
  <ul class="collapse">
  <li><a href="#grand-mean-effect" id="toc-grand-mean-effect" class="nav-link" data-scroll-target="#grand-mean-effect">Grand mean effect</a></li>
  <li><a href="#toothbrush-effects" id="toc-toothbrush-effects" class="nav-link" data-scroll-target="#toothbrush-effects">Toothbrush effects</a></li>
  <li><a href="#toothpaste-effects" id="toc-toothpaste-effects" class="nav-link" data-scroll-target="#toothpaste-effects">Toothpaste effects</a></li>
  <li><a href="#interaction-effects" id="toc-interaction-effects" class="nav-link" data-scroll-target="#interaction-effects">Interaction effects</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of Freedom</a></li>
  <li><a href="#completing-the-anova-table" id="toc-completing-the-anova-table" class="nav-link" data-scroll-target="#completing-the-anova-table">Completing the ANOVA Table</a></li>
  </ul></li>
  <li><a href="#analysis-in-r" id="toc-analysis-in-r" class="nav-link" data-scroll-target="#analysis-in-r">Analysis in R</a>
  <ul>
  <li><a href="#describe-the-data" id="toc-describe-the-data" class="nav-link" data-scroll-target="#describe-the-data">Describe the Data</a>
  <ul class="collapse">
  <li><a href="#numerical-summaries" id="toc-numerical-summaries" class="nav-link" data-scroll-target="#numerical-summaries">Numerical Summaries</a></li>
  <li><a href="#graphical-summaries" id="toc-graphical-summaries" class="nav-link" data-scroll-target="#graphical-summaries">Graphical Summaries</a></li>
  </ul></li>
  <li><a href="#create-the-model" id="toc-create-the-model" class="nav-link" data-scroll-target="#create-the-model">Create the Model</a></li>
  <li><a href="#check-assumptions" id="toc-check-assumptions" class="nav-link" data-scroll-target="#check-assumptions">Check Assumptions</a>
  <ul class="collapse">
  <li><a href="#constant-variance-of-residuals" id="toc-constant-variance-of-residuals" class="nav-link" data-scroll-target="#constant-variance-of-residuals">Constant Variance of Residuals</a></li>
  <li><a href="#normally-distributed-residuals" id="toc-normally-distributed-residuals" class="nav-link" data-scroll-target="#normally-distributed-residuals">Normally Distributed Residuals</a></li>
  <li><a href="#independent-residuals" id="toc-independent-residuals" class="nav-link" data-scroll-target="#independent-residuals">Independent Residuals</a></li>
  <li><a href="#assumptions-summary" id="toc-assumptions-summary" class="nav-link" data-scroll-target="#assumptions-summary">Assumptions Summary</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a>
  <ul>
  <li><a href="#notation-for-estimated-effects" id="toc-notation-for-estimated-effects" class="nav-link" data-scroll-target="#notation-for-estimated-effects">Notation for Estimated Effects</a></li>
  <li><a href="#unreplicated-or-single-observation-per-cell" id="toc-unreplicated-or-single-observation-per-cell" class="nav-link" data-scroll-target="#unreplicated-or-single-observation-per-cell">Unreplicated or Single Observation per Cell</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BF[2]</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>
<section id="overview" class="level1 page-columns page-full">
<h1>Overview</h1>
<p>When researchers want to study the effects of two factors on the same response variable a factorial design can be considered. Factorial experiments involve two or more factors that are crossed.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Full <strong>factorial crossing</strong> occurs when each combination of factor levels is present in the study.</p>
</div>
</div>
<p>Compare a factorial design with the one-at-a-time approach. In a one-at-a-time approach, each factor would be investigated in a separate experiment. Each experiment would evaluate the effect of just one factor on the response.</p>
<p>Factorial designs are a way to simultaneously study the effects of multiple factors using just one experiment. Factorial designs have a couple of major advantages over one-factor-at-a-time studies.</p>
<ol type="1">
<li>They are a more efficient use of our time and material: I can get information about both of my factors from just one observation</li>
<li>They allow the random error to be allocated across a greater number of factors, thereby reducing unexplained variance (i.e.&nbsp;mean square error) and increasing the statistical power of the F-test.</li>
<li>They allow the estimation of interaction effects. Or in other words, we can observe how one factor’s effect on the response changes for different levels of the other factor.</li>
</ol>
<p>We will expand on the simple toothpaste example to illustrate BF[2] concepts. The study is summarized here.</p>
<p>Researchers wanted to know which of 4 types of toothbrushes was best at reducing plaque: manual (this is the traditional/usual type of brush), oscillating bristles, sonic, and ultrasonic. The response variable was the percent of teeth surface area covered with plaque. Four teeth (first molar in each quadrant of the mouth) were measured on each person to calculate the total percent area covered. Six subjects were assigned to each type of brush.</p>
<p>Researchers also wanted to study the effect of name brand tooth paste compared to its off brand equivalent. This is the second controlled factor in the experiment. It has two levels (name brand and off brand). Twelve subjects used name brand paste, and a different 12 subjects used the off brand. Toothpaste brand is crossed with toothbrush type to create a BF[2].</p>
<section id="factor-structure" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-structure">Factor Structure</h2>
<p>Based on the description above, the factor structure for this experiment is displayed in <a href="#fig-bf2_brush_factor_structure">Figure&nbsp;1</a>:</p>
<div class="column-page">
<div id="fig-bf2_brush_factor_structure" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/toothbrush_bf2_factor_structure.JPG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Factor Structure Diagram</figcaption>
</figure>
</div>
</div>
<p>Two levels of toothpaste multiplied by 4 levels of toothbrush results in 8 factor level combinations total. This is represented by the 8 partitions in the interaction factor. These 8 factor level combinations are obtained by overlaying the 2 controlled factor partitions. When the toothbrush factor and toothpastepaste partitions are overlayed, they cross each other and create new, meaningful partitions: the interaction factor. Since there were 24 subjects and the study is balanced, we end up with <span class="math inline">\(24\div 8 = 3\)</span> replicates in each factor level combination.</p>
</section>
<section id="hypothesis-and-model" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-and-model">Hypothesis and Model</h2>
<p>Each factor (i.e.&nbsp;meaningful partition of the data) in <a href="#fig-bf2_brush_factor_structure">Figure&nbsp;1</a> corresponds to a term in <a href="#eq-bf2">Equation&nbsp;1</a>:</p>
<p><span id="eq-bf2"><span class="math display">\[
y_\text{ijk} = \mu + \alpha_i + \beta_j + (\alpha\beta)_\text{ij} + \epsilon_\text{ijk}
\tag{1}\]</span></span></p>
<p>Where</p>
<ul>
<li><span class="math inline">\(y_{ijk}\)</span> is the <span class="math inline">\(k^{th}\)</span> observation from the factor level combination of <span class="math inline">\(\alpha_i\)</span> and <span class="math inline">\(\beta_j\)</span>.</li>
<li><span class="math inline">\(\mu\)</span> is the grand mean of all the observations.</li>
<li><span class="math inline">\(\alpha\)</span> is the effect of toothbrush, and <span class="math inline">\(i\)</span> goes from 1 to 4 since there are 4 toothbrush types</li>
<li><span class="math inline">\(\beta\)</span> is the effect of toothpaste, and <span class="math inline">\(j\)</span> is either 1 or 2 since there are 2 levels (Name brand and off brand).</li>
<li>The <span class="math inline">\((\alpha\beta)_\text{ij}\)</span> is called the interaction effect.</li>
<li><span class="math inline">\(\epsilon\)</span> is the residual error term, and <span class="math inline">\(k\)</span> is the replicate count within a factor level combination.</li>
</ul>
<p>There are at least three hypotheses to test with this model. A hypothesis for each main effect, and a hypothesis for the interaction effect.</p>
<p>A hypothesis for the main effect of toothbrush type:</p>
<p><span class="math display">\[H_0: \alpha_\text{i} = 0 \text{ for all } i\]</span></p>
<p><span class="math display">\[H_a: \alpha_\text{i} \ne 0 \text{ for some } i\]</span></p>
<p>A hypothesis for the main effect of toothpaste brand:</p>
<p><span class="math display">\[H_0: \beta_\text{j} = 0 \text{ for all } j\]</span></p>
<p><span class="math display">\[H_a: \beta_\text{j} \ne 0 \text{ for some } j\]</span></p>
<p>A hypothesis for the interaction of toothbrush and toothpaste.</p>
<p><span class="math display">\[
H_0: (\alpha\beta)_\text{ij} = 0 \text{ for all } ij
\]</span></p>
<p><span class="math display">\[
H_a: (\alpha\beta)_\text{ij} \ne 0 \text{ for some } ij
\]</span></p>
<p>When the interaction term is <em>not</em> significant a predicted value for an observation can be obtained by simply adding the grand mean to the main effects <span class="math inline">\(\hat{\alpha}_i\)</span> and <span class="math inline">\(\hat{\beta}_j\)</span>. This is equivalent to treating the effect of <span class="math inline">\((\alpha\beta)_\text{ij} = 0\)</span> for all values of <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>.</p>
<p>When the interaction effect <em>is</em> significant reject the null hypothesis and accept the alternative hypothesis: at least one factor level combination has a none zero effect.</p>
</section>
<section id="assumptions" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>A two-way ANOVA model may be used to analyze data from a BF[2] design if the following requirements are satisfied. Note that these requirements are identical to the requirements of a BF[1] one-way ANOVA.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The BF[] designation refers to the design of the experiment. The reference to one- or two-way ANOVA refers to the analysis technique applied to the resulting data.</p>
</div></div><table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Requirements</th>
<th>Method for Checking</th>
<th>What You Hope to See</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Constant variance across factor levels</td>
<td>Residual vs.&nbsp;Fitted Plot</td>
<td>No major disparity in vertical spread of point groupings</td>
</tr>
<tr class="even">
<td></td>
<td>Levene’s Test</td>
<td>Fail to reject <span class="math inline">\(H_0\)</span></td>
</tr>
<tr class="odd">
<td>Normally Distributed Residuals</td>
<td>Normal Q-Q plot</td>
<td>Straight line, majority of points in boundaries</td>
</tr>
<tr class="even">
<td>Independent residuals</td>
<td>Order plot</td>
<td>No pattern/trend</td>
</tr>
<tr class="odd">
<td></td>
<td>Familiarity with/critical thinking about the experiment</td>
<td>No potential source for bias</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="design" class="level1 page-columns page-full">
<h1>Design</h1>
<p>In a basic factorial design of 2 factors, two factors are purposely varied in such a way that observations are obtained for every possible factor level combination. Each factor level combination is considered a treatment.</p>
<p>In a completely randomized design, each experimental unit is randomly assigned to exactly 1 factor level combination. It can be helpful to first list out all the subjects, factor level combinations, and the order in a non-randomized table. This can be done by listing all the subjects, then listing the values of each factor in a separate column.</p>
<p>We plan to collect 24 observations in total. Since toothbrush has four levels, it seems reasonable to collect <span class="math inline">\(24 \div 4 = 6\)</span> observations per toothbrush. We list each toothbrush type 6 times in the toothbrush column. Toothpaste has 2 levels, so we expect <span class="math inline">\(24 \div 2 = 12\)</span> observations at each level. We list each type of toothpaste 12 times.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>When the number of observations to collect is not a multiple of the factor levels, you will need to make decisions about which factor level will receive more/fewer observations.</p>
</div></div><p>Note that in this case, all the subjects will be brushing over the same two months. The order column in this case refers to the order in which the researchers will measure the patients. From a practicality perspective, it may not be feasible or meaningful to dictate the order in which experimental units are observed. If order can’t be randomized but could be a potential source of bias, it should at least be tracked so that it can be investigated later on.</p>
<p>In some cases, order (chronological, spatial, etc.) does not make sense to worry about. For example, consider a situation where 3 different tests are administered to subjects. All subjects receive the test at the same time and are asked to turn the test in at the same time. In this case, it does not make sense to think of chronological order. Furthermore, if it does not seem reasonable that their seating arrangement (spatial ordering) would affect results, order could be ignored.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a sequence from 1 to 24</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Paste the word "Subject " in front of each id #</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Subject <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Subject"</span>, <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">24</span>), <span class="at">sep =</span> <span class="st">" "</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a vector with each brush repeated 6 times</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>brush <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"manual"</span>, <span class="st">"oscillate"</span>, <span class="st">"sonic"</span>, <span class="st">"ultrasonic"</span>), <span class="at">each =</span> <span class="dv">6</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a vector with each paste repeated 12 times</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>paste <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"off"</span>), <span class="at">each =</span> <span class="dv">12</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a vector to represent order of taking measurement</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>order <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">24</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Combine the vectors of Subject ID's and controlled factor levels into one tibble/dataset</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>assignment_table <span class="ot">&lt;-</span> <span class="fu">tibble</span>(Subject, brush, paste, order)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#print the table, pander() makes it look nice</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(assignment_table) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">brush</th>
<th style="text-align: center;">paste</th>
<th style="text-align: center;">order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 7</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 8</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 9</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 10</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 11</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 12</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 13</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 14</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 15</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 16</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 17</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 18</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 19</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 20</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 21</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 22</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 23</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 24</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">24</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now randomize the brush column, paste column, and the order column.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a sequence from 1 to 24</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Paste the word "Subject " in front of each id #</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Subject <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Subject"</span>, <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">24</span>), <span class="at">sep =</span> <span class="st">" "</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a vector with each brush repeated 6 times</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>brush <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"manual"</span>, <span class="st">"oscillate"</span>, <span class="st">"sonic"</span>, <span class="st">"ultrasonic"</span>), <span class="at">each =</span> <span class="dv">6</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a vector with each paste repeated 12 times</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>paste <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"off"</span>), <span class="at">each =</span> <span class="dv">12</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Combine the vectors of Subject ID's and controlled factor levels into one tibble/dataset</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>randomized_table <span class="ot">&lt;-</span> <span class="fu">tibble</span>(Subject, <span class="fu">sample</span>(brush), <span class="fu">sample</span>(paste), <span class="fu">sample</span>(order))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">#print the table, pander() makes it look nice</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(randomized_table) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">sample(brush)</th>
<th style="text-align: center;">sample(paste)</th>
<th style="text-align: center;">sample(order)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Subject 1</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 2</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 3</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 4</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 5</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 6</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 7</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 8</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 9</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 10</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 11</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 12</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 13</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 14</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 15</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 16</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 17</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 18</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 19</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 20</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 21</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 22</td>
<td style="text-align: center;">ultrasonic</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Subject 23</td>
<td style="text-align: center;">oscillate</td>
<td style="text-align: center;">off</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="even">
<td style="text-align: center;">Subject 24</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">name</td>
<td style="text-align: center;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="interaction-effect" class="level1 page-columns page-full">
<h1>Interaction Effect</h1>
<p>The purpose of this section is to define an interaction, introduce interaction graphs, explain how to interpret interaction graphs to detect interactions, and provide helpful hints in working with interactions.</p>
<p>The terms in <a href="#eq-bf2">Equation&nbsp;1</a> that represent the marginal effects of the controlled factors in the experiment are referred to as <strong>main effects</strong>. In this case <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> are the main effects for toothbrush and toothpaste respectively.</p>
<p>The factor created by crossing toothbrush and toothpaste is called an interaction factor, and its term in the model, <span class="math inline">\(\alpha \beta\)</span>, is called an interaction effect.</p>
<p>Compared to a BF[1], the novel piece of a BF[2] is the <strong>interaction factor</strong>. This factor allows us to estimate the interaction effect, which is the effect of belonging to a particular factor level <em>combination</em>. Stated another way, the interaction effect is the additional change in the response (positive or negative) when the two factor levels happen together, beyond the effect of each factor level in isolation.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>When an interaction is present this means that a factor level’s effect on the response depends on the value of another factor.</p>
</div>
</div>
<p>We will discuss interactions at a conceptual level before dealing with numbers and the arithmetic of calculations. To facilitate this conceptual discussion we will step away from the toothbrush example and use an example for which you have not yet seen any data. We will return to toothbrushes and toothpaste at the end of the conceptual explanation.</p>
<section id="conceptual-understanding" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="conceptual-understanding">Conceptual Understanding</h2>
<p>The concept behind an interaction should feel quite familiar. It is something we deal with everyday and is very common in science. You may have experienced an interaction effect in something as simple as your daily commute:</p>
<blockquote class="blockquote">
<p>Consider a factor to indicate which route you take to work. Route has two levels: using the main roads and using back roads. The time to reach your destination is the response. During rush hour, the main roads are clogged with traffic and result in a longer commute time than taking the back roads. However, in non-rush hour times, the main roads result in a faster commute time. Thus, the effect of taking main roads depends on whether you are traveling during rush hour or not.</p>
</blockquote>
<p>The effect of route was reversed for different levels of rush hour. Not all interactions work this way. Some interactions increase/decrease the magnitude of an effect without completely changing its direction. We can tweak the situation of the commute time example to illustrate this:</p>
<blockquote class="blockquote">
<p>During non-rush hour periods, on average back roads result in a commute time that is 5 minutes faster than main roads. During rush hour periods however, the benefit of taking back rounds compared to main roads increases to 15 minutes. Thus, the size of the effect of back roads increased (is amplified) for rush hour compared to non-rush hour.</p>
</blockquote>
<p>The above descriptions cover just two possible outcomes for this commute time experiment. It may be helpful to visualize the possible outcome scenarios for this two factor (route and rush hour) study. This can effectively be done with an interaction plot. An <strong>interaction plot</strong> shows the means for each factor level combination and usually connects the means from the same factor level with a line to help the reader visually group means and detect effects.</p>
<p><a href="#fig-no-int">Figure&nbsp;2</a> shows four possible outcomes of the traffic study where NO interaction is present. The upper left panel of the plot shows a situation where there are no main effects or interactions apparent. The mean is the same regardless of the factor level combination. The upper right panel of the plot shows a large route effect but no effect due to rush hour. This can be seen because the commute time for back roads is high but commute time for main roads is low; however, for a given route there is no difference in the mean for rush hour vs.&nbsp;not rush hour.</p>
<p>The bottom left panel shows a non-zero effect for the rush hour factor, as seen by the sizable difference between the levels of rush hour within a route. However, the flat lines indicate that the mean commute time for route is not changing and therefore route has no effect on commute time. Lastly, the bottom right panel is a situation where both main effects appear to be present - but there is still no interaction apparent.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>R code instructions to create interaction plots are at the bottom of the R Instructions&gt;<a href="docs/DescribeData.html">Descriptive Summaries</a> page.</p>
</div></div><div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-no-int" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-no-int-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Scenarios with NO Interaction Present</figcaption>
</figure>
</div>
</div>
</div>
<p>The line segments within each graph of <a href="#fig-no-int">Figure&nbsp;2</a> are parallel (or coincide), which is a visual indicator that no interaction is present.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Factors with no interaction will have (nearly) parallel line segments in the interaction plot.</p>
</div>
</div>
<p>So what does an interaction plot look like when there <em>is</em> an interaction present? The key things to notice is that the line segments in the plot are not parallel. <a href="#fig-int">Figure&nbsp;3</a> contains 3 examples of interaction plots that show the presence of an potential interaction.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-int" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-int-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Scenarios Indicative of an Interaction</figcaption>
</figure>
</div>
</div>
</div>
<p>Panel A of <a href="#fig-int">Figure&nbsp;3</a> illustrates an example where the effect of Route reverses, depending on the value for Rush Hour. In Panel B, the effect of Rush Hour is much greater when using main roads than for back roads. In Panel C, main roads take longer regardless of time of day, but the effect of switching from back roads to main roads is much larger during rush hour than in non-rush hour times.</p>
<p>There are a few key points to remember when working with interactions.</p>
<p>First, <strong>exercise caution when interpreting a main effect if an interaction is present</strong>. The definition of an interaction is that a factor level’s effect changes for different values of the other factor. Therefore, it does not make sense to interpret the hypothesis test of a controlled factor if it is part of a significant interaction. Instead, get in the habit of describing the nature of the interaction.</p>
<p>To illustrate the danger of interpreting main effect hypothesis tests when the interaction is significant consider Panel A of <a href="#fig-int">Figure&nbsp;3</a>. If the hypothesis test for Route had a large p-value, it is tempting to say there is insufficient evidence that Route has an effect on commute time. However, the interaction plot shows quite the opposite. Route has an important effect on the response, since the level of Route drastically changes the impact of Rush Hour on commute times. Even though the mean commute time for “back” and “main” may be similar in this scenario, Route is indirectly having an effect on commute time through its interaction with Rush Hour.</p>
<p>Conversely, imagine a scenario where Route’s main effect had a small p-value and the Route - Rush Hour interaction was also significant. If the interaction is like that depicted in Panel C of <a href="#fig-int">Figure&nbsp;3</a>, simply stating that Route is a significant factor does not tell the whole story. The effect of Route in during rush hour is large and may be significant (steep blue line), but the effect of Route in non-rush hour times may not be large enough to reach significance (the nearly flat red line).</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting Main Effects and Interactions
</div>
</div>
<div class="callout-body-container callout-body">
<p>When a significant interaction is present, do not interpret the hypothesis tests of its main effects without providing additional information.</p>
</div>
</div>
<p>Second, <strong>don’t rely on interaction plots alone to detect the presence/absence of interactions.</strong> Though interaction plots are a a helpful tool, they do not adequately show the repsonse variability in each factor level combination. In other words, even when line segments are not parallel a hypothesis test is still needed to determine if an interaction is real or just due to random error. Furthermore, two lines may look nearly parallel but could actually represent a significant interaction.</p>
<p>Lastly, beware of a common mistake that students make. Students commonly state an interaction means that the level of one factor affects the values of another factor. This is a lie from Satan! The key misunderstanding here is thinking that the value of one factor <em>affects the other factor</em>. In reality, it is the factor’s <em>effect on the response</em> that changes for different levels of the other factor. The <strong>two factors do not affect each other</strong>.</p>
</section>
</section>
<section id="decomposition" class="level1 page-columns page-full">
<h1>Decomposition</h1>
<p>So far, we have been discussing the concept of interaction without doing any calculation or using specific numbers. Let’s return to our BF[2] experiment using toothbrush type and toothpaste brand as independent factors, and percent plaque coverage as the response. We will use this data to show how to calculate interaction effects, as well as main effects.</p>
<p>We will then continue on to complete the decomposition of variance and preform an F-test.</p>
<p>As was just mentioned, there are 2 controlled factors: toothbrush type (4 levels) and toothpaste brand (2 levels). A third factor, the interaction, is obtained by crossing the two controlled factors. In terms of the factor diagram, factors are crossed by overlaying the partition lines for the two factors to create new partitions that are also meaningful (see <a href="./factor_structure.html">Factor Structure</a> for a review). <a href="#fig-bf2-structural-factors">Figure&nbsp;4</a> shows the 3 structural factors for a BF[2].</p>
<div id="fig-bf2-structural-factors" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF2-structural-factors-toothbrush.PNG" class="img-fluid figure-img" width="600"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Three structural factors</figcaption>
</figure>
</div>
<p>To get a full structure diagram, as shown in <a href="#fig-bf2_full">Figure&nbsp;5</a> we must also include the universal factors for the grand mean and residuals.</p>
<div id="fig-bf2_full" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/toothbrush_bf2_factor_structure.JPG" class="img-fluid figure-img" width="900"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Factor structure diagram</figcaption>
</figure>
</div>
<p>Each factor in the diagram corresponds to a term in <a href="#eq-bf2_2">Equation&nbsp;2</a>:</p>
<p><span id="eq-bf2_2"><span class="math display">\[
y_\text{ijk} = \mu + \alpha_i + \beta_j + (\alpha\beta)_\text{ij} + \epsilon_\text{ijk}
\tag{2}\]</span></span></p>
<p>Where</p>
<ul>
<li><span class="math inline">\(\mu\)</span> is the grand mean of all observatinos</li>
<li><span class="math inline">\(\alpha\)</span> is the effect of toothbrush, and <span class="math inline">\(i\)</span> goes from 1 to 4 since there are 4 toothbrush types</li>
<li><span class="math inline">\(\beta\)</span> is the effect of toothpaste, and <span class="math inline">\(j\)</span> is either 1 or 2 since there are 2 levels (Name brand and off brand).</li>
<li>The <span class="math inline">\((\alpha\beta)_\text{ij}\)</span> is called the interaction effect.</li>
<li><span class="math inline">\(\epsilon\)</span> is the residual error term, and <span class="math inline">\(k\)</span> is the replicate count within a factor level combination.</li>
</ul>
<p>On the left side of the equation is <span class="math inline">\(y_{ijk}\)</span>, which represents the <span class="math inline">\(k^{th}\)</span> observation from the factor level combination of <span class="math inline">\(\alpha_i\)</span> and <span class="math inline">\(\beta_j\)</span>.</p>
<p>A decomposition of the data is how we estimate these model parameters.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Balanced vs.&nbsp;Unbalanced Data
</div>
</div>
<div class="callout-body-container callout-body">
<p>The formulas and decomposition presented here are for balanced data, where the number of replicates at each factor level combination is the same. In the case of unbalanced data with interaction effects, decisions must be made about how to allocate sums of squares. How to deal with this situation, including R code, is explained in the Unbalanced page under Broad Topics.</p>
</div>
</div>
<section id="factor-effects" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-effects">Factor Effects</h2>
<p>How can an interaction affect be estimated? Like all factor effects, its estimate is calculated using the general rule.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
General Rule for Calculating Factor Level Effect
</div>
</div>
<div class="callout-body-container callout-body">
<p>Factor level effect = mean of the factor level - Sum(effects of all outside factors)</p>
</div>
</div>
<p>From the general rule we can see that before we estimate the interaction effect we first need to estimate the outside factor effects (i.e.&nbsp;main effects). Factor level means need to be calculated in order to calculate estimated effects.</p>
<p>It is also important to recall that the grand mean factor is outside of all other factors, while the residual error factor is inside of all other factors.</p>
<section id="factor-level-means" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="factor-level-means">Factor Level Means</h3>
<p><a href="#fig-bf2_data_partition">Figure&nbsp;6</a> shows our data set with partition lines for structural factors in place. We will now proceed to calculate the factor level means for each factor.</p>
<div id="fig-bf2_data_partition" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF2-data-partition.PNG" class="img-fluid figure-img" width="450"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Full data set with partitions</figcaption>
</figure>
</div>
<p>The grand mean is the mean of all the observations:</p>
<p><span class="math display">\[
\hat{\mu} = \bar{y}_\cdots = \frac{19.12 + 18.56 + 25.58 + 24.39 + 24.21 + ... + 23.42}{24} = 22.76
\]</span></p>
<p>Now find the mean for each level of toothbrush type.</p>
<p><span class="math display">\[
\bar{y}_\text{manual} = \bar{y}_{1\cdot\cdot} = \frac{19.12 + 24.21 + 26.88 + 21.6 + 23.4 + 23.35}{6} = 23.10
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{oscillating} = \bar{y}_{2\cdot\cdot} = \frac{18.56 + 20.00 + 19.87 + 22.09 + 17.62 + 21.72}{6} = 19.98
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{sonic} = \bar{y}_{3\cdot\cdot} = \frac{25.58 + 23.31 + 18.99 + 23.09 + 23.81 + 21.27}{6} = 22.68
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{ultrasonic} = \bar{y}_{4\cdot\cdot} = \frac{24.39 + 21.45 + 32.74 + 24.21 + 25.67 + 23.42}{6} = 25.31
\]</span></p>
<p>Now find the mean for each level of toothpaste brand.</p>
<p><span class="math display">\[
\bar{y}_\text{name brand} = \bar{y}_{\cdot 1 \cdot} = \frac{19.12 + 18.56 + \cdots + 18.99 + 32.74}{12} = 22.93
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{off brand} = \bar{y}_{\cdot 2 \cdot} = \frac{21.60 + 22.09 + \cdots + 21.27 + 23.42}{12} = 22.60
\]</span></p>
<p>There are 8 different combinations of toothbrush type and toothpaste, so the interaction factor has 8 levels total. We calculate a mean for each one, but will only show the calculation for the first 3.</p>
<p><span class="math display">\[
\bar{y}_\text{manual and name brand} = \bar{y}_{11\cdot} = \frac{19.12 + 24.21 + 26.88}{3} = 23.40
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{manual and off brand} = \bar{y}_{12\cdot} = \frac{21.60 + 23.40 + 23.35}{3} = 22.78
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{oscillating and name brand} = \bar{y}_{21\cdot} = \frac{18.56 + 20.00 + 19.87}{3} = 19.48
\]</span></p>
<p>The means for the residual error factor levels is the observed value itself since there is just 1 observation per level. Therefore, there are no calculations to show.</p>
<p><a href="#fig-factor-means">Figure&nbsp;7</a> displays all the factor level means inside the factor structure.</p>
<div class="column-page">
<div id="fig-factor-means" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF2-toothbrush_means.PNG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Factor level means</figcaption>
</figure>
</div>
</div>
</section>
<section id="factor-level-effects" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="factor-level-effects">Factor Level Effects</h3>
<section id="grand-mean-effect" class="level4">
<h4 class="anchored" data-anchor-id="grand-mean-effect">Grand mean effect</h4>
<p>Now that we have calculated means for each level of each factor, we can move on to calculate the effects of the factor levels.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>For the grand mean, there is only one level and there are no outside factors. Therefore, the effect due to grand mean is 22.76 (equivalent to its mean) and this affect is applied to all 24 observations.</p>
</section>
<section id="toothbrush-effects" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="toothbrush-effects">Toothbrush effects</h4>
<p>The toothbrush factor has four levels: one for each brush type. We will use the general rule for calculating <a href="#factor-level-effects">factor level effects</a>. To calculate the effect of a toothbrush, take the toothbrush mean and subtract it from the grand mean factor’s effect. For the manual brush, this looks like:</p>
<p><span class="math display">\[
23.09 - 22.76 = 0.33
\]</span></p>
<p>Using the manual brush has the effect of <em>increasing</em> a person’s plaque area percentage by 0.33 percentage points on average compared to the grand mean. In a similar way<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> you can find the effect for the oscillating brush <span class="math inline">\(19.98 - 22.76 = -2.79\)</span>. This means the amount of plaque decreased by 2.79 on average with this brush compared to the grand mean. For a sonic toothbrush, the effect is <span class="math inline">\(22.68 - 22.76 = -0.09\)</span>. For an ultrasonic brush the effect is <span class="math inline">\(25.31 - 22.76 = 2.55\)</span>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>It is interesting to note that the factor effects for brush type are the same, whether toothpaste brand is included in the analysis or not.</p>
</div></div></section>
<section id="toothpaste-effects" class="level4">
<h4 class="anchored" data-anchor-id="toothpaste-effects">Toothpaste effects</h4>
<p>Calculating the effects for the second controlled factor in the experiment follows a similar pattern and also uses the general rule for calculating effect sizes. Remember that toothbrush is not outside or inside of toothpaste, rather the two factors are crossed. To calculate the effect of using the name brand toothpaste, take the name brand mean and subtract it from the grand mean factor’s effect:</p>
<p><span class="math display">\[
22.93 - 22.76 = 0.16
\]</span></p>
<p>A similar calculation is performed for off the brand toothpaste.</p>
<p><span class="math display">\[
22.60 - 22.76 = -0.16
\]</span></p>
<p>With only two levels, it becomes obvious that <strong>the effects of a factor’s levels will always sum to zero</strong>. You may want to go back to the toothbrush level effects and verify this is true.</p>
</section>
<section id="interaction-effects" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="interaction-effects">Interaction effects</h4>
<p>The general rule says that effects of outside factors must be subtracted from the factor level mean. We pause to review the relationship of the other factors to the interaction factor to determine if they are inside, outside, or crossed with each other.</p>
<div id="fig-crossed-interaction" class="column-page quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-brush" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF2-interaction-inside-brush.PNG" class="img-fluid figure-img" data-ref-parent="fig-crossed-interaction"></p>
<figcaption class="figure-caption">(a) Interaction inside of brush</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-paste" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF2-interaction-inside-paste.PNG" class="img-fluid figure-img" data-ref-parent="fig-crossed-interaction"></p>
<figcaption class="figure-caption">(b) Interaction inside of toothpaste</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;8: Interaction Effects</figcaption><p></p>
</figure>
</div>
<p>In <a href="#fig-brush">Figure&nbsp;8 (a)</a> you can see that each level of the interaction will fit nicely within a level of toothbrush, this means toothbrush is outside of interaction (equivalently, interaction is inside of toothbrush). The same holds true for the relationship of toothpaste brand and interaction, as shown in <a href="#fig-paste">Figure&nbsp;8 (b)</a>.</p>
<p>Therefore, to calculate the interaction effect for using an ultrasonic brush with name brand toothpaste we will subtract the effects of the grand mean factor, ultrasonic brush, and name brand paste from the “ultrasonic, name brand” level mean.</p>
<p><span class="math display">\[
26.19 - (22.76 + 2.55 + 0.16) = .15
\]</span></p>
<p>Let’s take a deeper look to understand why this works. It can be helpful to remember our assembly line analogy. We will walk through this assembly line, showing a graph to illustrate how the effects are added at each station.</p>
<p>An observation from the “ultrasonic brush, name brand paste” group starts with the grand mean value of 22.76. The observation belongs to the ultrasonic group, where plaque tends to be higher, specifically 2.55 higher on average (2.55 is the effect of ultrasonic). <a href="#fig-brush-effect">Figure&nbsp;9</a> show the starting point of the grand mean and the addition of the brush effect.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-brush-effect" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-brush-effect-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;9: Grand mean + brush effect</figcaption>
</figure>
</div>
</div>
</div>
<p>At the next step, because the observation belongs to the Name Brand Toothpaste group we would tack on an additional 0.16 of plaque coverage, as shown in <a href="#fig-paste-effect">Figure&nbsp;10</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-paste-effect" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-paste-effect-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;10: Grand mean + brush effect + paste effect</figcaption>
</figure>
</div>
</div>
</div>
<p>What we haven’t accounted for yet is the fact that the ultrasonic brush and name brand toothpaste have appeared <em>together</em>. If the interaction is significant then we can expect a synergistic effect (in either direction) and will need to add/subtract more to the response. Otherwise, the interaction effects will be small (relative to the error variance).</p>
<p>There is an old saying, “the whole is greater than the sum of its parts”. In a way, the interaction effect is the measure of how much greater. <a href="#fig-int-effect">Figure&nbsp;11</a> shows that after summing the main effects of each controlled factor, the remaining distance to the mean of the factor level combination is the interaction effect. We calculated this above using the general rule and found the distance to be 0.15.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-int-effect" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-int-effect-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;11: Interaction effect is remaining distance to factor level mean</figcaption>
</figure>
</div>
</div>
</div>
<p>The previous 3 figures are placed side by side below in the figure below so that the additive progression of the effects can more easily be seen.</p>
<div class="page-columns page-full">
<div id="fig-side_by_each" class="cell column-screen-inset-shaded quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-side_by_each-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-side_by_each-1.png" class="img-fluid figure-img" data-ref-parent="fig-side_by_each" width="672"></p>
<figcaption class="figure-caption">(a) <strong>?(caption)</strong></figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-side_by_each-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-side_by_each-2.png" class="img-fluid figure-img" data-ref-parent="fig-side_by_each" width="672"></p>
<figcaption class="figure-caption">(b) <strong>?(caption)</strong></figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-side_by_each-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-side_by_each-3.png" class="img-fluid figure-img" data-ref-parent="fig-side_by_each" width="672"></p>
<figcaption class="figure-caption">(c) <strong>?(caption)</strong></figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;12: Additive Effects</figcaption><p></p>
</figure>
</div>
<p>Additive Effects</p>
</div>
<p>Lastly, the residuals (or residual effects) need to be calculated. The mean for each level of residual is simply the observation itself. Effects associated with that observation’s factor levels are subtracted from the observed value. Whatever is left over is considered the residual. In other words, we have applied the general rule for calculating effect size. For the residual factor, the effect can concisely be stated as “observed value - predicted value”.</p>
<p>As an example, the residual in the top left corner of the residual factor was obtained with this calculation:</p>
<p><span class="math display">\[
19.12 - (22.76 + 0.329 + 0.16 + 0.15) = -4.28
\]</span></p>
<p>All other residuals were similarly obtained. Ultimately, <a href="#fig-factor-effects">Figure&nbsp;13</a> displays all the factor level effects that are summed to obtain each observation.</p>
<div class="column-page">
<div id="fig-factor-effects" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/BF2-toothbrush_effects.PNG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13: Factor level effects</figcaption>
</figure>
</div>
</div>
</section>
</section>
</section>
<section id="degrees-of-freedom" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h2>
<p>We can use our understanding of <a href="./factor_structure.html">inside vs.&nbsp;outside factors</a> to determine the degrees of freedom (df) for the <strong>grand mean</strong>, <strong>treatment factors</strong>, <strong>interaction</strong> and <strong>residual errors</strong>. We start with 24 observations - or pieces of information. In other words, we have 24 degrees of freedom that need to be allocated to the factors.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
General Rule for Degrees of Freedom
</div>
</div>
<div class="callout-body-container callout-body">
<p>df<span class="math inline">\(_\text{factor}\)</span> = Total levels of a factor minus the sum of the df of all outside factors</p>
<p>An alternative way to find degrees of freedom is to count the number of unique pieces of information in a factor.</p>
</div>
</div>
<p>In the toothbrush and toothpaste example, <strong>grand mean</strong> has one level and there are no factors outside of grand mean. Therefore, its degrees of freedom equals one. This will always be the case.</p>
<p>Remember, the degrees of freedom represent the number of unique pieces of information contributing to the estimation of the effects for that factor. In this case, as soon as you estimate the grand mean for just one of the observations, you know it for all the observations. In other words, only 1 value was <em>free</em> to vary. As soon as it was known all the other values for the grand mean effect were also known. Therefore, there is just one unique piece of information in the grand mean factor. Grand mean has just 1 degree of freedom.</p>
<p>In this case there are two controlled factors, or treatment factors: toothbrush and toothpaste. For toothbrush there are four levels of the factor. Grand mean is the only factor outside of toothbrush. Take the number of levels for toothbrush (4) and subtract the degrees of freedom for grand mean (1), which yields 4-1 = <strong>3 degrees of freedom</strong>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The degrees of freedom for toothbrush is it the same here as it was for the BF[1].</p>
</div></div><p>We could just as easily have used the other approach to finding the degrees of freedom: counting the unique pieces of information. Upon examining the factor for toothbrush in <a href="#fig-factor-effects">Figure&nbsp;13</a> you can see there are 4 unique numbers. We know the effects for toothbrush must sum to zero, so the 4th effect is not free to vary. As soon as I know the effect for 3 of the brushes, I can fill in all the effects for the toothbrush factor.</p>
<p>A similar approach is taken for toothpaste. Here it is even more obvious that the effects for toothpaste sum to zero. After estimating the toothbrush effect for one observation, I can fill in the toothpaste effects for all the other observations. Therefore, the degrees of freedom for toothpaste is 1.</p>
<p>Using the general rule, I know there are 2 levels for toothpaste and grand mean is the only outside factor. Since grand mean has 1 degree of freedom, I get <span class="math inline">\(2-1 = 1\)</span> degree of freedom for toothpaste.</p>
<p>Now we must calculate degrees of freedom for the interaction term. Take a closer look at the interaction effects in <a href="#fig-factor-effects">Figure&nbsp;13</a>. You can see that the numbers repeat within each cell. There are 8 cells total. You can also see that the effects inside a column of values sum to zero, as do the values in a row. Therefore, I really only need to know a value in 3 of the cells of the interaction factor before I can fill in the effects for all the other cells in that factor.</p>
<p>This is in perfect harmony with an application of the general rule. The interaction factor has 8 factor levels. Factors outside of the interaction include: grand mean (1 df), toothbrush (3 df), and toothpaste (1 df). Applying the general rule with these values yields <span class="math inline">\(8 - (1 + 3 + 1) = 3\)</span> degrees of freedom for the interaction factor.</p>
<p>Perhaps the easiest way to find the degrees of freedom for an interaction that is created by crossing two other factors is to multiply the degrees of freedom of the two other factors. In this case, toothbrush and toothpaste are crossed, so you would get <span class="math inline">\(3*1 = 3\)</span>, which matches the answer found using other methods.</p>
<p>Finally, the residual degrees of freedom can be found using the general rule. Since the residual error factor is inside of all other factors, this is the same as finding how many degrees of freedom are leftover after calculating degrees of freedom for all other factors. In this example, there were 24 observations total, so we subtract the degrees of freedom for the other factors from 24. This returns <span class="math inline">\(24 - (1+3+1+3) = 16\)</span> degrees of freedom for residuals.</p>
<p>The other approach to finding the degrees of freedom for residuals is to group the residuals by the smallest structural factor partitions (in this case the interaction). Inside each of those partitions the residuals sum to zero. For example, applying the interaction partition to residuals gives the values <span class="math inline">\(-4.28\)</span>, <span class="math inline">\(0.81\)</span>, and <span class="math inline">\(3.48\)</span>. Since we know the 3 residuals sum to zero in each partition, we only need to know 2 values per partition in order to fill in the third residual effect. With 8 partitions applied to the residuals, we have <span class="math inline">\(2x8 = 16\)</span> degrees of freedom for residual error.</p>
</section>
<section id="completing-the-anova-table" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="completing-the-anova-table">Completing the ANOVA Table</h2>
<p>Now that we have calculated degrees of freedom and effects for each factor , we can calculate the remaining pieces of the ANOVA table: <strong>Sum of Squares (SS), Mean Squares (MS), F-statistic and p-value</strong>. A completed ANOVA summary table contains the information we need for a hypothesis test of the main effects (for controlled factors) and their interaction.</p>
<p>In an ANOVA table, each factor and their associated degrees of freedom are listed on the left. Note: the total degrees of freedom are the total number of observations.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Toothpaste</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush:Toothpaste</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>To get the <strong>sum of squares (SS)</strong> of a factor, each value displayed in that particular factor first needs to be squared. <a href="#fig-factor-effects">Figure&nbsp;13</a> shows the effects, while <a href="#fig-SQ-effects">Figure&nbsp;14</a> shows the squared effects.</p>
<!-- ::: {#fig-effects layout-nrow=2} -->
<!-- ![Factor level effects](images/BF2-toothbrush_effects.PNG){#fig-factor-effects .column-page} -->
<!-- ![Squared factor level effects](images/BF2-toothbrush_SQ_effects.PNG){#fig-SQ-effects .column-page} -->
<!-- BF[2] Toothbrush x toothpaste example -->
<!-- ::: -->
<div id="fig-SQ-effects" class="quarto-figure quarto-figure-center column-page anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="images/BF2-toothbrush_SQ_effects.PNG" class="column-page img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;14: Squared factor level effects</figcaption>
</figure>
</div>
<p>Then, for each factor, all the squared values are summed up to get the sum of squares. The total sum of squares is obtained by summing the squared observations as shown in <a href="#eq-ss-obs">Equation&nbsp;3</a>. This represents the total variability in the dataset that will then be allocated or partitioned to the various factors, starting with the grand mean.</p>
<p><span id="eq-ss-obs"><span class="math display">\[
SS_\text{total} = 365.6 + 344.5 + 654.3 + ... + 452.4 + 548.2  = 12,674.30
\tag{3}\]</span></span></p>
<p>For <strong>grand mean</strong>, the squared effect of 518.2 is listed 24 times, once for each observation. Summing the squared effects gets:</p>
<p><span class="math display">\[
SS_\text{Grand Mean} = 518.2* 24 = 12,437.43
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The rounded numbers are displayed throughout this section, but all calculations are done using the unrounded numbers.</p>
</div>
</div>
<p>The <strong>toothbrush factor</strong> has four different effects: one for each level of the factor. For each effect, the squared value is multiplied by the number of observations within the level of the factor. Then, the results are added across all levels to get the sum of squares due to toothbrush.</p>
<p><span id="eq-ss-int"><span class="math display">\[
SS_\text{toothbrush} = 6*(0.11) + 6*(7.77) + 6*(0.01) + 6*(6.50) = 86.31
\tag{4}\]</span></span> <br></p>
<p>The sum of squares is similarly calculated for toothpaste brand (<a href="#eq-ss-paste">Equation&nbsp;5</a>) and brush by paste interaction (<a href="#eq-ss-int">Equation&nbsp;4</a>).</p>
<p><span id="eq-ss-paste"><span class="math display">\[
SS_\text{toothpaste} = 12*(0.03) + 12*(0.03) = 0.62
\tag{5}\]</span></span></p>
<p><span class="math display">\[
SS_\text{brush x paste} = 3*(0.02) + 3*(0.44) + 3*(0.04) + 3*(0.52) +3*(0.02) + 3*(0.44) + 3*(0.04) + 3*(0.52)  = 6.12
\]</span></p>
<p>The effect for the <strong>residual error factor</strong> has 24 unique values. The squared residuals are summed together in <a href="#eq-ss-resid">Equation&nbsp;6</a>.</p>
<p><span id="eq-ss-resid"><span class="math display">\[
SS_\text{residual} = 18.35 + 0.84 + 8.72 + ... + 2.11 + 1.03  = 143.82
\tag{6}\]</span></span></p>
<p>You can check that the sums of squares (SS) has been allocated to the factors correctly by adding up the SS for each factor and verifying that it also equals the result found in <a href="#eq-ss-obs">Equation&nbsp;3</a>.</p>
<p>Putting this information into the ANOVA table gets us the result shown in <a href="#tbl-SS">Table&nbsp;1</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-SS" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;1: Sums of squares</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12437.43</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">86.31</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Toothpaste</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush:Toothpaste</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6.12</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">143.82</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">12674.30</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Recall that SS is a measure of total variability. Of the three structural factors (brush, toothpaste, and their interaction) it is clear to see that brush is contributing the most variability. Some of the difference in SS may be due to difference in number of levels for each factor. Adding levels to a factor allows more variability to be attributed to that factor. We will convert this total variability (sum of squares) into a mean variability (mean square) measure to properly account for differences in number of factor levels. This allows us to compare the factors’ variability on a standardized scale.</p>
<p>To calculate a mean square (MS), simply divide SS by degrees of freedom for a factor. The mean square calculations are:</p>
<p><span class="math display">\[
MS_\text{Grand Mean} = \frac{SS_\text{Grand Mean}}{df_\text{Grand Mean}} = \frac{12437.43}{1} = 12437.43
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Brush} = \frac{SS_\text{Brush}}{df_\text{Brush}} = \frac{86.31}{3} = 28.77
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Toothpaste} = \frac{SS_\text{Toothpaste}}{df_\text{Toothpaste}} = \frac{0.62}{1} = 0.62
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Brush:Toothpaste} = \frac{SS_\text{Brush:Toothpaste}}{df_\text{Brush:Toothpaste}} = \frac{6.12}{3} = 2.04
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Residual Error} = \frac{SS_\text{Residual Error}}{df_\text{Residual Error}} = \frac{143.82}{16} = 8.99
\]</span></p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12437.43</td>
<td style="text-align: right;">12437.43</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">86.31</td>
<td style="text-align: right;">28.77</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Toothpaste</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush:Toothpaste</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6.12</td>
<td style="text-align: right;">2.04</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">143.82</td>
<td style="text-align: right;">8.99</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">12674.30</td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>For each structural factor in the design there are a set of hypothesis we want to test using the <strong>F statistic</strong>.</p>
<p>Specifically, we will want to test whether toothbrush type has an effect on plaque coverage, whether toothpaste brand has an effect on plaque coverage, and whether the interaction between brush and paste has an effect on plaque coverage.</p>
<p>More specifically, for each factor we test whether the factor level effects are all equal to zero. We can express the hypotheses mathematically using the terms of <a href="#eq-bf2_2">Equation&nbsp;2</a>.</p>
<p>A hypothesis for the main effect of toothbrush type:</p>
<p><span class="math display">\[H_0: \alpha_\text{i} = 0 \text{ for all } i\]</span></p>
<p><span class="math display">\[H_a: \alpha_\text{i} \ne 0 \text{ for some } i\]</span></p>
<p>A hypothesis for the main effect of toothpaste brand:</p>
<p><span class="math display">\[H_0: \beta_\text{j} = 0 \text{ for all } j\]</span></p>
<p><span class="math display">\[H_a: \beta_\text{j} \ne 0 \text{ for some } j\]</span></p>
<p>A hypothesis for the interaction of toothbrush and toothpaste.</p>
<p><span class="math display">\[
H_0: (\alpha\beta)_\text{ij} = 0 \text{ for all } ij
\]</span></p>
<p><span class="math display">\[
H_a: (\alpha\beta)_\text{ij} \ne 0 \text{ for some } ij
\]</span></p>
<p>To test these hypotheses we need to compare the mean square (MS) for a factor to the mean square for residual error (abbreviated as MSE). The MSE is the estimate of unexplained, random error. If a factor’s MS is similar in size to the MSE, the variance in that factor may just be random error; and the effect of the factor levels are zero. On the other hand, if the variability in the factor, as measured by its MS, is much larger than the random error observed in the experiment (represented by MSE), then it is reasonable to believe the factor levels have a non-trivial contribution to the variability. In other words, the factor has a significant effect on the response.</p>
<p>The F statistic is a ratio of these two errors and is obtained by dividing the factor’s mean square (MS) by the MSE. The F statistic calculations are</p>
<ul>
<li><p><span class="math inline">\(F_\text{brush} = 28.77/8.99 = 3.20\)</span></p></li>
<li><p><span class="math inline">\(F_\text{toothpaste} = 0.62/8.99 = 0.07\)</span></p></li>
<li><p><span class="math inline">\(F_\text{brush:toothpaste} = 2.04 / 8.99 = .23\)</span></p></li>
</ul>
<p>This F statistic follows a well defined distribution, called the F distribution. The F distribution is defined by two values for degrees of freedom<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>:</p>
<ul>
<li>the numerator degrees of freedom, which is the degrees of freedom for the factor being tested</li>
<li>the denominator degrees of freedom, which is the degrees of freedom for residual error</li>
</ul>
<p>The area under this distribution curve to the right of our F statistic is called the p-value. The p-value represents the probability of getting an F statistic at least as large as the one obtained, assuming the null hypothesis (of no effect) is true.</p>
<p>The F statistic, numerator degrees of freedom, and denominator degrees of freedom are the 3 required inputs to calculate a p-value. P-values can be obtained manually using the applet mentioned above, the <code>f.dist.rt()</code><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> function in excel or the <code>pf()</code> function in R<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. Usually though, R will show p-values as part of the standard output of the ANOVA model/table and it is recommended you stick to those values when reporting answers.</p>
<p>The completed ANOVA table for this BF[2] toothbrush and toothpaste example is shown in</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12437.43</td>
<td style="text-align: right;">12437.43</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">86.31</td>
<td style="text-align: right;">28.77</td>
<td style="text-align: right;">3.20</td>
<td style="text-align: right;">0.051</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Toothpaste</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brush:Toothpaste</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6.12</td>
<td style="text-align: right;">2.04</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.876</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">143.82</td>
<td style="text-align: right;">8.99</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">12674.30</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Because the p-value for the interaction (p-value = 0.876) is much higher than any traditional level of significance threshold we might have chosen (0.01, 0.05, or 0.1), we fail to reject the null hypothesis. There is insufficient evidence to say the interaction effect has an effect on plaque coverage. Because the interaction is NOT significant, we can proceed to interpret the main effects test results.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Significant Interaction Effects
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the interaction effect is significant, great caution should be taken when interpreting the hypothesis test results for the factors involved in the interaction; it may not be valid to interpret the hypothesis test results. Instead, if the interaction is significant, it is better to describe the nature of the interaction with graphs, numbers, and words.</p>
</div>
</div>
<p>Toothpaste’s p-value is high (p-value = 0.8), indicating no evidence that toothpaste brand has an effect on plaque coverage. The p-value for brush is marginally significant (p-value = 0.051). When (in)significance is borderline, rather than making bold statements based on a small amount of (in)significance, it is helpful to dig a little deeper. Consider things like sample size, effect size (practical significance), outliers, and how closely assumptions are met. After weighing those considerations carefully, take a stance and state your belief about the role of the factor on the response. Explain your rationale, then keep an open mind and stay curious.</p>
</section>
</section>
<section id="analysis-in-r" class="level1 page-columns page-full">
<h1>Analysis in R</h1>
<p>We will illustrate the R code used for a BF[2] analysis while continuing to use the toothbrush and toothpaste example that has been used throughout this page.</p>
<section id="describe-the-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="describe-the-data">Describe the Data</h2>
<p>When working with a dataset the first thing to do is get to know your data through numerical and graphical summaries. Numerical summaries typically consist of means, standard deviations, and sample sizes for each factor level. Graphical summaries most usually are boxplots, scatterplots, and/or interaction plots with the means displayed.</p>
<p>Interactive code and additional explanations of numerical summaries and plots in R are found at <a href="DescribeData.html">R Instructions-&gt;Descriptive Summaries</a> section of the book.</p>
<section id="numerical-summaries" class="level3">
<h3 class="anchored" data-anchor-id="numerical-summaries">Numerical Summaries</h3>
<p>After loading required packages, we will read in the data and do some wrangling.</p>
<div class="cell" data-cap="Read in / Wrangle Data">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>bf2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/toothpaste_BF2.csv"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We then calculate summary statistics for each factor level separately.</p>
<div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of Brush</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Plaque<span class="sc">~</span>Brush, <span class="at">data =</span> bf2) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of Toothpaste</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Plaque<span class="sc">~</span>Toothpaste, <span class="at">data =</span> bf2) <span class="sc">|&gt;</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-main_effects_numbers" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p>Table&nbsp;2: Numerical Summary for Each Factor</p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-main_effects_numbers-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-main_effects_numbers" style="flex-basis: 100.0%;justify-content: center;">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>(a) Brush</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Brush</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manual</td>
<td style="text-align: right;">19.12</td>
<td style="text-align: right;">22.04</td>
<td style="text-align: right;">23.38</td>
<td style="text-align: right;">24.01</td>
<td style="text-align: right;">26.88</td>
<td style="text-align: right;">23.09</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oscillating</td>
<td style="text-align: right;">17.62</td>
<td style="text-align: right;">18.89</td>
<td style="text-align: right;">19.94</td>
<td style="text-align: right;">21.29</td>
<td style="text-align: right;">22.09</td>
<td style="text-align: right;">19.98</td>
<td style="text-align: right;">1.74</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sonic</td>
<td style="text-align: right;">18.99</td>
<td style="text-align: right;">21.73</td>
<td style="text-align: right;">23.20</td>
<td style="text-align: right;">23.68</td>
<td style="text-align: right;">25.58</td>
<td style="text-align: right;">22.67</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ultrasonic</td>
<td style="text-align: right;">21.45</td>
<td style="text-align: right;">23.62</td>
<td style="text-align: right;">24.30</td>
<td style="text-align: right;">25.35</td>
<td style="text-align: right;">32.74</td>
<td style="text-align: right;">25.31</td>
<td style="text-align: right;">3.90</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">


</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-main_effects_numbers-2" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-main_effects_numbers" style="flex-basis: 100.0%;justify-content: center;">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>(b) Toothpaste</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Toothpaste</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NameBrand</td>
<td style="text-align: right;">18.56</td>
<td style="text-align: right;">19.68</td>
<td style="text-align: right;">22.38</td>
<td style="text-align: right;">24.69</td>
<td style="text-align: right;">32.74</td>
<td style="text-align: right;">22.92</td>
<td style="text-align: right;">4.18</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">OffBrand</td>
<td style="text-align: right;">17.62</td>
<td style="text-align: right;">21.69</td>
<td style="text-align: right;">23.22</td>
<td style="text-align: right;">23.52</td>
<td style="text-align: right;">25.67</td>
<td style="text-align: right;">22.60</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">


</div>
</div>
</div>
</div>
<p>In <a href="#tbl-main_effects_numbers">Table&nbsp;2</a> (a) we see that the oscillating brush has lowest mean plaque (19.98). <a href="#tbl-main_effects_numbers">Table&nbsp;2</a> (b) shows the mean plaque for the two types of toothpaste is very close, 22.92 for Name Brand and 22.60 for Off Brand.</p>
<p>You can also look at descriptive statistics for factor level combinations. This is only advisable if there is sufficient sample size at each combination and the number of combinations is manageable. <a href="#tbl-numerical">Table&nbsp;3</a> shows what that looks like for our current example. Due to the many combinations, it is a bit difficult to interpret the output. Furthermore, using a 5 number summary on a sample size of 3 observations is not advisable so some of the summary statistics have been dropped.</p>
<p>The combination of Oscillating with Name Brand has the lowest mean (19.48) and the lowest standard deviation (0.80).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Plaque<span class="sc">~</span>Brush<span class="sc">+</span>Toothpaste, <span class="at">data =</span> bf2) <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Brush.Toothpaste, mean, sd, n) <span class="sc">|&gt;</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="tbl-numerical" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;3: Numerical Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Brush.Toothpaste</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manual.NameBrand</td>
<td style="text-align: right;">23.40</td>
<td style="text-align: right;">3.94</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oscillating.NameBrand</td>
<td style="text-align: right;">19.48</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sonic.NameBrand</td>
<td style="text-align: right;">22.63</td>
<td style="text-align: right;">3.35</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ultrasonic.NameBrand</td>
<td style="text-align: right;">26.19</td>
<td style="text-align: right;">5.86</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manual.OffBrand</td>
<td style="text-align: right;">22.78</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oscillating.OffBrand</td>
<td style="text-align: right;">20.48</td>
<td style="text-align: right;">2.48</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sonic.OffBrand</td>
<td style="text-align: right;">22.72</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ultrasonic.OffBrand</td>
<td style="text-align: right;">24.43</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</section>
<section id="graphical-summaries" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="graphical-summaries">Graphical Summaries</h3>
<p>Graphs are also valuable tools to help you get to know your data. Since there are only 3 observation in each factor level combination, a dotplot/scatterplot is more appropriate than a boxplot. This is shown in <a href="#fig-summary">Figure&nbsp;15</a></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Note, I have to turn Brush into a factor because it started out as a character variable</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot</span>(Plaque<span class="sc">~</span><span class="fu">factor</span>(Brush)<span class="sc">|</span><span class="fu">factor</span>(Toothpaste), <span class="at">data =</span> bf2, </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-summary" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-summary-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;15: Graphical Summary</figcaption>
</figure>
</div>
</div>
</div>
<p>You could also gain insight about the main effects by cutting the data by each factor separately, as shown in <a href="#fig-by_factor">Figure&nbsp;16</a>.</p>
<div id="fig-by_factor" class="cell column-page quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-by_factor-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-by_factor-1.png" class="img-fluid figure-img" data-ref-parent="fig-by_factor" width="672"></p>
<figcaption class="figure-caption">(a) Brush</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-by_factor-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-by_factor-2.png" class="img-fluid figure-img" data-ref-parent="fig-by_factor" width="672"></p>
<figcaption class="figure-caption">(b) Toothpaste</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;16: Data cut by one factor at a time</figcaption><p></p>
</figure>
</div>
<p>Finally, an interaction plot is ideal for investigating a BF[2]. The plot only shows factor level means. Therefore, it does not give a good sense of the underlying distribution of data and should not be used as the only visual assessment of your data. However, it is extremely good at providing insight into possible interactions.</p>
<p>In <a href="#fig-tooth_int">Figure&nbsp;17</a> the lines are not parallel. In fact, they cross twice. Though this seems to suggest an interaction is present, our ability to claim an interaction exists will depend on the results of a hypothesis test. The hypothesis test is greatly influenced by sample size and the variability at each of the factor level means presented in the plot.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tooth_int" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-tooth_int-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;17: Interaction plot for Brush vs.&nbsp;Toothpaste</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="create-the-model" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="create-the-model">Create the Model</h2>
<p>You then create the model using the <code>aov()</code> function. To see results of the F-test you can feed your model into a <code>summary()</code> or <code>anova()</code> function.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>summary()</code> and <code>anova()</code> functions give the same output with some slight differences in formatting when called on a model created with <code>aov()</code>. The <code>summary()</code> function is more general; it can also take linear regression models created with <code>'lm()</code> as inputs. The output provided by <code>summary()</code> will change based on the type of object it is called on. This is discussed in more detail at the bottom of the <a href="./unbalanced.html">Unbalanced</a> page.</p>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>myaov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Y <span class="sc">~</span> X1<span class="sc">*</span>X2, <span class="at">data=</span>YourDataSet)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>myaov</code> is the user defined name in which the results of the aov() model are stored</li>
<li><code>Y</code> is the name of a numeric variable in your dataset which represents the quantitative response variable.</li>
<li><code>X1</code> and <code>X2</code> are names of qualitative variables in your dataset. They should have class(X) equal to factor or character. If that is not the case, use <code>factor(X)</code> inside the <code>aov(Y ~ factor(X1)*...)</code> command.</li>
<li><code>YourDataSet</code> is the name of your data set.</li>
</ul>
<p>The <code>*</code> in the code above is a shortcut for writing out the whole model. It can be read as, “include each term by itself, and all possible interaction terms”. The long way of writing out the model uses a colon, <code>:</code>, to define interaction terms and is shown below. When writing it this way each term must be explicitly stated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>myaov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Y <span class="sc">~</span> X1<span class="sc">+</span>X2<span class="sc">+</span>X1<span class="sc">:</span>X2, <span class="at">data=</span>YourDataSet)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Below are the results for the full BF[2] model using the toothbrush and toothpaste example. You should notice that these results match what we got when we performed the decomposition manually to build the ANOVA summary table. Even though the interaction plot showed crossing lines, we see the interaction between Brush and Toothpaste is not significant (p-value = .8763). This means we can interpret the hypothesis tests for each of the main effects.</p>
<p>Toothpaste is not significant (p-value = .7966) and Brush is marginally significant (p-value = .0517, which is close to the traditional alpha level of 0.05). Our exploratory analysis showed that oscillating brush resulted in the lowest amount of plaque and the ultrasonic brush resulted in the highest plaque measure.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>bf2_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Plaque<span class="sc">~</span>Brush<span class="sc">*</span>Toothpaste,<span class="at">data=</span>bf2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bf2_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 Df Sum Sq Mean Sq F value Pr(&gt;F)  
Brush             3  86.31  28.769   3.201 0.0517 .
Toothpaste        1   0.62   0.618   0.069 0.7966  
Brush:Toothpaste  3   6.12   2.040   0.227 0.8763  
Residuals        16 143.82   8.989                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In order to trust these hypothesis test results we need to verify that the assumptions are met.</p>
</section>
<section id="check-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-assumptions">Check Assumptions</h2>
<p>For a more detailed explanation of the code, output, and theory behind these assumptions visit the <a href="./assumptions.html">Assumptions</a> page.</p>
<section id="constant-variance-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="constant-variance-of-residuals">Constant Variance of Residuals</h3>
<p>There needs to be constant variance of residuals across the factor level combinations. First, we can check the residual plot.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bf2_aov, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-constant_var" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-constant_var-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;18: Checking constant variance</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-constant_var">Figure&nbsp;18</a> there are 8 distinct vertical groupings of points, one for each factor level combination. There are 3 observations, and so 3 residuals also, for each factor level combination. There does seem to be a slight trend for points with larger predicted values to be more spread out. On the far left of the plot the points appear closer together, as you move to the right the points tend to be more spread out (thought not always). This phenomenon raises the concern that the assumption of constant variance across factor level combinations may be violated.</p>
<p><a href="assumptions.html#constant-variance">Levene’s test</a> can provide insight on whether the trend in the residual plot is drastic enough to constitute a violation of the constant variance assumption.</p>
<p>Recall that the null hypothesis for Levene’s test is that the variance of residuals is equal for each and every factor level combination. The results of the test below shows a p-value of 0.5409. We therefore fail to reject a null hypothesis of equal variances and proceed with the analysis (assuming the other assumptions are met).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(bf2_aov) <span class="sc">%&gt;%</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.54</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">16</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="normally-distributed-residuals" class="level3">
<h3 class="anchored" data-anchor-id="normally-distributed-residuals">Normally Distributed Residuals</h3>
<p>We check the assumption that residuals are normally distributed in <a href="#fig-qq">Figure&nbsp;19</a>. Most of the points are in the shaded region. Row 1 of the dataset appears in the upper right corner, far away from the boundaries. A couple of other points are very close, but just outside of the boundary. Due to the robust nature of ANOVA, the mild violation of this assumption is not a concern.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(bf2_aov<span class="sc">$</span>residuals, <span class="at">id =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-qq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-qq-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;19: Checking normality of residuals</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="independent-residuals" class="level3">
<h3 class="anchored" data-anchor-id="independent-residuals">Independent Residuals</h3>
<p>The dataset we are analyzing does not include information about the order in which the data was collected. In fact, it may be possible there were multiple teams of researchers collecting the data simultaneously and there is no specific order. From what we know, there is no reason to think there is a potential order bias. Nevertheless, the order plot in <a href="#fig-order">Figure&nbsp;20</a> can be used to investigate trends in residuals by row number in the dataset. This plot does not show any patterns or trends. The assumption of independent residuals seems to be satisfied.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bf2_aov<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-order" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="bf2_files/figure-html/fig-order-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;20: Checking independent residuals assumption</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="assumptions-summary" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-summary">Assumptions Summary</h3>
<p>The assumptions appear to be met, meaning the p-values should be valid and reliable. However, since the F-test for toothbrush is such a close call, mild-moderate assumption violations may cause the p-value of the test to be slightly off. Even after attempting various transformations of the response variable, Plaque, the degree to which assumptions are met does not improve (in fact, in some cases it gets worse).</p>
<p>Rather than fuss about the whether F-test assumptions are met or not, you can recognize the F-test for Brush is close enough to merit further investigation. In this case, it is recommended to proceed with contrasts/pairwise tests of toothbrush type which do not require constant variance. (You should be aware of what assumption are required for those tests and be sure to check them).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(bf2_aov, <span class="at">which =</span> <span class="st">"Brush"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Plaque ~ Brush * Toothpaste, data = bf2)

$Brush
                             diff       lwr       upr     p adj
Oscillating-Manual     -3.1166667 -8.069047  1.835714 0.3089079
Sonic-Manual           -0.4183333 -5.370714  4.534047 0.9948323
Ultrasonic-Manual       2.2200000 -2.732381  7.172381 0.5864034
Sonic-Oscillating       2.6983333 -2.254047  7.650714 0.4280732
Ultrasonic-Oscillating  5.3366667  0.384286 10.289047 0.0324891
Ultrasonic-Sonic        2.6383333 -2.314047  7.590714 0.4469155</code></pre>
</div>
</div>
<p>In the above output results for all pairwise comparisons with Tukey’s HSD adjustment for multiple comparisons are displayed. Only the Ultrasonic-Oscillating comparison is significantly different, with a p-value of .03. Therefore, we can state that the ultrasonic brush performs significantly worse than the oscillating brush at plaque reduction.</p>
</section>
</section>
</section>
<section id="appendix" class="level1">
<h1>Appendix</h1>
<section id="notation-for-estimated-effects" class="level2">
<h2 class="anchored" data-anchor-id="notation-for-estimated-effects">Notation for Estimated Effects</h2>
<p>Here are symbolic representations for the estimated effects in the BF[2] model, as shown in <a href="#eq-bf2">Equation&nbsp;1</a>.</p>
<p><span class="math display">\[
\hat{\alpha}_i = \bar{y}_{i \cdot \cdot} - \bar{y}_{\cdots}
\]</span></p>
<p><span class="math display">\[
\hat{\beta}_j = \bar{y}_{\cdot j \cdot} - \bar{y}_{\cdots}
\]</span></p>
<p><span class="math display">\[
\begin{align}
\hat{\alpha}\hat{\beta}_{ij} &amp; = \bar{y}_{i j \cdot} - (\bar{y}_{\cdot \cdot \cdot} + \hat{\alpha}_i  + \hat{\beta}_j ) \\
&amp;= \bar{y}_{i j \cdot} - (\bar{y}_{\cdot \cdot \cdot} + (\bar{y}_{i \cdot \cdot} - \bar{y}_{\cdot \cdot \cdot})  + (\bar{y}_{\cdot j \cdot} - \bar{y}_{\cdot \cdot \cdot}) ) \\
&amp; = \bar{y}_{i j \cdot} - (\bar{y}_{i \cdot \cdot} + \bar{y}_{\cdot j \cdot} - \bar{y}_{\cdot \cdot \cdot})
\end{align}
\]</span></p>
</section>
<section id="unreplicated-or-single-observation-per-cell" class="level2">
<h2 class="anchored" data-anchor-id="unreplicated-or-single-observation-per-cell">Unreplicated or Single Observation per Cell</h2>
<p>What can be done in the case of an experiment where there is only one observation per factor level combination?</p>
<p>Under construction.</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>There are symbolic/mathematical representations of the factor effect formulas located in the appendix.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The values used in calculations here and throughout this page are rounded for a cleaner display. However, you should use unrounded values for these calculations. Rounded values and significant digits is the reason the arithmetic in some of these calculations appears off by one one-hundredth.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>You can explore behavior of the F distribution for various combinations of degrees of freedom using <a href="https://homepage.divms.uiowa.edu/~mbognar/applets/f.html">this applet</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>This is the formula used in Excel to obtain the p-values for brush, toothpaste, and brush:toothpaste interaction respectively:</p>
<ul>
<li><p>brush: <code>`=f.dist.rt(3.20054, 3, 16)</code></p></li>
<li><p>toothpaste: <code>=f.dist.rt(0.06871, 1, 16)</code></p></li>
<li><p>brush:toothpaste : <code>=f.dist.rt(.226924, 3, 16)</code></p></li>
</ul>
<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></li>
<li id="fn5"><p>This is the formula used in R to obtain the p-values for brush, toothpaste, and brush:toothpaste interaction respectively:</p>
<ul>
<li><p>brush: <code>1-pf(3.2005, 3, 16)</code></p></li>
<li><p>toothpaste: <code>1-pf(0.06871, 1, 16)</code></p></li>
<li><p>brush:toothpaste : <code>1-pf(0.2269, 3, 16)</code></p></li>
</ul>
<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>