<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Math326 Notebook - CB[1]</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Math326 Notebook</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-basics-of-design" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Basics of Design</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-basics-of-design">    
        <li>
    <a class="dropdown-item" href="./key_principles.html">
 <span class="dropdown-text">Key Principles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./research_objectives.html">
 <span class="dropdown-text">Research Objectives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./response_variable.html">
 <span class="dropdown-text">Response Variable</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./experimental_units.html">
 <span class="dropdown-text">Experimental Units</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sources_of_variances.html">
 <span class="dropdown-text">Sources of Variation - Factors and Conditions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./randomization.html">
 <span class="dropdown-text">Randomization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-specific-designs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Specific Designs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-specific-designs">    
        <li>
    <a class="dropdown-item" href="./BasicFactorial_intro.html">
 <span class="dropdown-text">Basic Factorial Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./BasicFactorial_quarto_boat.html">
 <span class="dropdown-text">BF[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bf2.html">
 <span class="dropdown-text">BF[2]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./BasicFactorial_quarto.html">
 <span class="dropdown-text">BF[3+]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./block_intro.html">
 <span class="dropdown-text">Blocking Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cb1.html">
 <span class="dropdown-text">CB[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Covariate.html">
 <span class="dropdown-text">Covariate Designs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NestedFactor.html">
 <span class="dropdown-text">Nested Factor (aka Split Plot/Repeated Measure) Designs</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-broad-topics" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Broad Topics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-broad-topics">    
        <li>
    <a class="dropdown-item" href="./factor_structure.html">
 <span class="dropdown-text">Factor Structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./effects_model.html">
 <span class="dropdown-text">Effects Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Anova_F-test.html">
 <span class="dropdown-text">ANOVA and the F-test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html">
 <span class="dropdown-text">Assumptions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./contrast.html">
 <span class="dropdown-text">Contrasts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./multiple_comparisons.html">
 <span class="dropdown-text">Multiple Comparisons</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unbalanced.html">
 <span class="dropdown-text">Unbalanced Datasets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Kruskal.html">
 <span class="dropdown-text">ZPower??</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./LogisticRegression.html">
 <span class="dropdown-text">ZRandom Factors??</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-instructions" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Instructions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-instructions">    
        <li>
    <a class="dropdown-item" href="./DescribeData.html">
 <span class="dropdown-text">Descriptive Summaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./diagnostics.html">
 <span class="dropdown-text">Model diagnostics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-datasets" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Datasets</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-datasets">    
        <li>
    <a class="dropdown-item" href="././Data/AnalysisRubric.html">
 <span class="dropdown-text">XYZ</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="././Data/StudentHousing.html">
 <span class="dropdown-text">yadda yadda</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#factor-structure" id="toc-factor-structure" class="nav-link" data-scroll-target="#factor-structure">Factor Structure</a></li>
  <li><a href="#hypothesis-and-model" id="toc-hypothesis-and-model" class="nav-link" data-scroll-target="#hypothesis-and-model">Hypothesis and Model</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  </ul></li>
  <li><a href="#design" id="toc-design" class="nav-link" data-scroll-target="#design">Design</a></li>
  <li><a href="#decomposition" id="toc-decomposition" class="nav-link" data-scroll-target="#decomposition">Decomposition</a>
  <ul class="collapse">
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of Freedom</a></li>
  <li><a href="#factor-effects" id="toc-factor-effects" class="nav-link" data-scroll-target="#factor-effects">Factor Effects</a>
  <ul class="collapse">
  <li><a href="#factor-level-means" id="toc-factor-level-means" class="nav-link" data-scroll-target="#factor-level-means">Factor Level Means</a></li>
  <li><a href="#factor-level-effects" id="toc-factor-level-effects" class="nav-link" data-scroll-target="#factor-level-effects">Factor Level Effects</a></li>
  </ul></li>
  <li><a href="#completing-the-anova-table" id="toc-completing-the-anova-table" class="nav-link" data-scroll-target="#completing-the-anova-table">Completing the ANOVA Table</a></li>
  </ul></li>
  <li><a href="#analysis-in-r" id="toc-analysis-in-r" class="nav-link" data-scroll-target="#analysis-in-r">Analysis in R</a>
  <ul class="collapse">
  <li><a href="#describe-the-data" id="toc-describe-the-data" class="nav-link" data-scroll-target="#describe-the-data">Describe the Data</a>
  <ul class="collapse">
  <li><a href="#numerical-summaries" id="toc-numerical-summaries" class="nav-link" data-scroll-target="#numerical-summaries">Numerical Summaries</a></li>
  <li><a href="#graphical-summaries" id="toc-graphical-summaries" class="nav-link" data-scroll-target="#graphical-summaries">Graphical Summaries</a></li>
  </ul></li>
  <li><a href="#create-the-model" id="toc-create-the-model" class="nav-link" data-scroll-target="#create-the-model">Create the Model</a></li>
  <li><a href="#check-assumptions" id="toc-check-assumptions" class="nav-link" data-scroll-target="#check-assumptions">Check Assumptions</a>
  <ul class="collapse">
  <li><a href="#constant-error-variance" id="toc-constant-error-variance" class="nav-link" data-scroll-target="#constant-error-variance">Constant Error Variance</a></li>
  <li><a href="#normally-distributed-error-term" id="toc-normally-distributed-error-term" class="nav-link" data-scroll-target="#normally-distributed-error-term">Normally Distributed Error Term</a></li>
  <li><a href="#independent-residuals" id="toc-independent-residuals" class="nav-link" data-scroll-target="#independent-residuals">Independent Residuals</a></li>
  <li><a href="#assumptions-summary" id="toc-assumptions-summary" class="nav-link" data-scroll-target="#assumptions-summary">Assumptions Summary</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CB[1]</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>
<section id="overview" class="level1 page-columns page-full">
<h1>Overview</h1>
<p>In a complete block design (CB[1]), there are two controlled factors: a treatment factor and a blocking factor. The study’s objective is usually to measure and/or test the treatment factor effects. The blocking factor is included to avoid confounding the treatment factor with the blocking factor and to reduce the variance of the error term.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a CB[1] design, there is only one observation per treatment per block, and thus an interaction effect cannot be estimated. In a CB[1], the treatment by block interaction is therefore assumed to be zero.</p>
</div>
</div>
<p>The toothbrush example can be used to illustrate this design. Imagine the toothbrush researchers are still in the planning stages of the experiment. Researchers want to pre-emptively address the argument that one toothbrush performs better (or worse) simply because the people who use that brush in the study are in some way better at brushing. There are a couple of things the researchers can do. They should of course provide training/education to each participant about the proper way to brush. This would help, but old brushing habits die hard, and skeptics can argue that behavior won’t change.</p>
<p>In addition to adjusting experimental protocols, the <em>design</em> of the experiment can be adjusted to address the concern. Specifically, the researchers can block on participant. The experiment would look like this:</p>
<ul>
<li><p>A person uses a particular brush for a set period.</p></li>
<li><p>At the end of the period, their plaque amount would be measured and their teeth cleaned</p></li>
<li><p>Then they would use a different brush for the same set amount of time.</p></li>
<li><p>The process would repeat until the person had used all 4 brushes.</p></li>
</ul>
<p>The order of the brush will be randomized for each person to remove any bias due to learning, fatigue, or gradual plaque build up.</p>
<section id="factor-structure" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-structure">Factor Structure</h2>
<p>The factor structure for a CB[1] design still has the two universal factors of the grand mean and residual error. There are also two structural factors: blocks and treatments.</p>
<div class="column-page">
<div id="fig-cb1_factor_structure" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/CB1_factor_structure.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Factor Structure for CB[1]</figcaption><p></p>
</figure>
</div>
</div>
<p>In this case, the blocks factor accounts for variation in participants, and the treatment is toothbrush type. There are 6 participants in the study (6 block factor levels). Each toothbrush type appears once in each block. There are 24 observations total, 1 observation for each combination of block and toothbrush.</p>
</section>
<section id="hypothesis-and-model" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="hypothesis-and-model">Hypothesis and Model</h2>
<p>Each factor (i.e.&nbsp;meaningful partition of the data) in <a href="#fig-cb1_factor_structure">Figure&nbsp;1</a> corresponds to a term on the right hand side of <a href="#eq-cb1">Equation&nbsp;1</a>:</p>
<p><span id="eq-cb1"><span class="math display">\[
y_{ij} = \mu + \alpha_i + \beta_j + \epsilon_{ij}
\tag{1}\]</span></span></p>
<p>Where</p>
<ul>
<li><p><span class="math inline">\(y_{ij}\)</span> is the observation that belongs to level <em>i</em> of <span class="math inline">\(\alpha\)</span> and level <em>j</em> of <span class="math inline">\(\beta\)</span>.</p></li>
<li><p><span class="math inline">\(\mu\)</span> is the grand mean of the entire dataset.</p></li>
<li><p><span class="math inline">\(\alpha\)</span> is the effect of participant, and <em>j</em> goes from 1 to 6 since there are 6 participants / blocks.</p></li>
<li><p><span class="math inline">\(\beta\)</span> is the effect of toothbrush, and <em>i</em> goes from 1 to 4 since there are 4 toothbrush types.</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> is the residual error term</p></li>
</ul>
<p>Note that since there is only one observation per factor level combination, there is not enough degrees of freedom to estimate an interaction effect.</p>
<p>The hypothesis of interest for a CB[1] study is about the treatment factor:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Block is a nuisance factor and not of particular interest. If you desired to test the Block factor as well, the null hypohtesis would be <span class="math display">\[ Ho: \alpha_i = 0 \text{ for all } i\]</span></p>
<p><span class="math display">\[H_a: \alpha_i \ne 0 \text{ for some }i\]</span></p>
</div></div><p><span class="math display">\[H_0: \beta_j = 0 \text{ for all }j\]</span></p>
<p><span class="math display">\[H_a: \beta_i \ne 0 \text{ for some }j\]</span></p>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>An ANOVA model may be used to analyze data from a CB[1] design if the following requirements are satisfied.</p>
<table class="table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Requirements</th>
<th>Method for Checking</th>
<th>What You Hope to See</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Constant variance across factor levels<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></td>
<td>Residual vs.&nbsp;Fitted Plot</td>
<td>No major disparity in vertical spread of point groupings</td>
</tr>
<tr class="even">
<td>Normally Distributed Residuals</td>
<td>Normal Q-Q plot</td>
<td>Straight line, majority of points in boundaries</td>
</tr>
<tr class="odd">
<td>Independent residuals</td>
<td>Order plot</td>
<td>No pattern/trend</td>
</tr>
<tr class="even">
<td></td>
<td>Familiarity with/critical thinking about the experiment</td>
<td>No potential source for bias</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="design" class="level1">
<h1>Design</h1>
<p>In a complete block design, each treatment is observed once in each block. Each block represents its own mini-replicate of the experiment. While treatment is purposefully varied to address the research question, blocks are a nuisance factor that we include in the design and analysis to more precisely estimate treatment effects.</p>
<p>Treatments are assigned completely at random within each block. Consider how this is done for the toothbrush example explained above in which we are blocking on participant. We can start by listing out each block and treatment. In this example, there are 24 observations, each observation represents a time slot in the study for a particular person, 6 participants x 4 time slots = 24 observations.</p>
<p>The design laid out in the format below is called “wider” format. It is helpful for humans to see it this way and fits in the way we have drawn our factor diagram (<a href="#fig-cb1_factor_structure">Figure&nbsp;1</a>)</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">ParticipantID</th>
<th style="text-align: center;">Period1</th>
<th style="text-align: center;">Period2</th>
<th style="text-align: center;">Period3</th>
<th style="text-align: center;">Period4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If we proceed with the experiment like this, all the participants will get the toothbrushes in the same order. Order and toothrbrush will be confounded: we won’t be able to tell if a toothbrush’s effect is due to the brush itself or due to where it falls in the sequence. We will therefore randomize the order of the brushes for each participant. We end up with this result:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">ParticipantID</th>
<th style="text-align: center;">Period1</th>
<th style="text-align: center;">Period2</th>
<th style="text-align: center;">Period3</th>
<th style="text-align: center;">Period4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">manual</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">manual</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">super sonic</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Having an idea of how to do this randomization in R can be helpful. R (and most softwares) will need the design laid out in “longer” form first as shown below (this is the unrandomized experiment):</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>ParticipantID <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">each =</span> <span class="dv">4</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Brush <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"manual"</span>, <span class="st">"oscillating"</span>, <span class="st">"sonic"</span>, <span class="st">"super sonic"</span>), <span class="at">times =</span> <span class="dv">6</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Order <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">times =</span> <span class="dv">6</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>longer <span class="ot">&lt;-</span> <span class="fu">tibble</span>(ParticipantID, Brush, Order)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(longer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><a href="javascript:showhide('unrandomized')"><span style="font-size:8pt;">click to show/hide data</span></a></p>
<div id="unrandomized">
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">ParticipantID</th>
<th style="text-align: center;">Brush</th>
<th style="text-align: center;">Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now randomize the order of the brushes for each participant. The resulting randomization matches what was shown in wider format above, but is now in longer format.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(ParticipantID, Brush) <span class="sc">%&gt;%</span> <span class="co">#This puts the two columns together</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ParticipantID) <span class="sc">%&gt;%</span> <span class="co">#randomize within each participant</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span> <span class="co">#shuffle the Brushes</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">Order =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">times =</span> <span class="dv">6</span>)) <span class="co">#put the order column back on</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><a href="javascript:showhide('random_long')"><span style="font-size:8pt;">click to show/hide data</span></a></p>
<div id="random_long">
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">ParticipantID</th>
<th style="text-align: center;">Brush</th>
<th style="text-align: center;">Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">manual</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">oscillating</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">sonic</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">super sonic</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="decomposition" class="level1 page-columns page-full">
<h1>Decomposition</h1>
<p>In the decomposition section we do the analysis of variance by hand. In other words, we decompose the variability in the response values and attribute that variability to the various factors in the experiment.</p>
<p>To do a decomposition, we will represent the data in “wider” format. This is easier to see, even though most of the time the computer will want it in “longer” format. We will also organize the data <em>without</em> regard to the order in which it was actually collected. In other words, even though the order of brushes was randomized, the data will be organized/displayed in the factor structure, without an attempt to represent the actual order of brushes.</p>
<p><a href="#fig-cb1_factors_and_model">Figure&nbsp;2</a> gives the factor structure of the complete block design for the toothbrush study, and the accompanying mathematical model.</p>
<div class="column-page">
<div id="fig-cb1_factors_and_model" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/CB1_factors_and_model.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Factor Structure and model for the CB[1] Toothbrush Study</figcaption><p></p>
</figure>
</div>
</div>
<p>Where</p>
<ul>
<li><p>The <strong>observed values</strong> <span class="math inline">\(y_{ij}\)</span> on the left of the equals sign show that there are 24 observations of plaque coverage, one for each unique combination of the levels of toothbrush and Block.</p></li>
<li><p>The <strong>grand mean factor</strong> (<span class="math inline">\(\mu\)</span>) is the grand mean of the entire dataset. The single large cell indicates that there is only one grand mean and it is part of every observation.</p></li>
<li><p>The <strong>block factor</strong> has one partition per row. All the observations in a row come from the same participant. A participant is a block in this case and a participant’s effect is represented in the model by <span class="math inline">\(\alpha_i\)</span>, where <em>i</em> goes from 1 to 6 since there are 6 participants/blocks.</p></li>
<li><p>The <strong>treatment factor</strong> involves the four types of brushes, represented by the four vertically long cells. Each factor level may have a distinct mean and effect. The factor level effect is represented in the model by <span class="math inline">\(\beta_j\)</span>, where <em>j</em> goes from 1 to 4 since there are 4 types.</p></li>
<li><p>The <strong>residual error</strong> represents the difference between the observed value and the predicted value. The predicted value, also called the fitted value, is the sum of the grand mean, treatment effect, and block effect for a given individual. Each cell represents a distinct value for the residual error and is written as <span class="math inline">\(\epsilon_{ij}\)</span>.</p></li>
</ul>
<p>A CB[1] design has four <em>analysis</em> factors: the grand mean, blocks, treatment, and residual. The effects of these factors can be summed together to find each observed value. Notice there is no interaction factor. If we cross treatment factor and block to create an interaction, we end up with the exact same partitions as we have for the residual factor. Thus, we can use the data to estimate an interaction or to estimate residual errors, but not both. We need the residual error to conduct our hypothesis test of the treatment, and therefore this model operates under the assumption that there is no interaction between the treatment and blocking factors.</p>
<section id="degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h2>
<p>We can use our understanding of <a href="./factor_structure.html">inside vs.&nbsp;outside factors</a> to determine the degrees of freedom (df) for the grand mean, treatment factor, blocks, and residual errors. We start with 24 observations - or pieces of information. In other words, we have 24 degrees of freedom that need to be allocated to the factors.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
General Rule for Degrees of Freedom
</div>
</div>
<div class="callout-body-container callout-body">
<p>Degrees of Freedom for a factor = Total levels of a factor minus the sum of the degrees of freedom of all outside factors</p>
</div>
</div>
<p>An alternative way to find degrees of freedom is to count the number of unique pieces of information in a factor.</p>
<p>The&nbsp;<strong>grand mean</strong>&nbsp;has one level and there are no factors outside of grand mean. Therefore, its degrees of freedom equals one. This will always be the case.</p>
<p>In this case there are two controlled factors: treatment factor (toothbrush) and blocking factor (participant). For&nbsp;<strong>treatment factor</strong>, there are four levels of the factor (shown by the four vertically long cells for treatment factor in&nbsp;<a href="#fig-cb1_factors_and_model">Figure&nbsp;2</a>). Since grand mean is the only factor outside of toothbrush, take the number of levels for toothbrush (4) and subtract the degrees of freedom for grand mean (1), which yields 4-1 =&nbsp;<strong>3 degrees of freedom</strong>&nbsp;for toothbrush.</p>
<p>We could just as easily have used the other approach to finding the degrees of freedom: counting the unique pieces of information the toothbrush effects really contain. Since all observations from the same toothbrush will have the same effect, we only need to know 4 pieces of information: the effect of each toothbrush. But, because we know that the effects must all sum to zero, only 3 of the effects are free to vary and the 4th one is constrained to be whatever value will satisfy this mathematical condition. Thus, the degrees of freedom are 3. As soon as we know effect for 3 factor levels of toothbrush, we can fill in the toothbrush effects for all the observations.</p>
<p>Though we don’t plan to test for the <strong>Block factor</strong>, we walk through the steps here to have a complete accounting of the degrees of freedom and variance. To calculate Block degrees of freedom, a similar approach of counting “free numbers” can be used. Namely, after estimating a participant’s effect on plaque, I can fill that effect in for all the observations pertaining to that participant’s partition in the block factor. Therefore, there is just one unique value in each row, meaning one degree of freedom per participant. However, since the sum of effects across participant must equal zero, the degrees of freedom will be equal to one less the number of participants.</p>
<p>Alternatively, degrees of freedom can be calculated using the general rule. There are 6 levels for participant Blocks, and grand mean is the only outside factor. Since grand mean has 1 degree of freedom, you get&nbsp;6−1=5&nbsp;degree of freedom for blocks.</p>
<p>Finally, the <strong>residual degrees of freedom</strong> can be found using the general rule. Since the residual error factor is inside of all other factors, this is the same as finding how many degrees of freedom are leftover after calculating degrees of freedom for all other factors. In this example, there were 24 observations total, so we subtract the degrees of freedom for the other factors from 24. This returns&nbsp;24−(1+3+5)=15&nbsp;degrees of freedom for residuals.</p>
</section>
<section id="factor-effects" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-effects">Factor Effects</h2>
<p>We can use our understanding of <a href="./factor_structure.html">inside vs.&nbsp;outside factors</a> to estimate the effect size of the grand mean, treatment factor, blocks, and residual errors. Recall the general rule for estimating effect size of a factor:</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
General Rule for Effect Size
</div>
</div>
<div class="callout-body-container callout-body">
<p>Effect size = Factor level mean - sum of the effects of all outside factors</p>
</div>
</div>
<p>We start by calculating factor level means.</p>
<section id="factor-level-means" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="factor-level-means">Factor Level Means</h3>
<p><a href="#fig-CB1-data-partition">Figure&nbsp;3</a> shows our data set with partition lines for structural factors in place. We will proceed to calculate the factor level means for each factor.</p>
<div id="fig-CB1-data-partition" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/CB1-data-partition.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Partitioned CB[1] Toothbrush Data</figcaption><p></p>
</figure>
</div>
<p>The grand mean is the mean of all the observations</p>
<p><span class="math display">\[
\hat{\mu} = \bar{y}_{\cdot\cdot} = \frac{19.12 + 18.56 + 25.58 + 24.39 + 24.21 + ... + 23.42}{24} = 22.76
\]</span></p>
<p>Now find the mean for each level of toothbrush type.</p>
<p><span class="math display">\[
\bar{y}_\text{manual} = \bar{y}_{\cdot 1} = \frac{19.12 + 24.21 + 26.88 + 21.6 + 23.4 + 23.35}{6} = 23.10
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{oscillating} = \bar{y}_{\cdot 2} = \frac{18.56 + 20.00 + 19.87 + 22.09 + 17.62 + 21.72}{6} = 19.98
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{sonic} = \bar{y}_{\cdot 3} = \frac{25.58 + 23.31 + 18.99 + 23.09 + 23.81 + 21.27}{6} = 22.68
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{ultrasonic} = \bar{y}_{\cdot 4} = \frac{24.39 + 21.45 + 32.74 + 24.21 + 25.67 + 23.42}{6} = 25.31
\]</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Note the effects for grand mean and toothbrush are the same as they are in the BF[2].</p>
</div></div><p>Now find the mean for each level of block (only the first two blocks are illustrated here).</p>
<p><span id="eq-block1_mean"><span class="math display">\[
\bar{y}_\text{Block1} = \bar{y}_{1\cdot} = \frac{19.12 + 18.56 + 25.58 + 24.39}{4} = 21.91
\tag{2}\]</span></span></p>
<p><span class="math display">\[
\bar{y}_\text{Block2} = \bar{y}_{2\cdot} = \frac{24.21 + 20.00 + 23.31 + 21.45}{4} = 22.24
\]</span></p>
<p>The mean for each residual error factor level is the observed value itself since there is just 1 observation per level. Therefore, there are no calculations to show.</p>
<p><a href="#fig-CB1_means">Figure&nbsp;4</a> displays the factor levels means associated with each observation.</p>
<div class="column-page">
<div id="fig-CB1_means" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/CB1_means.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Factor Level Means</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="factor-level-effects" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="factor-level-effects">Factor Level Effects</h3>
<p>Now that we have calculated means for the levels of each factor, we can calculate the effects of the factor levels<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>There is only one level of <strong>grand mean</strong> and there are no outside factors. Therefore, the effect due to grand mean is 22.76 (equivalent to its mean) and this effect is applied to all 24 observations.</p>
<p>The <strong>toothbrush factor</strong> has four levels: one for each brush type. We will use the general rule for calculating factor level effects. To calculate the effect of a toothbrush, take the toothbrush mean and subtract the grand mean (the only factor outside of toothbrush) from it. For the manual brush, this looks like:</p>
<p><span class="math display">\[ 23.09 - 22.76 = 0.33 \]</span></p>
<p>Using the manual brush has the effect of increasing a person’s plaque area percentage by 0.33 percentage points on average compared to the grand mean. In a similar way you can find the effect for the oscillating brush: <span class="math inline">\(19.98−22.76=−2.79\)</span>. This means the amount of plaque decreased by 2.79 on average with this brush compared to the grand mean. For a sonic toothbrush, the effect is <span class="math inline">\(22.68−22.76=−0.09\)</span>. For an ultrasonic brush the effect is <span class="math inline">\(25.31−22.76=2.55\)</span>.</p>
<p>Calculating the effects for the <strong>block factor</strong> in the experiment follows a similar pattern and also uses the general rule for calculating effect sizes. Block is not outside or inside of toothbrush, but grand mean is outside of block. To calculate the effect an of individual participant (i.e.&nbsp;block), take the participant’s mean across all 4 treatments (see <a href="#eq-block1_mean">Equation&nbsp;2</a> as an example) and subtract the grand mean from it:</p>
<p><span class="math display">\[ 21.91 - 22.76 = -0.85\]</span></p>
<p>A similar calculation is done to find the estimated effect for participant 2 (i.e.&nbsp;block 2):</p>
<p><span class="math display">\[ 22.24 - 22.76 = -0.52\]</span></p>
<p>Similar calculations are performed for the remaining four blocks (i.e.&nbsp;participants).</p>
<p>You can think of the last term in the model as residual effects, but we usually refer to them simply as residuals. Residual means “left over” or “remaining”. After adding all the other effects together, the residual is the remaining effect, or deviation, needed to arrive at the observed value.</p>
<p>More simply, the residual is the actual observed value minus the predicted value.</p>
<p>The observed plaque coverage for Participant 1 using the manual brush is 19.12. The sum of the other factor effect represents the predicted value for this factor level combination:</p>
<p><span class="math display">\[
\begin{align}
\hat{y}_{11} &amp;= \hat{\mu} + \hat{\alpha}_1 + \hat{\beta}_1 \\
22.24 &amp;= 22.76 + \text{-}0.85 + 0.33
\end{align}
\]</span></p>
<p>The residual then, is</p>
<p><span class="math display">\[
\begin{align*}
e_{11} &amp;= y_{11} - \hat{y}_{11} \\
&amp;= 19.12 - 22.24 \\
&amp;= -3.12
\end{align*}
\]</span></p>
<p>The residual can be interpreted to mean that this participant’s plaque measurement was 3.12 percentage points lower than we would have predicted.</p>
<p>A similar calculation is done to find the residual for participant 1 with the oscillating brush. Here we condense a couple of the steps:</p>
<p><span class="math display">\[
\begin{align}
e_{ij} &amp;= y_{12} - \hat{y}_{12} \\
&amp;= y_{12} - (\hat{\mu} + \hat{\alpha}_1 + \hat{\beta}_2) \\
&amp;= 18.56 - (22.76 + \text{-}0.85 + \text{-}2.79) \\
&amp;= 18.56 - 19.12 \\
&amp;= -0.56
\end{align}
\]</span></p>
<p>After using the oscillating toothbrush, Participant 1’s percent of teeth surface area with plaque is 0.56 percentage points lower than the model predicts.</p>
<p>We perform these calculations for every observation. <a href="#fig-CB1_effects">Figure&nbsp;5</a> shows the effects that make up each observation<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<div class="column-page">
<div id="fig-CB1_effects" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/CB1_effects.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Factor Level Effects</figcaption><p></p>
</figure>
</div>
</div>
</section>
</section>
<section id="completing-the-anova-table" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="completing-the-anova-table">Completing the ANOVA Table</h2>
<p>Now that we have calculated degrees of freedom and effects for each factor, we can calculate the remaining pieces of the ANOVA table: <strong>Sum of Squares (SS), Mean Squares (MS), F-statistic and p-value</strong>. A completed ANOVA summary table contains the information we need for a hypothesis test of the treatment effect.</p>
<p>In an ANOVA table, each factor and their associated degrees of freedom are listed on the left. Note: the total degrees of freedom are the total number of observations.</p>
<div class="cell">
<div class="cell-output-display">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table">
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:left;"> SS </th>
   <th style="text-align:left;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Participant </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Brush </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>To get the <strong>sum of squares (SS)</strong> of a factor, the effects of the factor must be squared, and then summed. <a href="#fig-CB1_effects">Figure&nbsp;5</a> shows the effects, while <a href="#fig-CB_SS">Figure&nbsp;6</a> shows the squared effects.</p>
<div class="column-page">
<div id="fig-CB_SS" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/CB_SS.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Squared Effects</figcaption><p></p>
</figure>
</div>
</div>
<p>The total sum of squares is obtained by summing the squared observations as shown in <a href="#eq-ss_total">Equation&nbsp;3</a> . This represents the total variability in the dataset that will then be allocated or partitioned to the various factors, starting with the grand mean.</p>
<p><span id="eq-ss_total"><span class="math display">\[
SS_\text{total}= 365.6 + 344.5 + 654.3 + ... + 452.4 + 548.2 = 12,674.30
\tag{3}\]</span></span></p>
<p>For <strong>grand mean</strong>, the squared effect of 518.2 is listed 24 times, once for each observation. Summing the squared effects gets:</p>
<p><span class="math display">\[
SS_\text{Grand Mean}= 518.2 * 24 = 12,437.43
\]</span></p>
<p>Similarly, we get the sum of squares for toothbrush, block, and residuals.</p>
<p><span class="math display">\[
\begin{align}
SS_\text{Participant} &amp;= 4*0.73 + 4*0.27 + ... + 4*0.11 = 18.27 \\
\\
SS_\text{Brush} &amp;= 6 * 0.11 + 6 * 7.77 + 6*0.01 + 6*6.5 = 86.31 \\
\\
SS_\text{Residual} &amp;= 9.74 + 0.32 + 14.12 + 0.01 + 2.69 + ... + 2.46 = 132.29
\end{align}
\]</span></p>
<p>Putting this information into the ANOVA table gets us the result shown in <a href="#tbl-ss_anova">Table&nbsp;1</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ss_anova" class="anchored">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table"><caption>Table&nbsp;1:  Sums of Squares </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:left;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 12437.43 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Participant </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 18.27 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Brush </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 86.31 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 132.29 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 12674.30 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To calculate a mean square (MS), simply divide a factor’s sum of squares by its degrees of freedom. The mean square calculations are:</p>
<p><span class="math display">\[
MS_\text{Grand Mean} = \frac{SS_\text{Grand Mean}}{df_\text{Grand Mean}} = \frac{12437.43}{1} = 12437.43
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Participant} = \frac{SS_\text{Participant}}{df_\text{Participant}} = \frac{18.27}{5} = 3.654
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Brush} = \frac{SS_\text{Brush}}{df_\text{Brush}} = \frac{86.31}{3} = 28.77
\]</span></p>
<p><br></p>
<p><span class="math display">\[
MS_\text{Residual Error} = \frac{SS_\text{Residual Error}}{df_\text{Residual Error}} = \frac{132.29}{15} = 8.82
\]</span></p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ms_anova" class="anchored">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table"><caption>Table&nbsp;2:  Mean Squares </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:right;"> MS </th>
   <th style="text-align:left;"> Fvalue </th>
   <th style="text-align:left;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 12437.43 </td>
   <td style="text-align:right;"> 12437.43 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Participant </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 18.27 </td>
   <td style="text-align:right;"> 3.65 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Brush </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 86.31 </td>
   <td style="text-align:right;"> 28.77 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 132.29 </td>
   <td style="text-align:right;"> 8.82 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 12674.30 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>For the structural factors in the design there are a set of hypothesis we can test using the <strong>F statistic</strong>. Specifically, we will want to test whether toothbrush type has an effect on plaque coverage.</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Danger
</div>
</div>
<div class="callout-body-container callout-body">
<p>We may or may not be interested in testing Block. Because Block is usually a nuisance factor, testing its effect is not a priority. On the other hand, curiosity about whether the blocks were a significant source of variation may help us plan future experiments and improve the current analysis. In fact, if Block is not significant, we may consider removing it from the model so that the Residual factor has more degrees of freedom - which may result in a lower mean squared error. A lower mean squared increases the ability to detect significance of the treatment factor.</p>
</div>
</div>
<p>We will proceed with a test of the toothbrush type, represented as <span class="math inline">\(\beta\)</span> in <a href="#eq-cb1">Equation&nbsp;1</a>.</p>
<p><span class="math display">\[H_0: \beta_j = 0 \text{ for all }j\]</span></p>
<p><span class="math display">\[H_a: \beta_j \ne 0 \text{ for some }j\]</span></p>
<p>To test the hypothesis, we need to compare the mean square (MS) for toothbrush to the mean square for residual error (abbreviated as MSE). This ratio of variances is called an F statistic. The F statistic calculation is</p>
<p><span class="math display">\[
F_\text{Brush} = \frac{MS_\text{Brush}}{MS_\text{Error}} = \frac{28.77}{8.82} = 3.26
\]</span></p>
<p>An F distribution is defined by two parameters: a numerator degrees of freedom and a denominator degrees of freedom. The denominator in the F statistic calculation was the mean squared error, which has a degrees of freedom of 15. The numerator degrees of freedom is the degrees of freedom for toothbrush.</p>
<p>In practice, statistical software computes all the components of the ANOVA table, including the p-value. To complete the decomposition of variance in a manual way, the p-value is calculated in R using the <code>pf()</code> function.</p>
<p><code>1 - pf(test statistic, df of Treatment, df of Residual error)</code></p>
<p>In this example, for toothbrush we get a p-value of:</p>
<p><code>1 - pf(3.26, 3, 15) = 0.051</code></p>
<p>The completed ANOVA table for this CB[1] toothbrush study, blocked on participant is shown below:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-complete_anova" class="anchored">

<table style="width:65%; margin-left: auto; margin-right: auto;" class="table"><caption>Table&nbsp;3:  Toothbrush F Test ANOVA Table </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Source </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> SS </th>
   <th style="text-align:right;"> MS </th>
   <th style="text-align:right;"> Fvalue </th>
   <th style="text-align:right;"> pvalue </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Grand Mean </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 12437.43 </td>
   <td style="text-align:right;"> 12437.43 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Participant </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 18.27 </td>
   <td style="text-align:right;"> 3.65 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Brush </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 86.31 </td>
   <td style="text-align:right;"> 28.77 </td>
   <td style="text-align:right;"> 3.26 </td>
   <td style="text-align:right;"> 0.051 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residual Error </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 132.29 </td>
   <td style="text-align:right;"> 8.82 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 12674.30 </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
   <td style="text-align:right;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The p-value for brush indicates the effects of brush are marginally significant. When (in)significance is borderline, rather than making bold statements based on a small amount of (in)significance, it is helpful to dig a little deeper. Consider things like sample size, effect size (practical significance), outliers, and how closely assumptions are met. After weighing those considerations carefully, take a stance and state your belief about the role of the factor on the response. Explain your rationale, then keep an open mind and stay curious.</p>
<p>In this case, the biggest difference in means exists between Oscillating and Ultrasonic brushes. The presence of an outlier for the Ultrasonic brush gives birth to additional questions and skepticism. Given the small sample sizes and the outlier, I would recommend gathering more evidence before making major decisions.</p>
</section>
</section>
<section id="analysis-in-r" class="level1 page-columns page-full">
<h1>Analysis in R</h1>
<p>We will illustrate the R code unique to a CB[1] analysis while continuing to use the toothbrush and participant blocking example that has been used throughout this page.</p>
<section id="describe-the-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="describe-the-data">Describe the Data</h2>
<p>When working with a dataset the first thing to do is get to know your data through numerical and graphical summaries. Interactive code and additional explanations of numerical summaries and plots in R are found at <a href="DescribeData.html">R Instructions-&gt;Descriptive Summaries</a> section of the book.</p>
<section id="numerical-summaries" class="level3">
<h3 class="anchored" data-anchor-id="numerical-summaries">Numerical Summaries</h3>
<p>After loading required packages, we will read in the data and calculate summary statistics for each factor level separately.</p>
<div class="cell">

</div>
<div class="cell" data-cap="Read in Data">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cb1 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/toothpaste_CB1.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ParticipantID =</span> <span class="fu">as.factor</span>(PersonID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of Brush</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Plaque<span class="sc">~</span>Brush, <span class="at">data =</span> cb1) <span class="sc">|&gt;</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of Participant</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Plaque<span class="sc">~</span>ParticipantID, <span class="at">data =</span> cb1) <span class="sc">|&gt;</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-main_effects_numbers" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p>Table&nbsp;4: Numerical Summary for Each Factor</p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-main_effects_numbers-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-main_effects_numbers" style="flex-basis: 100.0%;justify-content: center;">

<table class="table" style="margin-left: auto; margin-right: auto;"><caption>(a) Brush </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Brush </th>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> Q1 </th>
   <th style="text-align:right;"> median </th>
   <th style="text-align:right;"> Q3 </th>
   <th style="text-align:right;"> max </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> missing </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Manual </td>
   <td style="text-align:right;"> 19.12 </td>
   <td style="text-align:right;"> 22.04 </td>
   <td style="text-align:right;"> 23.38 </td>
   <td style="text-align:right;"> 24.01 </td>
   <td style="text-align:right;"> 26.88 </td>
   <td style="text-align:right;"> 23.09 </td>
   <td style="text-align:right;"> 2.60 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Oscillating </td>
   <td style="text-align:right;"> 17.62 </td>
   <td style="text-align:right;"> 18.89 </td>
   <td style="text-align:right;"> 19.94 </td>
   <td style="text-align:right;"> 21.29 </td>
   <td style="text-align:right;"> 22.09 </td>
   <td style="text-align:right;"> 19.98 </td>
   <td style="text-align:right;"> 1.74 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sonic </td>
   <td style="text-align:right;"> 18.99 </td>
   <td style="text-align:right;"> 21.73 </td>
   <td style="text-align:right;"> 23.20 </td>
   <td style="text-align:right;"> 23.68 </td>
   <td style="text-align:right;"> 25.58 </td>
   <td style="text-align:right;"> 22.67 </td>
   <td style="text-align:right;"> 2.27 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Ultrasonic </td>
   <td style="text-align:right;"> 21.45 </td>
   <td style="text-align:right;"> 23.62 </td>
   <td style="text-align:right;"> 24.30 </td>
   <td style="text-align:right;"> 25.35 </td>
   <td style="text-align:right;"> 32.74 </td>
   <td style="text-align:right;"> 25.31 </td>
   <td style="text-align:right;"> 3.90 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-main_effects_numbers-2" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-main_effects_numbers" style="flex-basis: 100.0%;justify-content: center;">

<table class="table" style="margin-left: auto; margin-right: auto;"><caption>(b) Block: Participant </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> ParticipantID </th>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> Q1 </th>
   <th style="text-align:right;"> median </th>
   <th style="text-align:right;"> Q3 </th>
   <th style="text-align:right;"> max </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> missing </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:right;"> 18.56 </td>
   <td style="text-align:right;"> 18.98 </td>
   <td style="text-align:right;"> 21.76 </td>
   <td style="text-align:right;"> 24.69 </td>
   <td style="text-align:right;"> 25.58 </td>
   <td style="text-align:right;"> 21.91 </td>
   <td style="text-align:right;"> 3.59 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:right;"> 20.00 </td>
   <td style="text-align:right;"> 21.09 </td>
   <td style="text-align:right;"> 22.38 </td>
   <td style="text-align:right;"> 23.53 </td>
   <td style="text-align:right;"> 24.21 </td>
   <td style="text-align:right;"> 22.24 </td>
   <td style="text-align:right;"> 1.89 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:right;"> 18.99 </td>
   <td style="text-align:right;"> 19.65 </td>
   <td style="text-align:right;"> 23.38 </td>
   <td style="text-align:right;"> 28.34 </td>
   <td style="text-align:right;"> 32.74 </td>
   <td style="text-align:right;"> 24.62 </td>
   <td style="text-align:right;"> 6.46 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:right;"> 21.60 </td>
   <td style="text-align:right;"> 21.97 </td>
   <td style="text-align:right;"> 22.59 </td>
   <td style="text-align:right;"> 23.37 </td>
   <td style="text-align:right;"> 24.21 </td>
   <td style="text-align:right;"> 22.75 </td>
   <td style="text-align:right;"> 1.16 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:right;"> 17.62 </td>
   <td style="text-align:right;"> 21.95 </td>
   <td style="text-align:right;"> 23.60 </td>
   <td style="text-align:right;"> 24.27 </td>
   <td style="text-align:right;"> 25.67 </td>
   <td style="text-align:right;"> 22.62 </td>
   <td style="text-align:right;"> 3.48 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:right;"> 21.27 </td>
   <td style="text-align:right;"> 21.61 </td>
   <td style="text-align:right;"> 22.54 </td>
   <td style="text-align:right;"> 23.37 </td>
   <td style="text-align:right;"> 23.42 </td>
   <td style="text-align:right;"> 22.44 </td>
   <td style="text-align:right;"> 1.11 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>The Ultrasonic brush has the highest mean plaque amount, while Oscillating brush has the lowest.</p>
<p>With the exception of Participant 3, all the participants mean plaque values are very similar. The standard deviation for Participant 3 is also higher than all the others.</p>
</section>
<section id="graphical-summaries" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="graphical-summaries">Graphical Summaries</h3>
<p>You could also gain insight about your data by investigating the response by cutting the data by each factor separately, as shown in <a href="#fig-graphical_summary">Figure&nbsp;7</a>. The plot reinforces what was seen in the numerical summary. The mean plaque for each person is roughly similar, Block factor does not look to be statistically significant. There could be some significant variation in plaque due to toothbrush.</p>
<div id="fig-graphical_summary" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<div class="page-columns page-full">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot</span>(Plaque <span class="sc">~</span>Brush, <span class="at">data =</span> cb1, <span class="at">main =</span> <span class="st">"% of Teeth Surface Area Covered by Plaque"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot</span>(Plaque <span class="sc">~</span>ParticipantID, <span class="at">data =</span> cb1, <span class="at">main =</span> <span class="st">"% of Teeth Surface Area Covered by Plaque"</span>, <span class="at">xlab =</span> <span class="st">"Participant"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell column-page-inset quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="cb1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="cb1_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</div>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;7: Graphical Summaries for Controlled Factors</figcaption><p></p>
</figure>
</div>
<p>To reveal an example of combining the 2 plots into one, <a href="javascript:showhide('uniquename')"><strong>click here</strong></a></p>
<!-- <a href="javascript:showhide('textplot')">[click this link]{style="font-size:8pt;"}</a> -->
<div id="uniquename" style="display:none;">
<div id="textplot">
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> cb1, <span class="fu">aes</span>(<span class="at">x =</span> ParticipantID, <span class="at">y =</span> Plaque, <span class="at">color =</span> Brush)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Brush)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">type =</span> <span class="st">"qual"</span>, <span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Participant"</span>, <span class="at">y =</span> <span class="st">"Plaque Coverage (%)"</span>, <span class="at">title =</span> <span class="st">"% of Teeth Surface Area Covered by Plaque"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="cb1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Here it is easy to see that Oscillating had the lowest, or nearly the lowest, amount of plaque left for every individual. For all but one person, Ultrasonic was the worst, or nearly the worst, performing brush. Manual tended to be high. Interestingly, Sonic was all over the place. Perhaps Sonic is more sensitive to a way someone brushes or to different types of plaque build up.</p>
</div>
</section>
</section>
<section id="create-the-model" class="level2">
<h2 class="anchored" data-anchor-id="create-the-model">Create the Model</h2>
<p>Create the model using the <code>aov()</code> function. To see results of the T-test, you can feed your model into a <code>summary()</code> or <code>anova()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>cb_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Y <span class="sc">~</span> block <span class="sc">+</span> treatment, <span class="at">data =</span> YourDataSet)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cb_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>cb_aov</code> is the user defined name in which the results of the aov() model are stored</li>
<li><code>Y</code> is the name of a numeric variable in your dataset which represents the quantitative response variable.</li>
<li><code>treatment</code> and <code>block</code> are names of qualitative variables in your dataset. They should have <code>class()</code> equal to factor or character. If that is not the case, use <code>factor(X)</code> inside the <code>aov(Y ~ factor(treatment)...)</code> command.</li>
<li><code>YourDataSet</code> is the name of your data set.</li>
</ul>
<p>The results using R code should match the results show in the Decomposition section in <a href="#tbl-complete_anova">Table&nbsp;3</a>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cb_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Plaque <span class="sc">~</span> ParticipantID <span class="sc">+</span> Brush, <span class="at">data=</span>cb1) <span class="co">#note the + instead of *</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cb_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)  
ParticipantID  5  18.27   3.653   0.414 0.8316  
Brush          3  86.31  28.769   3.262 0.0511 .
Residuals     15 132.29   8.820                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The marginal significance of toothbrush (p-value = 0.051) was discussed at the end of the the <a href="cb1.html#completing-the-anova-table">Decomposition</a> section of this page.</p>
<p>Though ParticipantID (the Block factor) was not the main purpose of our study, R gives us output for its hypothesis test anyway. We may be curious about it. Because the p-value for ParticipantID (p-value = 0.83) is high, we fail to reject the null hypothesis. There is insufficient evidence to say the variety in participants had an effect on plaque coverage<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>In order to trust these hypothesis test results we need to verify that the assumptions are met.</p>
</section>
<section id="check-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-assumptions">Check Assumptions</h2>
<p>For a more detailed explanation of the code, output, and theory behind these assumptions visit the <a href="./assumptions.html">Assumptions</a> page.</p>
<section id="constant-error-variance" class="level3">
<h3 class="anchored" data-anchor-id="constant-error-variance">Constant Error Variance</h3>
<p>There needs to be constant variance across the factor levels. To verify this assumption is met, check the residual plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cb_aov, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cb1_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>If the constant variance assumption is violated, the points in this graph will show a wedge or megaphone shape. In other words, the vertical spread of the points would noticeably increase/decrease as we moved along the x-axis. There does not appear to be a trend like that in this plot. Points 15 and 21, which are both on the right side of the plot, are farther away than the rest of the points. However, point 21 seems more like an outlier than a continuation of a trend. This assumption appears to be met</p>
</section>
<section id="normally-distributed-error-term" class="level3">
<h3 class="anchored" data-anchor-id="normally-distributed-error-term">Normally Distributed Error Term</h3>
<p>We check the assumption that residuals are normally distributed with a QQ plot. Since all the points in the plot below are in the shaded regions around the line, we conclude this assumption is met.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cb_aov, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cb1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="independent-residuals" class="level3">
<h3 class="anchored" data-anchor-id="independent-residuals">Independent Residuals</h3>
<p>The dataset we are analyzing does not include information about the order in which the data was collected. In fact, it may be there were multiple teams of researchers collecting the data simultaneously and there is no specific order. From what we know, there is no reason to think there is a potential order bias. Nevertheless, the order plot below can be used to investigate trends in residuals by row number in the dataset. This plot does not show any patterns or trends. The assumption of independent residuals seems to be satisfied.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cb_aov<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cb1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="assumptions-summary" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-summary">Assumptions Summary</h3>
<p>The assumptions all appear to be met, suggesting that an ANOVA model is appropriate to use in this example.</p>


</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Comparing the largest and smallest standard deviation tends to be too stringent for designs other than a BF[1]. In addition, there is only 1 observation for factor level combination and so no standard deviation can be computed. This is also the problem with applying Levene’s test.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The values used in calculations here and throughout this page are rounded for a cleaner display. However, you should use unrounded values for these calculations. Rounded values and significant digits is the reason the arithmetic in some of these calculations appears off by one one-hundredth.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The values used in calculations here and throughout this page are rounded for a cleaner display. However, you should use unrounded values for these calculations. Rounded values and significant digits is the reason the arithmetic in some of these calculations appears off in the hundreths place.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>In this case, because of its lack of significance, we could remove ParticipantID from the model. This would give more degrees of freedom to the Residuals factor, thereby reducing the MSE and enabling us to better detect significance in the treatment. In fact, treating the study as a BF[1] (i.e.&nbsp;ignoring blocks) returns a p-value of 0.0258 for Brush!<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>