<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Math326 Notebook - The SP/RM[1, 1] Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Math326 Notebook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-basics-of-design" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Basics of Design</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-basics-of-design">    
        <li>
    <a class="dropdown-item" href="./key_principles.html">
 <span class="dropdown-text">Key Principles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./research_objectives.html">
 <span class="dropdown-text">Research Objectives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./response_variable.html">
 <span class="dropdown-text">Response Variable</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./experimental_units.html">
 <span class="dropdown-text">Experimental Units</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sources_of_variances.html">
 <span class="dropdown-text">Sources of Variation - Factors and Conditions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./randomization.html">
 <span class="dropdown-text">Randomization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-specific-designs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Specific Designs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-specific-designs">    
        <li>
    <a class="dropdown-item" href="./BasicFactorial_intro.html">
 <span class="dropdown-text">Basic Factorial Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./BasicFactorial_quarto_boat.html">
 <span class="dropdown-text">BF[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bf2.html">
 <span class="dropdown-text">BF[2]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bf3.html">
 <span class="dropdown-text">BF[3+]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./block_intro.html">
 <span class="dropdown-text">Blocking Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cb1.html">
 <span class="dropdown-text">CB[1]</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ancova.html">
 <span class="dropdown-text">ANCOVA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./latin_square.html">
 <span class="dropdown-text">Latin Square</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nested_intro.html">
 <span class="dropdown-text">Nested Factor Designs Intro</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./split_plot.html">
 <span class="dropdown-text">SP/RM[1,1]</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-broad-topics" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Broad Topics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-broad-topics">    
        <li>
    <a class="dropdown-item" href="./factor_structure.html">
 <span class="dropdown-text">Factor Structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./effects_model.html">
 <span class="dropdown-text">Effects Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Anova_F-test.html">
 <span class="dropdown-text">ANOVA and the F-test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html">
 <span class="dropdown-text">Assumptions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./contrast.html">
 <span class="dropdown-text">Contrasts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./multiple_comparisons.html">
 <span class="dropdown-text">Multiple Comparisons</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unbalanced.html">
 <span class="dropdown-text">Unbalanced Datasets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./random_v_fixed.html">
 <span class="dropdown-text">Random Factors and EMS</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-instructions" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Instructions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-instructions">    
        <li>
    <a class="dropdown-item" href="./DescribeData.html">
 <span class="dropdown-text">Descriptive Summaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./diagnostics.html">
 <span class="dropdown-text">Model diagnostics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-datasets" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Datasets</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-datasets">    
        <li>
    <a class="dropdown-item" href="./data/data_for_class.zip">
 <span class="dropdown-text">Download Zip Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_for_class.html">
 <span class="dropdown-text">Data Page</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#motivating-example" id="toc-motivating-example" class="nav-link" data-scroll-target="#motivating-example">Motivating Example</a>
  <ul class="collapse">
  <li><a href="#adding-a-nested-factor" id="toc-adding-a-nested-factor" class="nav-link" data-scroll-target="#adding-a-nested-factor">Adding a Nested Factor</a></li>
  </ul></li>
  <li><a href="#factor-structure" id="toc-factor-structure" class="nav-link" data-scroll-target="#factor-structure">Factor Structure</a></li>
  <li><a href="#hypothesis-and-model" id="toc-hypothesis-and-model" class="nav-link" data-scroll-target="#hypothesis-and-model">Hypothesis and Model</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  </ul></li>
  <li><a href="#design" id="toc-design" class="nav-link" data-scroll-target="#design">Design</a></li>
  <li><a href="#decomposition" id="toc-decomposition" class="nav-link" data-scroll-target="#decomposition">Decomposition</a>
  <ul class="collapse">
  <li><a href="#factor-effects" id="toc-factor-effects" class="nav-link" data-scroll-target="#factor-effects">Factor Effects</a>
  <ul class="collapse">
  <li><a href="#factor-level-means" id="toc-factor-level-means" class="nav-link" data-scroll-target="#factor-level-means">Factor Level Means</a></li>
  <li><a href="#factor-level-means-1" id="toc-factor-level-means-1" class="nav-link" data-scroll-target="#factor-level-means-1">Factor Level Means</a></li>
  </ul></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of Freedom</a></li>
  <li><a href="#completing-the-anova-table" id="toc-completing-the-anova-table" class="nav-link" data-scroll-target="#completing-the-anova-table">Completing the ANOVA Table</a></li>
  </ul></li>
  <li><a href="#analysis-in-r" id="toc-analysis-in-r" class="nav-link" data-scroll-target="#analysis-in-r">Analysis in R</a>
  <ul class="collapse">
  <li><a href="#numerical-summaries" id="toc-numerical-summaries" class="nav-link" data-scroll-target="#numerical-summaries">Numerical Summaries</a></li>
  <li><a href="#graphical-summaries" id="toc-graphical-summaries" class="nav-link" data-scroll-target="#graphical-summaries">Graphical Summaries</a></li>
  <li><a href="#create-the-model" id="toc-create-the-model" class="nav-link" data-scroll-target="#create-the-model">Create the Model</a></li>
  <li><a href="#check-assumptions" id="toc-check-assumptions" class="nav-link" data-scroll-target="#check-assumptions">Check Assumptions</a>
  <ul class="collapse">
  <li><a href="#constant-error-variance" id="toc-constant-error-variance" class="nav-link" data-scroll-target="#constant-error-variance">Constant Error Variance</a></li>
  <li><a href="#normally-distributed-error-term" id="toc-normally-distributed-error-term" class="nav-link" data-scroll-target="#normally-distributed-error-term">Normally Distributed Error Term</a></li>
  <li><a href="#independent-residuals" id="toc-independent-residuals" class="nav-link" data-scroll-target="#independent-residuals">Independent Residuals</a></li>
  <li><a href="#assumptions-summary" id="toc-assumptions-summary" class="nav-link" data-scroll-target="#assumptions-summary">Assumptions Summary</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The SP/RM[1, 1] Design</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>
<section id="overview" class="level1 page-columns page-full">
<h1>Overview</h1>
<p>The designation SP/RM[1, 1] stands for a Split Plot, or Repeated Measures design with 1 factor (the <strong>between-block factor</strong>) applied to the larger experimental units (blocks), and 1 factor (the <strong>within-block factor)</strong> applied to smaller experimental units. The block factor is another important part of the model, but it is considered a nuisance factor and so does not show up specifically in the SP/RM[1, 1] designation.</p>
<section id="motivating-example" class="level2">
<h2 class="anchored" data-anchor-id="motivating-example">Motivating Example</h2>
<p>Consider an example from agriculture. Farmer John would like to compare yield for a specific variety of maize treated with 2 different fungicides: generic vs premium. Farmer John has 4 plots of land available for planting. He can assign a fungicide to each plot completely at random, see <a href="#fig-fung" class="quarto-xref">Figure&nbsp;1</a>.</p>
<div id="fig-fung" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fung-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/FarmerJohnBF1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="360">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fung-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Layout of Farmer John’s 4 Plots
</figcaption>
</figure>
</div>
<p>Farmer John may be interested in the variation of yield within each plot. Even if he takes multiple yield measurements within each plot and measures yield at each sample point, he still only has 2 replicates of each fungicide.</p>
<p>So far there is nothing new here and this can be analyzed as a BF[1]. Each plot is an experimental unit and is assigned one of the fungicides completely at random.</p>
<section id="adding-a-nested-factor" class="level3">
<h3 class="anchored" data-anchor-id="adding-a-nested-factor">Adding a Nested Factor</h3>
<p>Farmer John suspects that the impact of fungicide type is different for different varieties of maize. He wants to add 3 maize varieties to the experiment, but because of mechanical constraints he cannot completely randomize combinations of fungicide with maize variety. While maize variety can be applied to smaller areas within a plot, he can only apply the fungicide to an entire plot.</p>
<p>Nothing has changed for the fungicide treatment level. But it can be seen in <a href="#fig-fung-variety" class="quarto-xref">Figure&nbsp;2</a> we have a new level of experimental unit: sub-plots! Variety is assigned to sub-plots randomly within each plot. Variety is unreplicated inside of a single plot, but looking across plots we see variety replicated 4 times.</p>
<div id="fig-fung-variety" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fung-variety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/FarmerJohnsSplitPlotAnnotated.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="615">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fung-variety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Layout of Fungicide Assigned to Plots with Maize Variety Assigned to Subplots
</figcaption>
</figure>
</div>
<p>Because each plot belongs to only 1 level of fungicide, we say plot is <a href="./factor_structure.html#nested-factors">nested</a> within fungicide.</p>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Nesting occurs when each level of a factor appears with only 1 level of another factor.</strong> The block factor will always be nested inside of the between-block factor.</p>
<p><strong>Factor crossing occurs when all levels of one factor appear with each and every level of another factor.</strong> Variety is crossed with block because each variety appears in each block. Variety is also crossed with fungicide.</p>
<p>In more general terms, the within-block factor is crossed with the block factor and is also crossed with the between-block factor.</p>
</div>
</div>
</div>
</section>
</section>
<section id="factor-structure" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-structure">Factor Structure</h2>
<p><a href="#fig-sprm_factor_structure" class="quarto-xref">Figure&nbsp;3</a> shows the factor structure for Farmer John’s experiment. The partition lines for the <em>plot</em> factor are dashed to emphasize that the plots are nested in fungicide. You may also notice that the plot arrangement in <a href="#fig-sprm_factor_structure" class="quarto-xref">Figure&nbsp;3</a> is not quite like the arrangement in <a href="#fig-fung-variety" class="quarto-xref">Figure&nbsp;2</a>. Remember, the factor structure diagram represents how the <strong>data</strong> is arranged and partitioned and does not necessarily represent how the plots are positioned in the physical, real world.</p>
<div class="page-columns page-full">
<div id="fig-sprm_factor_structure" class="quarto-figure quarto-figure-left quarto-float anchored page-columns page-full" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-sprm_factor_structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="images/Split_Plot_Factor_Image.png" class="quarto-figure quarto-figure-left figure-img column-page" width="950" height="152">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sprm_factor_structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Factor Structure for Farmer John’s Experiment
</figcaption>
</figure>
</div>
</div>
<p><a href="#fig-sprm_structure_generic" class="quarto-xref">Figure&nbsp;4</a> shows a generic factor structure for a split plot / repeated measures design, without the context of the Farmer John example.</p>
<div class="page-columns page-full">
<div id="fig-sprm_structure_generic" class="quarto-figure quarto-figure-left quarto-float anchored page-columns page-full" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-sprm_structure_generic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="images/sprm_factor_structure_generic.PNG" class="quarto-figure quarto-figure-left figure-img column-page" width="950" height="152">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sprm_structure_generic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Factor Structure for Generic SP/RM[1,1] Design
</figcaption>
</figure>
</div>
</div>
<p>There are <strong>two levels of experimental units</strong>. Plot is the experimental unit for Fungicide, and sub-plot is the experimental unit for maize variety.</p>
<p>You can tell what the experimental unit is for a factor based on how/when the randomization takes place. The fungicide was randomized to plots, and maize variety was randomly assigned to sub-plots within a whole-plot.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Replication Inside of Blocks
</div>
</div>
<div class="callout-body-container callout-body">
<p>The factor structure diagrams above show examples of designs without replication inside of blocks. However, it is not uncommon to have replication within blocks. For example, Farmer John could have split each plot into 6 sub-plots, which would allow variety to be replicated twice in each plot. This poses no problem in the analysis, and in fact gives us more precision in our estimates.</p>
<p>Replication of the within-block factor inside of a block also allows the estimation of the block by within-block interaction (e.g.&nbsp;plot by variety interaction). Usually blocks are random factors, so this likely results in an interaction between a fixed and random factor. Analyzing this type of interaction requires some additional assumptions/decisions that are not discussed in this book. For that reason, we will continue to make the assumption the block by within-block interaction effect is zero and will keep our designs simple with no replication inside of blocks.</p>
</div>
</div>
</section>
<section id="hypothesis-and-model" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="hypothesis-and-model">Hypothesis and Model</h2>
<p>There is not a consensus on notation for a split-plot / repeated measures design with nested factors. Different textbooks will represent the models differently algebraically<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. The notation selected for this text book opts for the most simple approach to subscripts.</p>
<p>Each factor (i.e.&nbsp;meaningful partition of the data) in <a href="#fig-sprm_structure_generic" class="quarto-xref">Figure&nbsp;4</a> corresponds to a term on the right hand side of <a href="#eq-sprm" class="quarto-xref">Equation&nbsp;1</a>.</p>
<p><span id="eq-sprm"><span class="math display">\[
y_{ijk} = \mu + \alpha_i + \beta_{ij} + \gamma_k + (\alpha \gamma)_{ik} + \epsilon_{ijk}
\tag{1}\]</span></span></p>
<p>Where</p>
<ul>
<li><p><span class="math inline">\(y_{ijk}\)</span> is the observation that belongs to level <em>i</em> of <span class="math inline">\(\alpha\)</span>, level <em>j</em> of <span class="math inline">\(\beta\)</span>, and level <em>k</em> of <span class="math inline">\(\gamma\)</span>.</p></li>
<li><p><span class="math inline">\(\mu\)</span> is the grand mean of all yield data.</p></li>
<li><p><span class="math inline">\(\alpha_i\)</span> is the between-block effect (also called the whole plot effect). In the Farmer John example <em>i</em> goes from 1 to 2 because there are 2 levels of fungicide.</p></li>
<li><p><span class="math inline">\(\beta_{ij}\)</span> is the block effect. The double subscript <em>ij</em> is necessary because a block is nested inside of the between-block factor level. In the farm context, a subscript value of <em>12</em> refers to the second plot that received fungicide <strong>A</strong>; whereas a subscript of <em>22</em> refers to the second plot that received fungicide <strong>B</strong>. So, even though the value for <em>j</em> is two in both instances, the subscript refers to two completely different plots!</p></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p>Block is the experimental unit for the between-block factor and thus serves as the error term for the between-block factor.</p>
</div></div><ul>
<li><p><span class="math inline">\(\gamma_k\)</span> is the effect of the within-block factor. In the Farmer John example, <em>k</em> goes from 1 to 3 because there are 3 varieties of maize.</p></li>
<li><p><span class="math inline">\((\alpha \gamma)_{ik}\)</span> represents the interaction between fungicide and variety. More generically, it represents the interaction of the between-block factor and the within-block factor.</p></li>
<li><p><span class="math inline">\(\epsilon_{ijk}\)</span> is the residual error term and is used to test the within-block factor and the interaction.</p></li>
</ul>
<p>A hypothesis for the main effect of fungicide type:</p>
<p><span class="math display">\[H_0: \alpha_\text{i} = 0 \text{ for all } i\]</span></p>
<p><span class="math display">\[H_a: \alpha_\text{i} \ne 0 \text{ for some } i\]</span></p>
<p>A hypothesis for the main effect of variety:</p>
<p><span class="math display">\[H_0: \gamma_\text{k} = 0 \text{ for all } k\]</span></p>
<p><span class="math display">\[H_a: \gamma_\text{k} \ne 0 \text{ for some } k\]</span></p>
<p>A hypothesis for the interaction of fungicide and variety.</p>
<p><span class="math display">\[
H_0: (\alpha\gamma)_\text{ik} = 0 \text{ for all } ik
\]</span></p>
<p><span class="math display">\[
H_a: (\alpha\gamma)_\text{ik} \ne 0 \text{ for some } ik
\]</span></p>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>ANOVA tests are appropriate for a split-plot analysis if the following requirements are satisfied:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 36%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Requirements</th>
<th>Method for Checking</th>
<th>What You Hope to See</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Constant variance across factor levels</td>
<td>Residual vs.&nbsp;Fitted Plot</td>
<td>No major disparity in vertical spread of point groupings</td>
</tr>
<tr class="even">
<td>The residuals are normally distributed</td>
<td>Normal Q-Q plot</td>
<td>Straight line, majority of points in boundaries</td>
</tr>
<tr class="odd">
<td>Independent residuals</td>
<td>Order plot</td>
<td>No pattern/trend</td>
</tr>
<tr class="even">
<td></td>
<td>Familiarity with/critical thinking about the experiment</td>
<td>No potential source for bias</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="design" class="level1">
<h1>Design</h1>
<p>A Split-plot design is characterized by having 2 levels of experimental units. This typically occurs because of physical constraints limiting randomization of all treatment combinations equally.</p>
<p>Levels of the between-block factor are assigned to blocks completely at random (like a basic factorial design). The levels of the within-block factor are randomized to experimental units within the block (like a complete block design). Look no farther than the maize and fungicide study as an example. First, let’s take a look at the layout of the experiment before randomization in <a href="#tbl-unrandomized" class="quarto-xref">Table&nbsp;1</a>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a sequence from 1 to 4</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Whole-plot</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Fungicide <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">2</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a vector with each variety</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>subplot1 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"variety1"</span>, <span class="at">times =</span> <span class="dv">4</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>subplot2 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"variety2"</span>, <span class="at">times =</span> <span class="dv">4</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>subplot3 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"variety3"</span>, <span class="at">times =</span><span class="dv">4</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Combine the vectors of Subject ID's and controlled factor levels into one tibble/dataset</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>assignment_table <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="st">`</span><span class="at">Whole-plot</span><span class="st">`</span>, Fungicide, subplot1, subplot2, subplot3)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#print the table, pander() makes it look nice</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(assignment_table) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-unrandomized" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-unrandomized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Unrandomized SP/RM[1,1] in Wider Format
</figcaption>
<div aria-describedby="tbl-unrandomized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Whole-plot</th>
<th style="text-align: center;">Fungicide</th>
<th style="text-align: center;">subplot1</th>
<th style="text-align: center;">subplot2</th>
<th style="text-align: center;">subplot3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">variety3</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">variety3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">variety3</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">variety3</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The design in <a href="#tbl-unrandomized" class="quarto-xref">Table&nbsp;1</a> is displayed in “wider format”. It is easy to see and understand in “wider format”, but a bit more difficult to apply randomization (and maybe more difficult to record data). Eventually we need it in “longer format” so that R can work with it more easily. <a href="#tbl-long_randomized" class="quarto-xref">Table&nbsp;2</a> below was created “by hand” (i.e.&nbsp;without any special packages) and represents a randomized design in R expressed in long-format.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Whole-plot</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#create Fungicide column and randomize its assignment to whole plot at the same time</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Fungicide =</span> <span class="fu">rep</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"B"</span>)), <span class="at">each =</span> <span class="dv">3</span>), </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">variety =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"variety1"</span>, <span class="st">"variety2"</span>, <span class="st">"variety3"</span>), <span class="at">times =</span> <span class="dv">4</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">yield =</span> <span class="cn">NA</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#These two lines randomize variety within each whole-plot</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Whole-plot</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variety =</span> <span class="fu">sample</span>(variety))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">pander</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-long_randomized" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-long_randomized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Randomized SP/RM[1,1] in Longer Format
</figcaption>
<div aria-describedby="tbl-long_randomized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Whole-plot</th>
<th style="text-align: center;">Fungicide</th>
<th style="text-align: center;">variety</th>
<th style="text-align: center;">yield</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="decomposition" class="level1 page-columns page-full">
<h1>Decomposition</h1>
<p>In this section we will do the analysis of variance by hand by decomposing the variation into its parts. We first review the factor structure with accompanying model terms for the fungicide study described above.</p>
<p>Ignoring Variety for a moment, you can see that the Residual Error for Fungicide should be estimated by how the larger experimental units vary. It’s the plot-to-plot variation.</p>
<p>If we treat each fungicide plot as a block, then the residual error for Variety will be the sub-plot-to-sub-plot variation within the blocks.</p>
<div class="column-page">
<p><img src="images/Split_Plot_Factor_Decomposition.png" width="950" height="152"></p>
</div>
<section id="factor-effects" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="factor-effects">Factor Effects</h2>
<p>We can use our understanding of <a href="./factor_structure.html">inside vs.&nbsp;outside factors</a> to estimate the effect size of the grand mean, treatment factor, blocks, and residual errors. Recall the general rule for estimating effect size of a factor:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
General Rule for Effect Size
</div>
</div>
<div class="callout-body-container callout-body">
<p>Effect size = Factor level mean - sum of the effects of all outside factors</p>
</div>
</div>
<p>We start by calculating factor level means.</p>
<section id="factor-level-means" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="factor-level-means">Factor Level Means</h3>
<p><a href="#fig-sprm-data-partition" class="quarto-xref">Figure&nbsp;5</a> shows our data set with partition lines for structural factors in place. We will proceed to calculate the factor level means for each factor.</p>
<div class="page-columns page-full">
<div id="fig-sprm-data-partition" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-sprm-data-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="images/sprm-data-partition.PNG" class="img-fluid figure-img column-page">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sprm-data-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Partitioned Split Plot Fungicide Example
</figcaption>
</figure>
</div>
</div>
<p>The grand mean is the mean of all the observations</p>
<p><span class="math display">\[
\hat{\mu} = \bar{y}_{\cdot\cdot\cdot} = \frac{200 + 214 + 214 + 214 + 202 + ... + 201}{24} = 209
\]</span></p>
<p>Now find the mean for each level of fungicide.</p>
<p><span class="math display">\[
\bar{y}_\text{Fung. A} = \bar{y}_{1 \cdot \cdot} = \frac{200 + 214 + 202 + 221 + 192 + 211}{6} = 206.\overline{66}
\]</span></p>
<p><span class="math display">\[
\bar{y}_\text{Fung. B} = \bar{y}_{2 \cdot \cdot} = \frac{214 + 214 + 220 + 204 + 215 + 201}{6}  = 211.\overline{33}
\]</span></p>
<p>Now find the mean for each plot (block).</p>
<p><span class="math display">\[
\bar{y}_\text{Plot 1} = \bar{y}_{1 1 \cdot} = \frac{200 + 202 + 192}{3}  = 198
\]</span></p>
<p><span class="math display">\[  
\bar{y}_\text{Plot 4} = \bar{y}_{1 2 \cdot} = \frac{214 + 221 + 211}{3}  = 215.\overline{33}
\]</span></p>
<p><span class="math display">\[   \bar{y}_\text{Plot 2} = \bar{y}_{2 1 \cdot} = \frac{214 + 220 + 215}{3}  = 216.\overline{33} \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{Plot 3} = \bar{y}_{2 2 \cdot} = \frac{214 + 204 + 201}{3}  = 206.\overline{33} \]</span></p>
<p>Now find the mean for each maize variety. <span class="math display">\[   \bar{y}_\text{variety 1} = \bar{y}_{\cdot \cdot 1} = \frac{200 + 214 + 214 + 214}{4}  = 210.5 \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{variety 2} = \bar{y}_{\cdot \cdot 2} = \frac{202 + 221 + 220 + 204}{4}  = 211.75 \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{variety 3} = \bar{y}_{\cdot \cdot 3} = \frac{192 + 211 + 215 + 201}{4}  = 204.75 \]</span> Now find the mean for each level of the interaction between fungicide and maize variety.</p>
<p><span class="math display">\[   \bar{y}_\text{Fung. A, variety 1} = \bar{y}_{1 \cdot 1} = \frac{200 + 214}{2}  = 207 \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{Fung. A, variety 2} = \bar{y}_{1 \cdot 2} = \frac{202 + 221}{2}  = 211.5 \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{Fung. A, variety 3} = \bar{y}_{1 \cdot 3} = \frac{192 + 211}{2}  = 201.5 \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{Fung. B, variety 1} = \bar{y}_{2 \cdot 1} = \frac{214 + 214}{2}  = 214 \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{Fung. B, variety 2} = \bar{y}_{2 \cdot 2} = \frac{220 + 204}{2}  = 212 \]</span></p>
<p><span class="math display">\[   \bar{y}_\text{Fung. B, variety 3} = \bar{y}_{2 \cdot 3} = \frac{215 + 201}{2}  = 208 \]</span></p>
<p>The mean for each level of residual is simply the value of the observation itself, so that is not repeated here. The means are put in the factor level diagram in <a href="#fig-means" class="quarto-xref">Figure&nbsp;6</a>.</p>
<div class="page-columns page-full">
<div id="fig-means" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="images/sprm_means.PNG" class="img-fluid figure-img column-page">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Factor Level Means
</figcaption>
</figure>
</div>
</div>
<p>Now that the factor level means for every factor are calculated, we can proceed to calculate factor level effects.</p>
</section>
<section id="factor-level-means-1" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="factor-level-means-1">Factor Level Means</h3>
<p>Now that we have calculated means for the levels of each factor, we can calculate the effects of the factor levels.</p>
<p>There is only one level of <strong>grand mean</strong> and there are no outside factors. Therefore, the effect due to grand mean is 22.76 (equivalent to its mean) and this effect is applied to all 24 observations.</p>
<p>The <strong>fungicide factor</strong> has two levels. The general rule for calculating factor level effects is implemented by subtracting the effect of grand mean (which is the only factor outside of fungicide) from the fungicide level mean:</p>
<p><span class="math display">\[
\alpha_\text{Fung. A} = \alpha_1 = 206.\overline(6) - 209 = -2.\overline{3}
\]</span></p>
<p><span class="math display">\[
\alpha_\text{Fung. B} = \alpha_2 = 211.\overline(3) - 209 = 2.\overline{3}
\]</span></p>
<p>To calculate the effect of plot, recall that plot is nested within fungicide. Therefore, the grand mean factor and fungicide type are both outside of plot. The sum of their factor level effects must be subtracted from the factor level mean of each plot respectively.</p>
<p><span class="math display">\[
\beta_\text{plot 1} = \beta_{11} = 198 - (209 + -2.\overline{3})  = -8.\overline{6}
\]</span></p>
<p><span class="math display">\[
\beta_\text{plot 4} = \beta_{11} = 215.\overline{3} - (209 + -2.\overline{3})  = 8.\overline{6}
\]</span></p>
<p><span class="math display">\[
\beta_\text{plot 2} = \beta_{21} = 216.\overline{3} - (209 + 2.\overline{3})  = 5
\]</span></p>
<p><span class="math display">\[
\beta_\text{plot 3} = \beta_{22} = 206.\overline{3} - (209 + 2.\overline{3})  = -5
\]</span></p>
<p>Variety is crossed with fungicide and crossed with plot, therefore, grand mean effect is the only factor outside of variety and so it is the only value subtracted from variety’s factor level mean. The effect of Variety is calculated as follows:</p>
<p><span class="math display">\[
\gamma_\text{variety 1} = \gamma_{1} = 210.5 - 209  = -1.5
\]</span></p>
<p><span class="math display">\[
\gamma_\text{variety 2} = \gamma_{2} = 211.75 - 209  = 2.75
\]</span></p>
<p><span class="math display">\[
\gamma_\text{variety 3} = \gamma_{3} = 204.75 - 209  = -4.25
\]</span></p>
<p>The interaction between fungicide and variety is the next variable for which to to calculate factor level effects. To calculate the interaction effects, the factors outside of the interaction must be identified. The factors used to create the interaction (fungicide and variety) will always be outside of the interaction factor itself. Is Fungicide by Variety outside of Plot? Overlay one partition of the interaction on the Plot partition and you will see it does not fit neatly inside of a partition. Each partition of the interaction actually spans across to plot partitions. Therefore, Plot is NOT outside of the interaction factor. More generally, the block factor is not outside of the interaction of between-block and within-block factors. Grand mean is outside of the interaction. The interaction level factor effects are calculated below.</p>
<p><span class="math display">\[
(\alpha \gamma)_\text{Fung A, variety 1} = (\alpha \gamma)_{11} = 207 - (209 + -2.\overline{3} + 1.5)  = -1.\overline{6}
\]</span></p>
<p><span class="math display">\[
(\alpha \gamma)_\text{Fung A, variety 2} = (\alpha \gamma)_{12} = 211.5 - (209 + -2.\overline{3} + 2.75)  = -2.41\overline{6}
\]</span></p>
<p>and so on for each combination. The general formula for finding the effect of the interaction is</p>
<p><span class="math display">\[
(\alpha \gamma)_{ik} = \bar{y}_{i \cdot k} - (\bar{y}_{\cdot \cdot \cdot} + \alpha_i + \gamma_k)
\]</span> Finally, the residual effects need to be calculated. All other factors are outside of the residual factor. To calculate a residual, take the observed value and note what level it belongs to for each of the factors. Sum the effects of factor levels the observed value belongs to, then subtract that sum from the observed value.</p>
<p>As an example, one of our observations has a value of 220. The particular observation belongs to plot 2 and so received Fungicide B. Also, the observation came from Variety 2 of maize. Adding the effects from those factor levels (including the grand mean and the interaction effect) results in a predicted value of <span class="math inline">\(217.08\overline{3}\)</span>:</p>
<p><span class="math display">\[
209 + 2.\overline(3) + 5 + 2.75 + -2 = 217.08\overline{3}
\]</span> To find the residual, that predicted value is subtracted from the actual value:</p>
<p><span class="math display">\[e_{212} = 220 - 217.08\overline{3} = 2.91\overline{6}\]</span></p>
<p><a href="#fig-factor_effects" class="quarto-xref">Figure&nbsp;7</a> shows the decomposition for all the values in the dataset, with the observed value of <span class="math inline">\(y_{212} = 220\)</span> and its corresponding factor level effects in bold.</p>
<div class="page-columns page-full">
<div id="fig-factor_effects" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-factor_effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="images/sprm_factor_effects.PNG" class="img-fluid figure-img column-page">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-factor_effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Decomposition Into Factor Level Effects (rounded)
</figcaption>
</figure>
</div>
</div>
</section>
</section>
<section id="degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h2>
<p>In this example, there are a total of 12 degrees of freedom to be allocated because there were 12 observations.</p>
<p>As in the case with other models, one degree of freedom is used to estimate the grand mean.</p>
<p>One can use the “counting unique factor effects” approach, or the general rule to find the degrees of freedom for the other factors.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
General Rule for Degrees of Freedom
</div>
</div>
<div class="callout-body-container callout-body">
<p>Degrees of Freedom for a factor = Total levels of a factor minus the sum of the degrees of freedom of all outside factors</p>
</div>
</div>
<p>The Fungicide effect, has just two levels. If you know the effect for one level, the other fungicide’s effect can be deduced because factor level effects must sum to zero. This means fungicide has 1 degree of freedom.</p>
<p>To use the general rule to determine degrees of freedom for Fungicide you must recognize that Grand Mean is the only factor outside of Fungicide. Therefore, the calculation becomes <span class="math inline">\(2-1 = 1\)</span>.</p>
<p>The factors outside of Plot include Grand Mean and Fungicide. The degrees of freedom calculation for Plot, which has 4 levels, is <span class="math inline">\(4 - (1 + 1)\)</span>, where 1 and 1 are the degrees of freedom for Grand Mean and Fungicide respectively. Alternatively, degrees of freedom for Plot can be found by observing that factor effects of Plot sum to zero within each Fungicide partition. Thus, knowing just 2 factor effects enables you to discover the other two. The degrees of freedom for Plot are therefore 2.</p>
<p>Likewise, the degrees of freedom for Variety is two because you only need to know 2 of the three effects to determine the value of the third. If the general rule is used, you start by observing that variety has 3 levels. Grand mean is the only factor outside of Variety. Therefore, the degrees of freedom for Variety is 3-1 = 2.</p>
<p>There are 6 levels to the the interaction between Fungicide and Variety. Factors outside of the interaction include: Variety (2 d.f.), Fungicide (1 d.f.) and the grand mean (1 d.f.). Using the general rule results in 6 - (2 + 1 + 1) = 2 degrees of freedom for the Fungicide by Variety interaction. effect only has 2 degrees of freedom because each of the fungicide treatment combinations must sum to zero across varieties.</p>
<p>There are two other ways to find degrees of freedom for the interaction. First, note that factor level effect sum to zero across rows and columns. Due to that constraint, after 2 of the 6 effects are known the rest become locked in. Lastly, and perhaps the most method for finding degrees of freedom for the interaction, is to multiply the degrees of freedom of the factors that were crossed to create the interaction.</p>
<p>The degrees of freedom for residuals is equal to the total number of observations minus the degrees of freedom used to estimate all the other factor effects, <span class="math inline">\(12 - (1 + 1 + 2 + 2 + 2) = 4\)</span>. You can also notice a pattern in the residuals and how they sum to zero. Do you see why only 4 residuals need to be known before the rest can be filled in?</p>
</section>
<section id="completing-the-anova-table" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="completing-the-anova-table">Completing the ANOVA Table</h2>
<p>Now that we have calculated degrees of freedom and effects for each factor, we can calculate the remaining pieces of the ANOVA table: <strong>Sum of Squares (SS), Mean Squares (MS), F-statistic and p-value</strong>. A completed ANOVA summary table contains the information we need for a hypothesis test of the treatment effects.</p>
<p>In an ANOVA table, each factor and their associated degrees of freedom are listed on the left. Note: the total degrees of freedom are the total number of observations.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fungicide</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plot</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fung. x Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>To get the <strong>sum of squares (SS)</strong> of a factor, the effects of the factor must be squared, and then summed. <a href="#fig-factor_effects" class="quarto-xref">Figure&nbsp;7</a> shows the effects, while <a href="#fig-sprm_SS" class="quarto-xref">Figure&nbsp;8</a> shows the squared effects for all but the grand mean.</p>
<div class="page-columns page-full">
<div id="fig-sprm_SS" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-sprm_SS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="images/sprm_SS.PNG" class="img-fluid figure-img column-page">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sprm_SS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Squared Effects (rounded)
</figcaption>
</figure>
</div>
</div>
<p>The total sum of squares is obtained by summing the squared observations as shown in <a href="#eq-ss_total" class="quarto-xref">Equation&nbsp;2</a> . This represents the total variability in the dataset that will then be allocated or partitioned to the various factors, starting with the grand mean.</p>
<p><span id="eq-ss_total"><span class="math display">\[
SS_\text{total}= 200^2 + 214^2 + ... + 201^2 = 525060
\tag{2}\]</span></span></p>
<p>The <strong>grand mean</strong> squared is <span class="math inline">\(209^2 = 43681\)</span> and is listed 12 times since all observations have the grand mean applied as part of their decomposition. Summing the squared effects gets:</p>
<p><span class="math display">\[
SS_\text{Grand Mean}= 209^2 * 12 = 524,172
\]</span></p>
<p>Similarly, we get the sum of squares for the remaining factors.</p>
<span class="math display">\[\begin{align}
SS_\text{Fungicide} &amp;= 12 * 5.\overline{4} = 65.\overline{3}\\
\\
SS_\text{Plot} &amp;= 6 * (75.\overline{1} + 25) = 600.\overline{6}\\
\\
SS_\text{Variety} &amp;= 4 * (2.25 + 7.5625 + 18.0625) = 111.5\\
\\
SS_\text{Fung. x Variety Interaction} &amp;= 4 * ( 1.36\overline{1} + 4.3402\overline{7} +  0.8402\overline{7}) = 12.1\overline{6}\\
\\
SS_\text{Residuals} &amp;= 2 * (2.\overline{7} + 25 + .69\overline{4} + 9 + .69\overline{4} + 4) = 84.\overline{3}

\end{align}\]</span>
<p>Putting this information into the ANOVA table gets us the result shown in <a href="#tbl-ss_anova" class="quarto-xref">Table&nbsp;3</a>.</p>
<div class="cell">
<div id="tbl-ss_anova" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ss_anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Sums of Squares
</figcaption>
<div aria-describedby="tbl-ss_anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">524172.00</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fungicide</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">65.33</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plot</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">600.67</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">111.50</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fung. x Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">26.17</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">84.33</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">525060.00</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
<p>To calculate a mean square (MS), simply divide a factor’s sum of squares by its degrees of freedom. The mean square calculations are:</p>
<p><span class="math display">\[
MS_\text{factor} = \frac{SS_\text{factor}}{df_\text{factor}}
\]</span></p>
<p><br></p>
<div class="cell">
<div id="tbl-ms_anova" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ms_anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Mean Squares
</figcaption>
<div aria-describedby="tbl-ms_anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">524172.00</td>
<td style="text-align: right;">524172.00</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fungicide</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">65.33</td>
<td style="text-align: right;">65.33</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plot</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">600.67</td>
<td style="text-align: right;">300.33</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">111.50</td>
<td style="text-align: right;">55.75</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fung. x Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">26.17</td>
<td style="text-align: right;">13.08</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">84.33</td>
<td style="text-align: right;">21.08</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">525060.00</td>
<td style="text-align: right;">43755.00</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
<p>For the structural factors in <a href="#eq-sprm" class="quarto-xref">Equation&nbsp;1</a> there are a set of hypothesis we can test using the <strong>F statistic</strong>. The first hypotheses we will address deals with the between-block factor, Fungicide.</p>
<p><span class="math display">\[H_0: \alpha_1 = \alpha_2 = 0 \]</span></p>
<p><span class="math display">\[H_a: \alpha_i \ne 0 \text{ for some }i\]</span></p>
<p>At this point, it becomes super critical to recognize the two levels of experimental units and the amount of replication for each factor. For the Fungicide factor, as pointed out earlier, Plot is the experimental unit.</p>
<p>This means that the Sum of Squares for Plot is actually capturing the unexplained variance (i.e.&nbsp;the error) from plot to plot that couldn’t be explained by the difference in Fungicide. In other words, Plot is the error term for Fungicide. Thus, the Mean Squares for Plot should be used in the denominator of the F test for Fungicide.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> The result of this calculation is shown below (rounded to 2 decimal places).</p>
<p><span class="math display">\[
F_\text{Fungicide} = \frac{MS_\text{Fungicide}}{MS_\text{Plot}} = \frac{65.\overline{3}}{300.\overline{3}} = .216
\]</span></p>
<p>An F distribution is defined by two parameters: a numerator degrees of freedom and a denominator degrees of freedom. The numerator degrees of freedom is the degrees of freedom for Fungicide. The denominator in the F statistic calculation was the mean squares for Plot, which has a degrees of freedom of 2. The p-value for an F statistic of 0.216 with 1 and 2 degrees of respectively is 0.69.</p>
<p>The p-value is larger than any reasonable level of significance. We therefore have insufficient evidence to suggest that type of Fungicide has an effect on maize yield.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
F-test for between-block factor
</div>
</div>
<div class="callout-body-container callout-body">
<p>In general terms, the F-test for the between-block is calculated as:</p>
<p><span id="eq-f"><span class="math display">\[
F_\text{between-block factor} = \frac{MS_\text{between-block factor}}{MS_\text{block factor}}
\tag{3}\]</span></span></p>
<p>The numerator degrees of freedom for the F statistic is the degrees of freedom for between-block factor. The denominator degrees of freedom is the degrees of freedom for blocks.</p>
</div>
</div>
<p>We now work through hypotheses tests for the other terms in <a href="#eq-sprm" class="quarto-xref">Equation&nbsp;1</a>. The other factors we will test all have sub-plots as their experimental units. Mean squared error represents the unexplained variance from sub-plot to sub-plot. Therefore, like we have done with all past designs, the mean squared error will be the denominator of those F tests.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Since Plot is a random, blocking factor, we will not formally work through the hypothesis test here, even though the test is typically included in the ANOVA table.</p>
</div></div><p>They hypotheses for maize variety is,</p>
<p><span class="math display">\[H_0: \gamma_1 = \gamma_2 = \gamma_3 = 0 \]</span></p>
<p><span class="math display">\[H_a: \gamma_k \ne 0 \text{ for some }k\]</span></p>
<p>and the hypothesis for the interaction of Fungicide and Variety is,</p>
<p><span class="math display">\[H_0: (\alpha \gamma)_{ik} = 0 \text{ for all }ik\]</span></p>
<p><span class="math display">\[H_a: (\alpha \gamma)_{ik} \ne 0 \text{ for some }ik\]</span>.</p>
<p>For both of these tests, the F statistic is obtained by dividing the factor’s mean squares by the mean squared error.</p>
<p><span class="math display">\[
\begin{align}
F_\text{Variety} &amp;= F_\text{2,4} = \frac{55.75}{21.08\overline{3}} =  2.64\\
\\
F_\text{Interaction} &amp;= F_\text{2,4} = \frac{13.08\overline{3}}{21.08\overline{3}} =  0.62 \\
\\
\end{align}
\]</span></p>
<p>The numerator degrees of freedom is 2 for both of these F statistics because each of the factors being tested has 2 degrees of freedom respectively. The denominator degrees of freedom for both tests is 4 because both use the mean square error in the denominator of the tests.</p>
<p>The p-values associated with these F statistics is 0.186 and 0.583 respectively. Neither factor is significant.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpret the Test for Interaction First
</div>
</div>
<div class="callout-body-container callout-body">
<p>As with other designs and models that involve an interaction, the highest order interaction should be interpreted first. If the interaction is significant, hypothesis tests for lower order interactions and main effects should not be interpreted.</p>
<p>If the interaction is not significant (as was the case here), you can proceed to evaluate hypothesis tests for lower order interactions (if there are any) and main effects (assuming all higher order interactions involving that factor are not significant).</p>
</div>
</div>
<p>The ANOVA table is now completed:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Mean Squares</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Fvalue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grand Mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">524172.00</td>
<td style="text-align: right;">524172.00</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fungicide</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">65.33</td>
<td style="text-align: right;">65.33</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plot</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">600.67</td>
<td style="text-align: right;">300.33</td>
<td style="text-align: right;">14.25</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">111.50</td>
<td style="text-align: right;">55.75</td>
<td style="text-align: right;">2.64</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fung. x Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">26.17</td>
<td style="text-align: right;">13.08</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.58</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residual Error</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">84.33</td>
<td style="text-align: right;">21.08</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">525060.00</td>
<td style="text-align: right;">43755.00</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</section>
</section>
<section id="analysis-in-r" class="level1 page-columns page-full">
<h1>Analysis in R</h1>
<p>When working with a dataset the first thing to do is get to know your data through numerical and graphical summaries. Interactive code and additional explanations of numerical summaries and plots in R are found at <a href="DescribeData.html">R Instructions-&gt;Descriptive Summaries</a> section of the book.</p>
<section id="numerical-summaries" class="level3">
<h3 class="anchored" data-anchor-id="numerical-summaries">Numerical Summaries</h3>
<p>After loading required packages, we will read in the data and calculate summary statistics for each factor level separately.</p>
<div class="cell" data-cap="Read in Data">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sprm <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Split_Plot.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">plot =</span> <span class="fu">as.factor</span>(plot),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">variety =</span> <span class="fu">as.factor</span>(variety))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#why not working</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><a href="javascript:showhide('tablesummaries')"><span style="font-size:8pt;">click this link to hide numerical output summaries</span></a></p>
<div id="tablesummaries">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of fungicide</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(yield <span class="sc">~</span> fungicide, <span class="at">data =</span> sprm) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of plot</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(yield <span class="sc">~</span> plot, <span class="at">data =</span> sprm) <span class="sc">|&gt;</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of variety</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(yield <span class="sc">~</span> variety, <span class="at">data =</span> sprm) <span class="sc">|&gt;</span> </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive stats for levels of fungicide by variety</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(yield <span class="sc">~</span> fungicide <span class="sc">+</span> variety, <span class="at">data =</span> sprm) <span class="sc">|&gt;</span> </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-main_effects_numbers" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-main_effects_numbers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: [“Between-block Factor: Fungicide”,“Block Factor: Plot”,“Within-block Factor: Variety”,“Between-block x Within-block Interaction: Factor x Variety”]
</figcaption>
<div aria-describedby="tbl-main_effects_numbers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">fungicide</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">192</td>
<td style="text-align: right;">200.5</td>
<td style="text-align: right;">206.5</td>
<td style="text-align: right;">213.25</td>
<td style="text-align: right;">221</td>
<td style="text-align: right;">206.67</td>
<td style="text-align: right;">10.58</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">206.5</td>
<td style="text-align: right;">214.0</td>
<td style="text-align: right;">214.75</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">211.33</td>
<td style="text-align: right;">7.26</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell-output-display">
<div>
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">plot</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">192</td>
<td style="text-align: right;">196.0</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">201.0</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">198.00</td>
<td style="text-align: right;">5.29</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">214.5</td>
<td style="text-align: right;">215</td>
<td style="text-align: right;">217.5</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">216.33</td>
<td style="text-align: right;">3.21</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">202.5</td>
<td style="text-align: right;">204</td>
<td style="text-align: right;">209.0</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">206.33</td>
<td style="text-align: right;">6.81</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">212.5</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">217.5</td>
<td style="text-align: right;">221</td>
<td style="text-align: right;">215.33</td>
<td style="text-align: right;">5.13</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell-output-display">
<div>
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">variety</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">210.50</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">214.00</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">210.50</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">203.50</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">220.25</td>
<td style="text-align: right;">221</td>
<td style="text-align: right;">211.75</td>
<td style="text-align: right;">10.14</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">192</td>
<td style="text-align: right;">198.75</td>
<td style="text-align: right;">206</td>
<td style="text-align: right;">212.00</td>
<td style="text-align: right;">215</td>
<td style="text-align: right;">204.75</td>
<td style="text-align: right;">10.34</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell-output-display">
<div>
<table class="table do-not-create-environment cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">fungicide.variety</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A.1</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">203.50</td>
<td style="text-align: right;">207.0</td>
<td style="text-align: right;">210.50</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">207.0</td>
<td style="text-align: right;">9.90</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B.1</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">214.00</td>
<td style="text-align: right;">214.0</td>
<td style="text-align: right;">214.00</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">214.0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A.2</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">206.75</td>
<td style="text-align: right;">211.5</td>
<td style="text-align: right;">216.25</td>
<td style="text-align: right;">221</td>
<td style="text-align: right;">211.5</td>
<td style="text-align: right;">13.44</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B.2</td>
<td style="text-align: right;">204</td>
<td style="text-align: right;">208.00</td>
<td style="text-align: right;">212.0</td>
<td style="text-align: right;">216.00</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">212.0</td>
<td style="text-align: right;">11.31</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A.3</td>
<td style="text-align: right;">192</td>
<td style="text-align: right;">196.75</td>
<td style="text-align: right;">201.5</td>
<td style="text-align: right;">206.25</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">201.5</td>
<td style="text-align: right;">13.44</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B.3</td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">204.50</td>
<td style="text-align: right;">208.0</td>
<td style="text-align: right;">211.50</td>
<td style="text-align: right;">215</td>
<td style="text-align: right;">208.0</td>
<td style="text-align: right;">9.90</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<p>Fungicide B has a slightly higher mean yield, but the standard deviation for each fungicide means the difference in mean yield between A and B is likely not significant. Maize Variety 2 had the highest mean yield, but not by much. There is quite a bit of variation between plots. As for the interaction, there are only 2 observations per treatment. The combination of “B.1” has no standard deviation.</p>
</section>
<section id="graphical-summaries" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="graphical-summaries">Graphical Summaries</h3>
<p>You could also gain insight about your data graphically, as shown in <a href="#fig-graphical_summary" class="quarto-xref">Figure&nbsp;9</a>. The plots reinforce what was observed in the numerical summary. Especially, it is important to know that there are two observations in the “Fungicide B, Variety 1” condition, but because the observations have identical values only 1 point appears.</p>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sprm, <span class="fu">aes</span>(<span class="at">x =</span> variety, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(fungicide)) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Maize Yield"</span>, <span class="at">y =</span> <span class="st">"Bushels / acre"</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> .<span class="dv">5</span>))</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sprm, <span class="fu">aes</span>(<span class="at">x =</span> plot, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Maize Yield"</span>, <span class="at">y =</span> <span class="st">"Bushels / acre"</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> .<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-graphical_summary" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-graphical_summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<div>

</div>
<div class="cell column-page-inset quarto-layout-panel" data-layout-nrow="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="split_plot_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="split_plot_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-graphical_summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Graphical Summaries for Controlled Factors
</figcaption>
</figure>
</div>
</section>
<section id="create-the-model" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="create-the-model">Create the Model</h2>
<p>Create the model using the <code>aov()</code> function. To see results of the hypothesis test for each factor you can feed your model into a <code>summary()</code> or <code>anova()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sprm_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Y <span class="sc">~</span> between_block_factor <span class="sc">+</span> block <span class="sc">+</span> within_block_factor <span class="sc">+</span> between_block_factor<span class="sc">:</span>within_block_factor, <span class="at">data =</span> YourDataSet)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sprm_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>sprm_aov</code> is the user defined name in which the results of the aov() model are stored</li>
<li><code>Y</code> is the name of a numeric variable in your dataset which represents the quantitative response variable.</li>
<li><code>between_block_factor</code> is the name of factor in your dataset. It represents the treatment that is applied to blocks.</li>
<li><code>block</code> is a factor used to identify each block. Remember that blocks are nested within <code>between_block_factor</code> and serve as the experimental unit for that factor.</li>
<li><code>within_block_factor</code> is a factor whose values vary inside of each block.</li>
<li><code>between_block_factor:within_block_factor</code> is the interaction between two factors.</li>
<li><code>YourDataSet</code> is the name of your data set.</li>
</ul>
<p>Note that each factor should be a categorical variable. If the variable is not already a character or factor data type in R, you can convert it to a factor variable with the <code>factor()</code> function.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Order Matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>The order in which the variables are specified in the model can effect the resulting F test of the factors. The factors applied to blocks must be listed before the block variable.</p>
<p>Thus the model defined as</p>
<p><code>aov(yield ~ fungicide*variety + plot, data = sprm)</code></p>
<p>still works, but the following model does not</p>
<p><code>sprm_aov &lt;- aov(yield ~ plot + fungicide*variety, data=sprm)</code></p>
<p>because the block factor comes before the between block factor.</p>
</div>
</div>
<p>The results using R code should match the results shown in the decomposition performed earlier.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sprm_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(yield <span class="sc">~</span> fungicide <span class="sc">+</span> plot <span class="sc">+</span> variety <span class="sc">+</span> fungicide<span class="sc">:</span>variety, <span class="at">data=</span>sprm)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sprm_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value Pr(&gt;F)  
fungicide          1   65.3   65.33   3.099 0.1532  
plot               2  600.7  300.33  14.245 0.0152 *
variety            2  111.5   55.75   2.644 0.1854  
fungicide:variety  2   26.2   13.08   0.621 0.5825  
Residuals          4   84.3   21.08                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>First, the hypothesis test of the the interaction of fungicide and variety is evaluated, because the significance of the interaction can impact how/if the hypothesis test for the main effects is evaluated. In this case, we see that the interaction is not significant (<em>p = .5825</em>). We can proceed to evaluate the main effect tests.</p>
<p>Maize variety (<em>p=0.1854</em>) is also not a significant factor in explaining yield. <strong>The p-value (<em>p=0.1532</em>) and F statistic for fungicide in the output are not correct</strong>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Correct F Statistic and P-value for a Test of the Between Block Factor
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remember, that the experimental unit for fungicide is actually plot. Therefore, the Mean Squares for plot needs to be the denominator of the F statistic for fungicide. By default, R uses the Mean Squared Residuals in the denominator, which is not correct in this case.</p>
</div>
</div>
<p>The correct F-statistic is calculated as:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The rationale/reasoning behind this calculation is directly connected with the explanation of Expected Mean Squares (EMS) given on the Random Factors page.</p>
</div></div><p><span class="math display">\[
\frac{MS_{fungicide}}{MS_{plot}} = \frac{65.33}{300.33} = 0.2175
\]</span></p>
<p>The degrees of freedom for this F statistic are the degrees of freedom of it’s numerator and denominator mean squares, respectively.</p>
<p><span class="math display">\[
F_{1,2} = 0.2175
\]</span></p>
<p>The area under the <span class="math inline">\(F_{1,2}\)</span> distribution to the right of the F test statistic constitutes the p-value. In this case, it is <strong>p=</strong> <strong>0.687</strong>. With such a high p-value, we conclude there is insufficient evidence that fungicide effects yield.</p>
<p>Though we calculated the correct p-value by-hand, there is other R code, not covered in this book, that will calculate the correct F test by default.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>We are not formally conducting a hypothesis test for plot, since it is considered a nuisance factor. However, it appears to contribute a significant amount of variation to yield, as evidenced by the low p-value of <em>0.0152</em>.</p>
<p>A lack of significance in the factors of interest does not absolve our need to check assumptions. In order to trust these hypothesis test results we need to verify that the assumptions are met.</p>
</section>
<section id="check-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-assumptions">Check Assumptions</h2>
<p>For a more detailed explanation of the code, output, and theory behind these assumptions visit the <a href="./assumptions.html">Assumptions</a> page.</p>
<section id="constant-error-variance" class="level3">
<h3 class="anchored" data-anchor-id="constant-error-variance">Constant Error Variance</h3>
<p>There needs to be constant variance across the factor levels. To verify this assumption is met, check the residual plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sprm_aov, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="split_plot_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If the constant variance assumption is violated, the points in this graph will show a wedge or megaphone shape. In other words, the vertical spread of the points would noticeably increase/decrease as we moved along the x-axis.</p>
<p>It is difficult to say whether this assumption is met. The issue is further complicated by the fact that there is a group (fungicide = B, variety = 1) where there is no variation in yield. The standard deviation of the other groups (calculated in the <a href="#numerical-summaries">Numerical Summaries</a>) are relatively close to each other. Furthermore, the sample sizes are small, making it difficult to conclude any observed differences are anything more than random chance. In summary, there is not strong evidence that the constant variance assumption is violated.</p>
</section>
<section id="normally-distributed-error-term" class="level3">
<h3 class="anchored" data-anchor-id="normally-distributed-error-term">Normally Distributed Error Term</h3>
<p>We check the assumption that residuals are normally distributed with a QQ plot. Since all the points in the plot closely follow the line, we conclude this assumption is met.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sprm_aov, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="split_plot_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="independent-residuals" class="level3">
<h3 class="anchored" data-anchor-id="independent-residuals">Independent Residuals</h3>
<p>The dataset we are analyzing was not gathered sequentially or chronologically. The experiment with various treatment combinations was conducted simultaneously. Therefore, the order plot will not be useful to include.</p>
<p>The observations were related spatially, however. Because the model has accounted for the nested, spatial relationships by using a hierarchical model (i.e.&nbsp;2 levels of experimental units), the residuals will not be correlated. Each residual will be independent, not correlated, with other residuals.</p>
</section>
<section id="assumptions-summary" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-summary">Assumptions Summary</h3>
<p>The assumptions could not be refuted, suggesting that an ANOVA model is appropriate to use in this example.</p>


</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Some textbooks prefer to represent the blocking term as another epsilon term, since it represent the random error of the experimental units of the between-block factor. In that case the two error terms may be distinguished with a superscript and look like this:</p>
<p><span class="math display">\[   y_{iujt} = \mu + \alpha_i + \epsilon_{iu}^{W}  + \beta_j + (\alpha \beta)_{ij} + \epsilon_{jiu)}^{S}   \]</span></p>
<p>Where <span class="math inline">\(\epsilon_{iu}^{W} \sim N(0, \sigma_W^2)\)</span>, and <span class="math inline">\(\epsilon_{jiu}^{S} \sim N(0, \sigma_S^2)\)</span>. Both error terms are mutually independent.</p>
<p>When replication occurs within a block (whole plot), usually subscript <em>t</em> is used to denote each replicate.</p>
<p>Another common convention is the use of parenthesis in the subscripts to emphasize the nested relationship of factors. For example:</p>
<p><span class="math display">\[   y_{iuj} = \mu + \gamma_i + \epsilon_{i(u)}^{W}  + \beta_j + (\gamma \beta)_{ij} + \epsilon_{j(iu)}^{S}   \]</span></p>
<p>Here you can see that the block factor, still represented as <span class="math inline">\(\epsilon^W\)</span> has the subscript <span class="math inline">\(i(u)\)</span> to emphasize the fact that the levels of the block factor, <em>u</em>, are nested within the between-block factor. The parenthesis flow through to the <span class="math inline">\(\epsilon^S\)</span> as well. However, convention typically removes them from the subscript of <em>y</em>. Here is the expression again, this time including <em>t</em> subscript for within block replication.</p>
<p><span class="math display">\[   y_{iujt} = \mu + \gamma_i + \epsilon_{i(u)}^{W}  + \beta_j + (\gamma \beta)_{ij} + \epsilon_{jt(iu)}^{S}   \]</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>If we think of the subplots at the top as the north plot and the subplot at the bottom of each plot as the south plot, and the one in the middle as a middle plot that may introduce another source of variability. In the example so far we are ignoring the location of the sub-plot within the whole-plot. Or in other words, we are treating all 3 subplot locations as equal, not a source of variability. If the plots are small enough, it does seem reasonable to assume the effect of north vs.&nbsp;south will be negligible. If however, we want to address the risk that location of the subplot within the whole-plot is meaningful we must add another factor to the design. We would want to prevent “unlucky” randomizations that confound the effect of subplot plot <em>location</em> with variety. (If we were doing repeated measures, you can think of confounding order with the within-block factor).</p>
<!-- We can conduct an approach similar to Latin-square randomization for within plot assignments, rather than the simpler complete block. -->
<!-- ```{r} -->
<!-- #| code-fold: true -->
<!-- #Take a "latin-square" approach to randomizing the sub-plots: randomly rearranging rows and column. It's not exactly a latin square because it has an extra row, but it should help to prevent bad randomizations by helping ensure each variety appears in each subplot -->
<!-- my_df <- tribble( -->
<!--   ~`North sub-plot`, ~`Mid sub-plot`, ~`South sub-plot`, -->
<!--   "variety1", "variety2", "variety3", -->
<!--   "variety2", "variety3", "variety1", -->
<!--   "variety3", "variety1", "variety2", -->
<!--   "variety1", "varitey2", "variety3" -->
<!-- ) -->
<!-- set.seed(17) -->
<!-- randomized <- my_df[sample(nrow(my_df)), sample(ncol(my_df))] %>%  -->
<!-- #Then combine it with the random assignment of the whole-plot factor -->
<!--   bind_cols(`Whole-plot` = seq(1,4), Fungicide = sample(c("A", "A", "B", "B"))) %>%  -->
<!--   relocate(`Whole-plot`, Fungicide) -->
<!-- pander(randomized) -->
<!-- ``` -->
<!-- You may need to work with the data in longer form instead of the wider form. You can `pivot_wider` the table above. Another approach is contained in the R code below that doesn't require you to create a "wide" table first. -->
<p>Note that the code below starts by forcing each variety to show up at least once in a North subplot (i.e.&nbsp;first position). This is a strategic way to ensure a better spread and prevent getting “unlucky” random assignment that preserves the bias/confounding from the unrandomized design. Then, for the fourth plot, if there are still gaps in the randomization, a strategic assignment can be made to ensure each variety is represented in each sub-plot level. Or, if there is already sufficient coverage, simply assign each variety randomly to a subplot in the 4th plot.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">19</span>) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>first3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"variety1"</span>, <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"variety2"</span>, <span class="st">"variety3"</span>)),    </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">"variety2"</span>, <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"variety1"</span>, <span class="st">"variety3"</span>)),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"variety3"</span>, <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"variety1"</span>, <span class="st">"variety2"</span>))) </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>all4 <span class="ot">&lt;-</span> <span class="fu">c</span>(first3, <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"variety1"</span>, <span class="st">"variety2"</span>, <span class="st">"variety3"</span>)))  </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">variety =</span> all4) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(   <span class="at">Fungicide =</span> <span class="fu">rep</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"B"</span>)), <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                      <span class="st">`</span><span class="at">Whole-plot</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">3</span>),   </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">yield =</span> <span class="cn">NA</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(<span class="st">`</span><span class="at">Whole-plot</span><span class="st">`</span>, Fungicide) <span class="sc">%&gt;%</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pander</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Whole-plot</th>
<th style="text-align: center;">Fungicide</th>
<th style="text-align: center;">variety</th>
<th style="text-align: center;">yield</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety1</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety3</td>
<td style="text-align: center;">NA</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">variety2</td>
<td style="text-align: center;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></li>
<li id="fn3"><p>Another way to think about the F test is a ratio of Sum of Square for a “full model” to a “reduced model”. This is explained <a href="https://online.stat.psu.edu/stat501/lesson/6/6.2">here</a>. In this case, the full model includes Fungicide as well as Plots. The reduced model just has Plot. The other factors (variety and the interaction) are ignored since they are at the small experimental unit.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>For example, the following code gives the correct F test for fungicide and the other factors in the model</p>
<p><code>myaov&lt;- aov(yield ~ fungicide*variety + Error(plot), data = sprm)</code></p>
<p><code>summary(myaov)</code></p>
<p>In this case, a different class of object is created, which isn’t compatible with many of the other commands we have learned so far. Other packages are specifically designed to handle models like this, otherwise known as mixed models or hierarchical models. A list of such packages can be <a href="https://cran.r-project.org/web/views/MixedModels.html">found here</a>, but the simplest, most common, and easiest to use in basic cases is <code>lme4</code> .<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>